import { EVT } from '../EVT'
import { settings, OptionCategoryLevel1 } from './Settings'
import { lang } from '../Language'
import { LangTextKey } from '../langText'

type CategorySchema = {
  [key in OptionCategoryLevel1]: {
    /** 一级分类的 ID */
    id: OptionCategoryLevel1
    /** 一级分类的顺序 */
    order: number
    /** 一级分类的名称的 i18n 的 key */
    nameKey: LangTextKey
    // 分类名字只需要保存 key 就行了，不需要获取实际文本，等到需要显示的时候再动态获取即可
    /** 二级分类 */
    level2: {
      /** 二级分类的 ID */
      [key: string]: {
        /** 二级分类的 ID */
        id: string
        /** 二级分类的顺序 */
        order: number
        /** 二级分类的名称的 i18n 的 key */
        nameKey: LangTextKey
        /** 二级分类的图标 */
        icon: string
      }
    }
  }
}

/** 每个设置的元数据 */
type OptionMeta = {
  /** 每个设置的编号，它会被用来查找设置所在的卡片，以便对卡片进行操作 */
  no: number
  /** 设置名称的 i18n 的 key */
  nameKey: LangTextKey
  /** 设置名称的实际文本 */
  name: string
  /** 所属的一级分类 */
  categoryLevel1: OptionCategoryLevel1
  /** 所属的二级分类 */
  categoryLevel2: string
  /** 该设置的搜索关键词的 i18n 的 key。可能是空数组，因为有些设置的名字就够用了，没有其他推荐的关键词 */
  searchWordKeys: LangTextKey[]
  /** 该设置的搜索关键词 */
  searchWords: string[]
  /** 是否置顶 */
  pinned: boolean
  /** 是否是定制选项。只有定制的选项有这个属性。如果没有这个属性或者为 false，则表示不是定制选项 */
  isCustom?: boolean
  /** 是否在移动端隐藏。只有需要隐藏时才会有这个属性。如果没有这个属性或者为 false，则表示在移动端显示 */
  hideOnMobile?: boolean
  /** 是否在 pixivision 隐藏。只有需要隐藏时才会有这个属性。如果没有这个属性或者为 false，则表示在 pixivision 显示 */
  hideOnPixivision?: boolean
  /** 添加该设置项时的时间戳。新增的设置需要添加这个属性，旧设置不需要这个属性，因为它是为了显示“new”角标而存在的，旧设置用不到 */
  addedAt?: number
}

/** 把所有设置按照分类层级进行组织 */
type OptionsByCategory = {
  /** 一级分类的 ID */
  [key in OptionCategoryLevel1]: {
    /** 二级分类的 ID，值是该分类里的所有设置项的编号列表 */
    [key: string]: {
      ids: number[]
    }
  }
}

/** 保存所有设置项以及分类的元数据 */
class OptionConfigs {
  constructor() {
    this.bindEvents()
  }

  /** 所有一级分类和二级分类的 schema 信息 */
  public categorySchema: CategorySchema = {
    crawl: {
      id: 'crawl',
      order: 0,
      nameKey: '_抓取',
      level2: {
        scope: {
          id: 'scope',
          order: 0,
          icon: 'category-scope-line',
          nameKey: '_分组_抓取范围',
        },
        workType: {
          id: 'workType',
          order: 1,
          icon: 'category-work-type-line',
          nameKey: '_分组_作品类型',
        },
        workData: {
          id: 'workData',
          order: 2,
          icon: 'category-work-data-line',
          nameKey: '_分组_作品数据',
        },
        tagAndTitle: {
          id: 'tagAndTitle',
          order: 3,
          icon: 'category-tag-title-line',
          nameKey: '_分组_标签与标题',
        },
        multiImage: {
          id: 'multiImage',
          order: 4,
          icon: 'category-multi-image-line',
          nameKey: '_分组_多图作品',
        },
        strategy: {
          id: 'strategy',
          order: 5,
          icon: 'category-strategy-line',
          nameKey: '_分组_执行策略',
        },
      },
    },
    naming: {
      id: 'naming',
      order: 1,
      nameKey: '_命名',
      level2: {
        names: {
          id: 'names',
          order: 0,
          icon: 'category-names-line',
          nameKey: '_分组_文件夹和文件的名字',
        },
        adjustFolders: {
          id: 'adjustFolders',
          order: 1,
          icon: 'category-adjust-folders-line',
          nameKey: '_分组_调整文件夹',
        },
        alias: {
          id: 'alias',
          order: 2,
          icon: 'category-alias-line',
          nameKey: '_分组_别名',
        },
        serial: {
          id: 'serial',
          order: 3,
          icon: 'category-serial-line',
          nameKey: '_分组_序号',
        },
        removeSpecialChars: {
          id: 'removeSpecialChars',
          order: 4,
          icon: 'category-remove-special-chars-line',
          nameKey: '_分组_移除特殊字符',
        },
      },
    },
    download: {
      id: 'download',
      order: 2,
      nameKey: '_下载',
      level2: {
        behavior: {
          id: 'behavior',
          order: 0,
          icon: 'download',
          nameKey: '_分组_下载行为',
        },
        record: {
          id: 'record',
          order: 1,
          icon: 'category-download-record-line',
          nameKey: '_分组_下载记录',
        },
        imageSize: {
          id: 'imageSize',
          order: 2,
          icon: 'category-image-size-line',
          nameKey: '_分组_图片尺寸',
        },
        ugoira: {
          id: 'ugoira',
          order: 3,
          icon: 'category-ugoira-line',
          nameKey: '_分组_动图',
        },
        novel: {
          id: 'novel',
          order: 4,
          icon: 'book',
          nameKey: '_分组_小说',
        },
        metadata: {
          id: 'metadata',
          order: 5,
          icon: 'category-metadata-line',
          nameKey: '_分组_元数据',
        },
      },
    },
    enhance: {
      id: 'enhance',
      order: 3,
      nameKey: '_增强',
      level2: {
        preview: {
          id: 'preview',
          order: 0,
          icon: 'category-preview-line',
          nameKey: '_分组_预览',
        },
        thumbnail: {
          id: 'thumbnail',
          order: 1,
          icon: 'category-thumbnail-line',
          nameKey: '_分组_缩略图',
        },
        thumbnailButtons: {
          id: 'thumbnailButtons',
          order: 2,
          icon: 'category-thumbnail-buttons-line',
          nameKey: '_分组_缩略图上的按钮',
        },
        other: {
          id: 'other',
          order: 3,
          icon: 'category-other-line',
          nameKey: '_分组_其他',
        },
        searchPage: {
          id: 'searchPage',
          order: 4,
          icon: 'category-search-page-line',
          nameKey: '_分组_搜索页面',
        },
      },
    },
    general: {
      id: 'general',
      order: 4,
      nameKey: '_通用',
      level2: {
        language: {
          id: 'language',
          order: 0,
          icon: 'category-language-line',
          nameKey: '_分组_语言',
        },
        operation: {
          id: 'operation',
          order: 1,
          icon: 'category-operation-line',
          nameKey: '_分组_操作方式',
        },
        appearance: {
          id: 'appearance',
          order: 2,
          icon: 'category-appearance-line',
          nameKey: '_分组_外观',
        },
        log: {
          id: 'log',
          order: 3,
          icon: 'category-log-line',
          nameKey: '_分组_日志',
        },
        manageSettings: {
          id: 'manageSettings',
          order: 4,
          icon: 'category-manage-settings-line',
          nameKey: '_分组_管理设置',
        },
      },
    },
  }

  /** 所有设置的元数据 */
  public options: OptionMeta[] = [
    // 抓取
    {
      no: 0,
      nameKey: '_抓取多少作品',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'scope',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 1,
      nameKey: '_抓取多少页面',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'scope',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 2,
      nameKey: '_抓取每个用户最新的几个作品',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'scope',
      pinned: false,
      isCustom: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 3,
      nameKey: '_作品类型',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workType',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 4,
      nameKey: '_年龄限制',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workType',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 5,
      nameKey: '_AI作品',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workType',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 6,
      nameKey: '_原创作品',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workType',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1774310400000,
    },
    {
      no: 7,
      nameKey: '_图片色彩',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workType',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 8,
      nameKey: '_图片数量',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workType',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 9,
      nameKey: '_收藏状态',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workData',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_书签'],
      searchWords: [],
    },
    {
      no: 10,
      nameKey: '_收藏数量',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workData',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 11,
      nameKey: '_图片的宽高',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workData',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_分辨率'],
      searchWords: [],
    },
    {
      no: 12,
      nameKey: '_图片的宽高比例',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workData',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_纵横比'],
      searchWords: [],
    },
    {
      no: 13,
      nameKey: '_id范围',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workData',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 14,
      nameKey: '_投稿时间',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'workData',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_发布时间'],
      searchWords: [],
    },
    {
      no: 15,
      nameKey: '_必须含有tag',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'tagAndTitle',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_标签'],
      searchWords: [],
    },
    {
      no: 16,
      nameKey: '_不能含有tag',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'tagAndTitle',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_标签'],
      searchWords: [],
    },
    {
      no: 17,
      nameKey: '_针对特定用户屏蔽标签',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'tagAndTitle',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 18,
      nameKey: '_标题必须含有',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'tagAndTitle',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1774137600000,
    },
    {
      no: 19,
      nameKey: '_标题不能含有',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'tagAndTitle',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1774137600000,
    },
    {
      no: 20,
      nameKey: '_多图作品的图片数量上限',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'multiImage',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 21,
      nameKey: '_多图作品只抓取前几张图片',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'multiImage',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 22,
      nameKey: '_多图作品只抓取后几张图片',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'multiImage',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1776147641055,
    },
    {
      no: 23,
      nameKey: '_多图作品不抓取前几张图片',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'multiImage',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1776147641055,
    },
    {
      no: 24,
      nameKey: '_多图作品不抓取后几张图片',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'multiImage',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1776147641055,
    },
    {
      no: 25,
      nameKey: '_特定用户的多图作品不下载最后几张图片',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'multiImage',
      pinned: false,
      hideOnPixivision: true,
      isCustom: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 26,
      nameKey: '_不抓取下载过的作品',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'strategy',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_已下载'],
      searchWords: [],
      addedAt: 1775755273036,
    },
    {
      no: 27,
      nameKey: '_用户阻止名单',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'strategy',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_黑名单'],
      searchWords: [],
    },
    {
      no: 28,
      nameKey: '_减慢抓取速度',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'strategy',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 29,
      nameKey: '_定时抓取的间隔时间',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'strategy',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 30,
      nameKey: '_自动导出抓取结果',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'strategy',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 31,
      nameKey: '_导出ID列表',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: 'strategy',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },

    // 命名
    {
      no: 32,
      nameKey: '_图像作品的命名规则',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'names',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_文件名'],
      searchWords: [],
    },
    {
      no: 33,
      nameKey: '_小说的命名规则',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'names',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_文件名'],
      searchWords: [],
      addedAt: 1777025547205,
    },
    {
      no: 34,
      nameKey: '_在不同的页面类型中使用不同的命名规则',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'names',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 35,
      nameKey: '_如果作品含有某些标签则对这个作品使用另一种命名规则',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'names',
      pinned: false,
      hideOnPixivision: true,
      isCustom: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 36,
      nameKey: '_合并系列小说时的命名规则',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'names',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_文件名'],
      searchWords: [],
    },
    {
      no: 37,
      nameKey: '_标签分隔符号',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'names',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 38,
      nameKey: '_日期格式',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'names',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 39,
      nameKey: '_文件名长度限制',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'names',
      pinned: false,
      searchWordKeys: ['_路径长度'],
      searchWords: [],
    },
    {
      no: 40,
      nameKey: '_不创建文件夹',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'adjustFolders',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_文件夹'],
      searchWords: [],
      addedAt: 1776337453630,
    },
    {
      no: 41,
      nameKey: '_为多图作品添加一层文件夹',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'adjustFolders',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_文件夹'],
      searchWords: [],
      addedAt: 1776337453630,
    },
    {
      no: 42,
      nameKey: '_为r18作品添加一层文件夹',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'adjustFolders',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_文件夹'],
      searchWords: [],
    },
    {
      no: 43,
      nameKey: '_使用第一个匹配的标签建立文件夹',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'adjustFolders',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_文件夹'],
      searchWords: [],
    },
    {
      no: 44,
      nameKey: '_标签别名',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'alias',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1777025547205,
    },
    {
      no: 45,
      nameKey: '_自定义用户名',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'alias',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 46,
      nameKey: '_序号起始值',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'serial',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1775633245633,
    },
    {
      no: 47,
      nameKey: '_第一张图不带序号',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'serial',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 48,
      nameKey: '_在序号前面填充0',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'serial',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 49,
      nameKey: '_移除文件名里的emoji',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'removeSpecialChars',
      pinned: false,
      searchWordKeys: ['_表情符号'],
      searchWords: [],
      addedAt: 1775579018462,
    },
    {
      no: 50,
      nameKey: '_移除用户名中的at和后续字符',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: 'removeSpecialChars',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },

    // 下载
    {
      no: 51,
      nameKey: '_同时下载数量',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_并发'],
      searchWords: [],
    },
    {
      no: 52,
      nameKey: '_自动开始下载',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 53,
      nameKey: '_下载之后收藏作品',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_书签'],
      searchWords: [],
    },
    {
      no: 54,
      nameKey: '_点击收藏按钮时下载作品',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_书签'],
      searchWords: [],
    },
    {
      no: 55,
      nameKey: '_点击点赞按钮时下载作品',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 56,
      nameKey: '_下载间隔',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 57,
      nameKey: '_文件下载顺序',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_排序'],
      searchWords: [],
    },
    {
      no: 58,
      nameKey: '_优先下载动图',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1780444800000,
    },
    {
      no: 59,
      nameKey: '_文件体积限制',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      searchWordKeys: ['_上限'],
      searchWords: [],
    },
    {
      no: 60,
      nameKey: '_把文件保存到用户上次选择的位置',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      searchWordKeys: ['_路径'],
      searchWords: [],
    },
    {
      no: 61,
      nameKey: '_下载完成后显示通知',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'behavior',
      pinned: false,
      searchWordKeys: ['_提醒'],
      searchWords: [],
    },
    {
      no: 62,
      nameKey: '_管理下载记录',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'record',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1776098259792,
    },
    {
      no: 63,
      nameKey: '_不下载重复文件',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'record',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_去重'],
      searchWords: [],
    },
    {
      no: 64,
      nameKey: '_下载图片时的尺寸',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'imageSize',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_分辨率'],
      searchWords: [],
    },
    {
      no: 65,
      nameKey: '_动图保存格式',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'ugoira',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 66,
      nameKey: '_同时转换多少个动图',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'ugoira',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_并发', '_动图_动态图像'],
      searchWords: [],
    },
    {
      no: 67,
      nameKey: '_小说保存格式',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'novel',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 68,
      nameKey: '_在小说里保存元数据',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'novel',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 69,
      nameKey: '_下载小说的封面图片',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'novel',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 70,
      nameKey: '_下载小说里的内嵌图片',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'novel',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_插图'],
      searchWords: [],
    },
    {
      no: 71,
      nameKey: '_自动合并系列小说',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'novel',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_连载'],
      searchWords: [],
    },
    {
      no: 104,
      nameKey:
        '_在合并系列小说时只要有一篇小说符合过滤条件就保存该系列里的所有小说',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'novel',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 72,
      nameKey: '_合并系列小说时的分割阈值',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'novel',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_连载'],
      searchWords: [],
      addedAt: 1776693866003,
    },
    {
      no: 73,
      nameKey: '_保存作品的元数据',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'metadata',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_元信息'],
      searchWords: [],
    },
    {
      no: 74,
      nameKey: '_保存作品的简介',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: 'metadata',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_介绍'],
      searchWords: [],
    },

    // 增强
    {
      no: 75,
      nameKey: '_预览作品',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'preview',
      pinned: false,
      hideOnPixivision: true,
      hideOnMobile: true,
      searchWordKeys: ['_预览图片'],
      searchWords: [],
    },
    {
      no: 76,
      nameKey: '_长按右键显示大图',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'preview',
      pinned: false,
      hideOnPixivision: true,
      hideOnMobile: true,
      searchWordKeys: ['_原图'],
      searchWords: [],
    },
    {
      no: 77,
      nameKey: '_预览作品的详细信息',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'preview',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 78,
      nameKey: '_显示更大的缩略图',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'thumbnail',
      pinned: false,
      hideOnPixivision: true,
      hideOnMobile: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 79,
      nameKey: '_替换方形缩略图以显示图片比例',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'thumbnail',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 80,
      nameKey: '_在多图作品页面里显示缩略图列表',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'thumbnail',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 81,
      nameKey: '_把图片显示为灰色',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'thumbnail',
      pinned: false,
      isCustom: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 82,
      nameKey: '_缩略图上按钮的位置',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'thumbnailButtons',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1776098259792,
    },
    {
      no: 83,
      nameKey: '_在作品缩略图上显示放大按钮',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'thumbnailButtons',
      pinned: false,
      hideOnPixivision: true,
      hideOnMobile: true,
      searchWordKeys: ['_放大镜', '_图片查看器'],
      searchWords: [],
    },
    {
      no: 84,
      nameKey: '_在缩略图上显示复制按钮',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'thumbnailButtons',
      pinned: false,
      hideOnPixivision: true,
      hideOnMobile: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 85,
      nameKey: '_在作品缩略图上显示下载按钮',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'thumbnailButtons',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 86,
      nameKey: '_高亮关注的用户',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'other',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 87,
      nameKey: '_在下载过的作品上显示边框',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'other',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_已下载'],
      searchWords: [],
      addedAt: 1775914625357,
    },
    {
      no: 88,
      nameKey: '_收藏设置',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'other',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_书签'],
      searchWords: [],
    },
    {
      no: 89,
      nameKey: '_复制按钮',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'other',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 90,
      nameKey: '_在搜索页面添加快捷搜索区域',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'searchPage',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_快速搜索'],
      searchWords: [],
    },
    {
      no: 91,
      nameKey: '_过滤搜索页面的作品',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'searchPage',
      pinned: false,
      hideOnPixivision: true,
      isCustom: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 92,
      nameKey: '_在搜索页面里移除已关注用户的作品',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'searchPage',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 93,
      nameKey: '_预览搜索结果',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: 'searchPage',
      pinned: false,
      hideOnPixivision: true,
      hideOnMobile: true,
      searchWordKeys: [],
      searchWords: [],
    },

    // 通用
    {
      no: 94,
      nameKey: '_Language',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: 'language',
      pinned: false,
      searchWordKeys: [
        '_语言',
        '_中文_简体和繁体_搜索用',
        '_简体中文_搜索用',
        '_正體中文_搜索用',
        '_英语_搜索用',
        '_日语_搜索用',
        '_韩语_搜索用',
        '_俄语_搜索用',
      ],
      searchWords: [],
    },
    {
      no: 95,
      nameKey: '_选项卡切换方式',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: 'operation',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 96,
      nameKey: '_点击设置卡片时切换它的开关状态',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: 'operation',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1779990279488,
    },
    {
      no: 97,
      nameKey: '_点击设置名字时打开wiki链接',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: 'operation',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1780444800000,
    },
    {
      no: 98,
      nameKey: '_颜色主题',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: 'appearance',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_深色模式'],
      searchWords: [],
    },
    {
      no: 99,
      nameKey: '_背景图片',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: 'appearance',
      pinned: false,
      searchWordKeys: ['_壁纸', '_皮肤'],
      searchWords: [],
    },
    {
      no: 100,
      nameKey: '_高亮显示关键字',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: 'appearance',
      pinned: false,
      searchWordKeys: ['_关键词'],
      searchWords: [],
    },
    {
      no: 101,
      nameKey: '_日志区域的默认可见性',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: 'log',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
      addedAt: 1772287652821,
    },
    {
      no: 102,
      nameKey: '_导出日志',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: 'log',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_保存日志'],
      searchWords: [],
    },
    {
      no: 103,
      nameKey: '_管理设置',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: 'manageSettings',
      pinned: false,
      hideOnPixivision: true,
      searchWordKeys: ['_导入设置', '_导出设置', '_重置设置'],
      searchWords: [],
    },
  ]

  /** 按分类组织的设置项 */
  public optionsByCategory: OptionsByCategory = this.getOptionsByCategory()

  public getOptionsByCategory() {
    const optionsByCategory: OptionsByCategory = {
      crawl: {},
      naming: {},
      download: {},
      enhance: {},
      general: {},
    }
    for (const option of this.options) {
      // 添加二级分类数组
      if (!optionsByCategory[option.categoryLevel1][option.categoryLevel2]) {
        optionsByCategory[option.categoryLevel1][option.categoryLevel2] = {
          ids: [],
        }
      }
      // 添加二级分类里的设置项编号
      optionsByCategory[option.categoryLevel1][option.categoryLevel2].ids.push(
        option.no
      )
    }
    return optionsByCategory
  }

  private bindEvents() {
    // 当置顶的设置发生变化时，更新每个设置项的 pinned 属性
    window.addEventListener(EVT.list.settingChange, (ev: CustomEventInit) => {
      const data = ev.detail.data as any
      if (data.name === 'pinnedOptionsV2') {
        this.setPinnedOptions()
      }
    })

    // 当设置初始化完成后、界面语言变化后，设置每个配置项里的 i18n 文本
    const setOptionTextEvents = [
      EVT.list.settingInitialized,
      EVT.list.langChange,
    ]
    for (const event of setOptionTextEvents) {
      window.addEventListener(event, () => {
        this.setOptionText()
      })
    }
  }

  private setPinnedOptions() {
    for (const option of this.options) {
      option.pinned = settings.pinnedOptionsV2.includes(option.no)
    }
  }

  private setOptionText() {
    for (const option of this.options) {
      // 设置名称里含有 span 标签，需要去掉，只保留纯文字
      option.name = lang.transl(option.nameKey).replace(/<\/?.+?>/g, '')
      // 设置搜索词数组
      if (option.searchWordKeys.length > 0) {
        option.searchWords = []
        option.searchWords = option.searchWordKeys.map((key) =>
          lang.transl(key).replace(/<\/?.+?>/g, '')
        )
      }
    }
  }
}

const optionConfigs = new OptionConfigs()
export { optionConfigs }
