export interface SettingsForm extends HTMLFormElement {
  setWantPage: HTMLInputElement
  firstFewImages: HTMLInputElement
  downType0: HTMLInputElement
  downType1: HTMLInputElement
  downType2: HTMLInputElement
  downType3: HTMLInputElement
  downSingleImg: HTMLInputElement
  downMultiImg: HTMLInputElement
  firstFewImagesSwitch: HTMLInputElement
  multiImageWorkImageLimitSwitch: HTMLInputElement
  multiImageWorkImageLimit: HTMLInputElement
  downColorImg: HTMLInputElement
  downBlackWhiteImg: HTMLInputElement
  ugoiraSaveAs: RadioNodeList
  BMKNumMin: HTMLInputElement
  BMKNumMax: HTMLInputElement
  BMKNumAverageSwitch: HTMLInputElement
  BMKNumAverage: HTMLInputElement
  downNotBookmarked: HTMLInputElement
  downBookmarked: HTMLInputElement
  setWHSwitch: HTMLInputElement
  setWidth: HTMLInputElement
  idRange: RadioNodeList
  idRangeInput: HTMLInputElement
  setWidthAndOr: RadioNodeList
  setHeight: HTMLInputElement
  ratio: RadioNodeList
  userRatio: HTMLInputElement
  postDate: HTMLInputElement
  postDateStart: HTMLInputElement
  postDateEnd: HTMLInputElement
  needTag: HTMLInputElement
  notNeedTag: HTMLInputElement
  quietDownload: HTMLInputElement
  downloadThread: HTMLInputElement
  userSetName: HTMLInputElement
  fileNameSelect: HTMLSelectElement
  tagNameToFileName: HTMLInputElement
  noSerialNo: HTMLInputElement
  workDir: HTMLInputElement
  workDirFileNumber: HTMLInputElement
  workDirNameRule: HTMLInputElement
  previewResult: HTMLInputElement
  previewResultLimit: HTMLInputElement
  BMKNumSwitch: HTMLInputElement
  ratioSwitch: HTMLInputElement
  idRangeSwitch: HTMLInputElement
  needTagSwitch: HTMLInputElement
  notNeedTagSwitch: HTMLInputElement
  convertUgoiraThread: HTMLInputElement
  sizeSwitch: HTMLInputElement
  sizeMin: HTMLInputElement
  sizeMax: HTMLInputElement
  novelSaveAs: RadioNodeList
  saveNovelMeta: HTMLInputElement
  deduplication: HTMLInputElement
  dupliStrategy: RadioNodeList
  fileNameLengthLimitSwitch: HTMLInputElement
  fileNameLengthLimit: HTMLInputElement
  imageSize: RadioNodeList
  dateFormat: HTMLInputElement
  userSetLang: RadioNodeList
  bmkAfterDL: HTMLInputElement
  widthTag: RadioNodeList
  restrict: RadioNodeList
  userBlockList: HTMLInputElement
  blockList: HTMLInputElement
  needTagMode: RadioNodeList
  theme: RadioNodeList
  r18Folder: HTMLInputElement
  r18FolderName: HTMLInputElement
  blockTagsForSpecificUser: HTMLInputElement
  magnifier: HTMLInputElement
  magnifierSize: RadioNodeList
  magnifierPosition: RadioNodeList
  bgDisplay: HTMLInputElement
  bgOpacity: HTMLInputElement
  bgPositionY: HTMLInputElement
  createFolderByType: HTMLInputElement
  createFolderByTypeIllust: HTMLInputElement
  createFolderByTypeManga: HTMLInputElement
  createFolderByTypeUgoira: HTMLInputElement
  createFolderByTypeNovel: HTMLInputElement
  createFolderByTag: HTMLInputElement
  createFolderTagList: HTMLTextAreaElement
  downAllAges: HTMLInputElement
  downR18: HTMLInputElement
  downR18G: HTMLInputElement
  switchTabBar: RadioNodeList
  zeroPadding: HTMLInputElement
  zeroPaddingLength: HTMLInputElement
  tagMatchMode: RadioNodeList
  showFastSearchArea: HTMLInputElement
  saveMetaType0: HTMLInputElement
  saveMetaType1: HTMLInputElement
  saveMetaType2: HTMLInputElement
  saveMetaType3: HTMLInputElement
  setNameRuleForEachPageType: HTMLInputElement
  showAdvancedSettings: HTMLInputElement
  showNotificationAfterDownloadComplete: HTMLInputElement
  boldKeywords: HTMLInputElement
  autoExportResult: HTMLInputElement
  autoExportResultCSV: HTMLInputElement
  autoExportResultJSON: HTMLInputElement
  autoExportResultNumber: HTMLInputElement
  PreviewWork: HTMLInputElement
  showDownloadBtnOnThumb: HTMLInputElement
  prevWorkSize: HTMLInputElement
  previewWorkWait: HTMLInputElement
  showPreviewWorkTip: HTMLInputElement
  showOriginImage: HTMLInputElement
  showOriginImageSize: HTMLInputElement
  replaceSquareThumb: HTMLInputElement
  notFolderWhenOneFile: HTMLInputElement
  noSerialNoForSingleImg: HTMLInputElement
  noSerialNoForMultiImg: HTMLInputElement
  removeAtFromUsername: HTMLInputElement
  showLargerThumbnails: HTMLInputElement
  doubleWidthThumb: HTMLInputElement
  wheelScrollSwitchImageOnPreviewWork: HTMLInputElement
  doNotDownloadLastImageOfMultiImageWork: HTMLInputElement
  downloadNovelCoverImage: HTMLInputElement
  downloadNovelEmbeddedImage: HTMLInputElement
  previewUgoira: HTMLInputElement
  hiddenBrowserDownloadBar: HTMLInputElement
  userRatioLimit: HTMLInputElement
}
