export interface EventList {
  crawlStart: 'crawlStart'
  crawlFinish: 'crawlFinish'
  crawlEmpty: 'crawlEmpty'
  crawlError: 'crawlError'
  convertChange: 'convertChange'
  previewFileName: 'previewFileName'
  output: 'output'
  downloadStart: 'downloadStart'
  downloadPause: 'downloadPause'
  downloadStop: 'downloadStop'
  download: 'download'
  downloadSucccess: 'downloadSucccess'
  downloadComplete: 'downloadComplete'
  downloadError: 'downloadError'
  pageSwitch: 'pageSwitch'
  pageTypeChange: 'pageTypeChange'
  resetOption: 'resetOption'
}
