export interface SettingsForm extends HTMLFormElement {
  setWantPage: HTMLInputElement
  firstFewImages: HTMLInputElement
  downType0: HTMLInputElement
  downType1: HTMLInputElement
  downType2: HTMLInputElement
  downSingleImg: HTMLInputElement
  downMultiImg: HTMLInputElement
  firstFewImagesSwitch: HTMLInputElement
  downColorImg: HTMLInputElement
  downBlackWhiteImg: HTMLInputElement
  ugoiraSaveAs: RadioNodeList
  BMKNumMin: HTMLInputElement
  BMKNumMax: HTMLInputElement
  setOnlyBmk: HTMLInputElement
  quickBookmarks: HTMLInputElement
  setWHSwitch: HTMLInputElement
  setWidth: HTMLInputElement
  idRange: RadioNodeList
  idRangeInput: HTMLInputElement
  setWidthAndOr: RadioNodeList
  setHeight: HTMLInputElement
  ratio: RadioNodeList
  userRatio: HTMLInputElement
  postDate: HTMLInputElement
  postDateStart: HTMLInputElement
  postDateEnd: HTMLInputElement
  needTag: HTMLInputElement
  notNeedTag: HTMLInputElement
  quietDownload: HTMLInputElement
  downloadThread: HTMLInputElement
  userSetName: HTMLInputElement
  fileNameSelect: HTMLSelectElement
  tagNameToFileName: HTMLInputElement
  noSerialNo: HTMLInputElement
  alwaysFolder: HTMLInputElement
  multipleImageDir: HTMLInputElement
  multipleImageFolderName: RadioNodeList
  debut: HTMLInputElement
  previewResult: HTMLInputElement
  BMKNumSwitch: HTMLInputElement
  ratioSwitch: HTMLInputElement
  idRangeSwitch: HTMLInputElement
  needTagSwitch: HTMLInputElement
  notNeedTagSwitch: HTMLInputElement
  convertUgoiraThread: HTMLInputElement
}
