/*
 * project: Powerful Pixiv Downloader
 * author:  xuejianxianzun; 雪见仙尊
 * license: GPL-3.0-or-later; http://www.gnu.org/licenses/gpl-3.0.txt
 * Github： https://github.com/xuejianxianzun/PixivBatchDownloader
 * Releases: https://github.com/xuejianxianzun/PixivBatchDownloader/releases
 * Wiki:    https://xuejianxianzun.github.io/PBDWiki
 * Website: https://pixiv.download/
 */

import './Language'
import './IconHelper'
import './Theme'
import './store/States'
import './setting/Settings'
import './setting/AutoExportSettings'
import './setting/InvisibleSettings'
import './ListenPageSwitch'
import './setting/SettingsPanelBootstrap'
import './setting/DoNotDownloadLastFewImages'
import './setting/UseDifferentNameRuleIfWorkHasTag'
import './ReplaceSquareThumb'
import './InitPage'
import './crawlMixedPage/QuickCrawl'
import './crawlArtworkPage/CrawlCurrent'
import './download/DownloadControl'
import './download/Resume'
import './Tip'
import './PreviewWork'
import './ShowOriginSizeImage'
import './PreviewWorkDetailInfo'
import './ShowLargerThumbnails'
import './buttonsOnThumb/ButtonsOnArtworkThumbOnPC'
import './buttonsOnThumb/ButtonsOnNovelThumbOnPC'
import './buttonsOnThumb/DownloadBtnOnThumbOnMobile'
import './RemoveBlockedUsersWork'
import './output/OutputPanel'
import './output/PreviewFileName'
import './output/ShowURLs'
import './download/ExportResult2CSV'
import './download/ExportResult'
import './download/ImportResult'
import './download/ExportLST'
import './download/SaveWorkMeta'
import './download/SaveWorkDescription'
import './download/showStatusOnTitle'
import './download/ShowTotalResultOnTitle'
import './download/ShowRemainingDownloadOnTitle'
import './download/DownloadOnClickLike'
import './HighlightFollowingUsers'
import './ImageToGray'
import './UpdateUserName'
import './ShowBorderOnDownloadedWorks'
// 在红叶分支里不需要启用 QuicklyBlockUsers，因为该分支里使用 CheckUser 实现了这个功能
// import './setting/QuicklyBlockUsers'
import './ImageToGray'
import './ShowWhatIsNew'
import './ShowNotification'
import './CheckTag'
import './CheckUser'
import './HotkeyListener'
import './setting/HotkeyEditor'
