import { Config } from './config/Config'

// 储存下载器使用的多语言文本
// 在属性名前面加上下划线，和文本内容做出区别
// {} 是占位符
// <br> 是换行

const langText = {
  _只下载已收藏: [
    '只下载已收藏',
    '只下載已收藏',
    'Download only bookmarked works',
    'ブックマークのみをダウンロードする',
    '북마크된 작품만 다운로드',
  ],
  _下载作品类型: [
    '下载作品类型',
    '下載作品類型',
    'Download work type',
    'ダウンロード作品の種類',
    '다운로드할 작품 유형',
  ],
  _作品类型: [
    '作品<span class="key">类型</span>',
    '作品<span class="key">類型</span>',
    '<span class="key">Type</span> of work',
    '作品の<span class="key">種類</span>',
    '작품 <span class="key">유형</span>',
  ],
  _不能含有tag: [
    '<span class="key">不能</span>含有标签',
    '<span class="key">不能</span>含有標籤',
    '<span class="key">Exclude</span> tag',
    'タグを除外する',
    '<span class="key">제외</span> 태그',
  ],
  _排除tag的提示文字: [
    '您可在下载前设置要排除的标签，这样在下载时将不会下载含有这些标签的作品。不区分大小写；如需排除多个标签，请使用英文逗号分隔。请注意要排除的标签的优先级大于要包含的tag的优先级。',
    '可在下載前設定要排除的標籤，下載時將排除含有這些標籤的作品，不區分大小寫；如需排除多個標籤，請使用半形逗號（,）分隔。請注意，要排除的標籤優先於要包含的標籤。',
    'Before downloading, you can set the tag you want to exclude. Not case sensitive; If you need to set multiple tags, you can use comma (,) separated. The excluded tag takes precedence over the included tag',
    'ダウンロード前に、除外するタグを設定できます。大文字と小文字を区別しない；複数のタグを設定する必要がある場合は、「,」で区切ってください。除外されたタグは、必要なタグよりも優先されます',
    '다운로드하기 전에 제외해야 하는 태그를 설정할 수 있습니다. 대소문자를 구분하지 않습니다. 여러 태그를 설정해야 하는 경우 쉼표(,)로 구분합니다. 제외된 태그가 포함된 태그보다 우선합니다.',
  ],
  _设置了排除tag之后的提示: [
    '排除标签：',
    '排除標籤：',
    'Excludes tag: ',
    '以下のタグを除外：',
    '제외 태그: ',
  ],
  _必须含有tag: [
    '<span class="key">必须</span>含有标签',
    '<span class="key">必須</span>含有標籤',
    '<span class="key">Include</span> tag',
    '<span class="key">必要な</span>タグ',
    '<span class="key">포함</span> 태그',
  ],
  _必须tag的提示文字: [
    '您可在下载前设置作品里必须包含的标签，不区分大小写；如需包含多个标签，请使用英文逗号分隔。',
    '可在下載前設定作品裡必須包含的標籤，不區分大小寫；如需包含多個標籤，請使用半形逗號（,）分隔。',
    'Before downloading, you can set the tag that must be included. Not case sensitive; If you need to set multiple tags, you can use comma (,) separated.',
    'ダウンロードする前に、必要なタグを設定することができます。大文字と小文字を区別しない；複数のタグを設定する必要がある場合は、「,」で区切ってください。',
    '다운로드하기 전에 포함해야 하는 태그를 설정할 수 있습니다. 대소문자를 구분하지 않습니다. 여러 태그를 설정해야 하는 경우 쉼표(,)로 구분합니다.',
  ],
  _设置了必须tag之后的提示: [
    '包含标签：',
    '包含標籤：',
    'Include tag: ',
    '以下の タグ を含める：',
    '포함 태그: ',
  ],
  _图片的宽高比例: [
    '图片的宽高<span class="key">比例</span>',
    '圖片的寬高<span class="key">比例</span>',
    'Aspect <span class="key">ratio</span>',
    '画像の縦横比',
    '<span class="key">종횡비</span>',
  ],
  _设置宽高比例Title: [
    '设置宽高比例，也可以手动输入宽高比',
    '設定寬高比，也可以手動輸入寬高比。',
    'Set the aspect ratio, or manually type the aspect ratio',
    '縦横比を設定する、手動で縦横比を入力することもできる',
    '종횡비를 설정하거나, 값을 수동으로 입력할 수 있습니다.',
  ],
  _不限制: ['不限制', '不限制', 'not limited', '無制限', '제한 없음'],
  _横图: ['横图', '橫圖', 'Horizontal', '横長', '가로'],
  _竖图: ['竖图', '豎圖', 'Vertical', '縦長', '세로'],
  _正方形: ['正方形', '正方形', 'Square', '正方形', '정사각형'],
  _宽高比: ['宽高比', '寬高比', 'Ratio', '縦横比', '종횡비 '],
  _设置了宽高比之后的提示: [
    '宽高比：{}',
    '寬高比：{}',
    'Aspect ratio: {}',
    '縦横比：{}',
    '종횡비: {}',
  ],
  _宽高比必须是数字: [
    '宽高比必须是数字',
    '寬高比必須是數字',
    'The aspect ratio must be a number',
    '縦横比は数値でなければなりません',
    '종횡비는 숫자여야 합니다',
  ],
  _图片的宽高: [
    '图片的<span class="key">宽高</span>',
    '圖片的<span class="key">寬高</span>',
    '<span class="key">width</span> and height',
    '画像の幅と高さ',
    '<span class="key">너비</span> 그리고 높이',
  ],
  _筛选宽高的提示文字: [
    '请输入最小宽度和最小高度，不会下载不符合要求的图片。',
    '請輸入最小寬度和最小高度，只會下載符合要求的圖片。',
    'Please type the minimum width and minimum height. Will not download images that do not meet the requirements',
    '最小幅と最小高さを入力してください。要件を満たしていない画像はダウンロードされません。',
    '최소 너비와 최소 높이를 입력해주세요, 요구 사항을 충족하지 않는 이미지는 다운로드하지 않습니다.',
  ],
  _本次输入的数值无效: [
    '本次输入的数值无效',
    '本次輸入的數值無效',
    'Invalid input',
    '無効な入力',
    '잘못된 입력',
  ],
  _宽度: ['宽度', '寬度', 'Width', '幅', '너비'],
  _或者: [' 或者 ', ' 或是 ', ' or ', ' または ', '또는'],
  _并且: [' 并且 ', ' 並且 ', ' and ', ' そして ', '그리고'],
  _高度: ['高度', '高度', 'height', '高さ', '높이'],
  _抓取多少作品: [
    '抓取<span class="key">多少</span>作品',
    '擷取<span class="key">多少</span>作品',
    'How <span class="key">many</span> works to crawl',
    'クロールする作品の数',
    '긁어올 작품 <span class="key">수</span>',
  ],
  _抓取多少页面: [
    '抓取<span class="key">多少</span>页面',
    '擷取<span class="key">多少</span>頁面',
    'How <span class="key">many</span> pages to crawl',
    'クロールするページ数',
    '긁어올 페이지 <span class="key">수</span>',
  ],
  _收藏数量: [
    '<span class="key">收藏</span>数量',
    '<span class="key">收藏</span>數量',
    'Number of <span class="key">bookmarks</span>',
    'ブックマークの数',
    '<span class="key">북마크</span> 수',
  ],
  _设置收藏数量的提示: [
    '如果作品的收藏数小于设置的数字，作品不会被下载。',
    '只會下載設定收藏數範圍內的作品。',
    'If the number of bookmarks of the work is less than the set number, the work will not be downloaded.',
    '作品のブックマークされた数が設定された数字よりも少ない場合、作品はダウンロードされません。',
    '작품의 북마크 수가 설정된 값보다 적을 경우 작품은 다운로드되지 않습니다.',
  ],
  _筛选收藏数的提示文字: [
    '请输入一个数字，如果作品的收藏数小于这个数字，作品不会被下载。',
    '請輸入數字，只會下載設定收藏數範圍內的作品。',
    'Please type a number. If the number of bookmarks of the work is less than this number, the work will not be downloaded.',
    '数字を入力してください。 作品のブックマークされた数がこの数字より少ない場合、作品はダウンロードされません。',
    '숫자를 입력해주세요. 작품의 북마크 수가 이 수보다 적을 경우 작품은 다운로드되지 않습니다.',
  ],
  _收藏数大于: [
    '收藏数 >= ',
    '收藏數 >= ',
    'Number of bookmarks >= ',
    'ブックマークの数 >= ',
    '북마크 수 >= ',
  ],
  _收藏数小于: [
    '收藏数 <= ',
    '收藏數 <= ',
    'Number of bookmarks <= ',
    'ブックマークの数 <= ',
    '북마크 수 <=',
  ],
  _本次任务已全部完成: [
    '本次任务已全部完成。',
    '本次工作已全部完成',
    'This task has been completed.',
    'この作業は完了しました。',
    '이 작업은 완료되었습니다.',
  ],
  _本次任务条件: [
    '本次任务条件: ',
    '本次工作條件：',
    'This task condition: ',
    'この作業の条件：',
    '이 작업 조건: ',
  ],
  _参数不合法: [
    '参数不合法，本次操作已取消。',
    '參數不合法，本次動作已取消。',
    'Parameter is not legal, this operation has been canceled.',
    'パラメータは有効ではありません。この操作はキャンセルされました。',
    '매개변수가 잘못되었습니다, 이 작업은 취소됩니다.',
  ],
  _向下获取所有作品: [
    '向下获取所有作品',
    '向下取得所有作品',
    'download all the work from this page.',
    'このページからすべての作品をダウンロードする。',
    '모든 작품 다운로드',
  ],
  _从本页开始下载提示: [
    '从当前页面开始下载。<br>如果要限制下载的页数，请输入从 1 开始的数字。<br>1 为仅下载本页。',
    '從當前頁面開始下載。<br>如果要限制下載的頁數，請輸入從 1 開始的數字。<br>1 為僅下載本頁。',
    'Download from the current page.<br>If you want to set the number of pages to download, type a number starting at 1. <br>1 is to download only this page.',
    '現在のページからダウンロードしてください。<br>ダウンロードするページを設定する場合は、1から始まる数字を入力してください。<br>1 は現在のページのみをダウンロードする。',
    '현재 페이지에서 다운로드합니다.<br>다운로드할 페이지 수를 설정하려면 1로 시작하는 숫자를 입력해주세요.<br>1은 이 페이지만 다운로드합니다.',
  ],
  _下载所有页面: [
    '下载所有页面',
    '下載所有頁面',
    'download all pages',
    'すべてのページをダウンロードする',
    '모든 페이지 다운로드',
  ],
  _下载x个相关作品: [
    '下载 {} 个相关作品',
    '下載 {} 個相關作品',
    'download {} related works.',
    '関連作品 {} 枚をダウンロードする。',
    '관련 작품 {}개를 다운로드',
  ],
  _下载所有相关作品: [
    '下载所有相关作品',
    '下載所有相關作品',
    'download all related works.',
    '関連作品をすべてダウンロードする。',
    '모든 관련 작품 다운로드',
  ],
  _下载推荐作品: [
    '下载推荐作品',
    '下載推薦作品',
    'download recommend works',
    'お勧め作品をダウンロードする',
    '추천 작품 다운로드',
  ],
  _下载排行榜前x个作品: [
    '下载排行榜前 {} 个作品',
    '下載排行榜前 {} 個作品',
    'download the top {} works in the ranking list',
    'ランク前 {} 位の作品をダウンロードする。',
    '랭킹 목록 상위 {}개의 작품 다운로드',
  ],
  _输入超过了最大值: [
    '您输入的数字超过了最大值',
    '輸入的數字超出最大值',
    'The number you set exceeds the maximum',
    '入力した番号が最大値を超えています',
    '설정하신 수가 최대값을 초과합니다',
  ],
  _从本页开始下载x页: [
    '从本页开始下载 {} 页',
    '從本頁開始下載 {} 頁',
    'download {} pages from this page',
    'このページから {} ページをダウンロードする',
    '이 페이지부터 {} 페이지 다운로드',
  ],
  _从本页开始下载x个: [
    '从本页开始下载 {} 个作品',
    '從本頁開始下載 {} 個作品',
    'Download {} works from this page.',
    'このページから {} 枚の作品をダウンロード。',
    '이 페이지부터 {}개의 작품 다운로드',
  ],
  _任务开始0: [
    '任务开始',
    '工作開始',
    'Task starts',
    '作業が開始されます',
    '작업 시작',
  ],
  _排除作品类型: [
    '排除作品类型：',
    '排除作品類型：',
    'Excludes these types of works: ',
    'これらのタイプの作品を除外：',
    '제외된 작품 유형: ',
  ],
  _多图作品: [
    '多图作品',
    '多圖作品',
    'Multi-image works',
    '複数画像作品',
    '여러 이미지 작품',
  ],
  _多图下载设置: [
    '多图下载设置',
    '多圖下載設定',
    'Download multi-image works',
    '複数画像設定',
    '여러 이미지 작품 다운로드',
  ],
  _不下载: ['不下载', '不下載', 'No', '必要なし', '아니요'],
  _全部下载: ['全部下载', '全部下載', 'Yes', '全部ダウンロード', '네'],
  _插画: ['插画', '插畫', 'Illustrations', 'イラスト', '일러스트'],
  _漫画: ['漫画', '漫畫', 'Manga', '漫画', '만화'],
  _动图: ['动图', '動圖', 'Ugoira', 'うごイラ', '움직이는 일러스트'],
  _动图保存格式: [
    '<span class="key">动图</span>保存格式',
    '<span class="key">動圖</span>儲存格式',
    'Save the <span class="key">ugoira</span> work as',
    'うごイラの保存タイプ',
    '<span class="key">움직이는 일러스트</span> 작품 저장 형식',
  ],
  _动图保存格式title: [
    '下载动图时，可以把它转换成视频文件',
    '下載動圖時，可轉換為影片檔。',
    'When you download a ugoira work, you can convert it to a video file.',
    'うごイラをダウンロードするとき、動画に変換することができます。',
    '움직이는 일러스트 작품을 다운로드 하면, 동영상 파일로 변환할 수 있습니다.',
  ],
  _webmVideo: [
    'WebM 视频',
    '影片（WebM）',
    'WebM video',
    'WebM ビデオ',
    'WebM 동영상',
  ],
  _gif: ['GIF 图片', '圖片（GIF）', 'GIF image', 'GIF 画像', 'GIF 이미지'],
  _apng: [
    'APNG 图片',
    '圖片（APNG）',
    'APNG image',
    'APNG 画像',
    'APNG 이미지',
  ],
  _zipFile: [
    'Zip 文件',
    '壓縮檔（Zip）',
    'Zip file',
    'ZIP ファイル',
    'Zip 파일',
  ],
  _当前作品个数: [
    '当前有 {} 个作品',
    '目前有 {} 個作品',
    'There are now {} works',
    '今は　{}　枚の作品があります',
    '현재 {}개의 작품이 있습니다',
  ],
  _当前有x个用户: [
    '当前有 {} 个用户',
    '目前有 {} 個使用者',
    'There are currently {} users',
    '現在 {} 人のユーザーがいます',
    '현재 {}명의 유저가 있습니다',
  ],
  _已抓取x个用户: [
    '已抓取 {} 个用户',
    '已擷取 {} 個使用者',
    'crawled {} users',
    'クロールされた {} ユーザー',
    '{}명의 유저를 긁어왔습니다',
  ],
  _排行榜进度: [
    '已抓取本页面第{}部分',
    '已擷取本頁面第 {} 部分',
    'Part {} of this page has been crawled',
    'このページの第　{}　部がクロールされました',
    '이 페이지의 {} 부분을 긁어왔습니다',
  ],
  _新作品进度: [
    '已抓取本页面 {} 个作品',
    '已擷取本頁面 {} 個作品',
    'This page has been crawled {} works',
    'このページの {} つの作品をクロールしました',
    '이 페이지의 {}개의 작품을 긁어왔습니다',
  ],
  _抓取多少个作品: [
    '抓取本页面 {} 个作品',
    '擷取本頁面 {} 個作品',
    'Crawl this page {} works',
    'このページの {} つの作品をクロールします',
    '이 페이지의 {}개의 작품 긁어오기',
  ],
  _相关作品抓取完毕: [
    '相关作品抓取完毕。包含有{}个作品，开始获取作品信息。',
    '相關作品擷取完畢。包含有 {} 個作品，開始取得作品資訊。',
    'The related works have been crawled. Contains {} works and starts getting information about the work.',
    '関連作品はクロールされました。 {} 作品を含み、その作品に関する情報の取得を開始します。',
    '관련 작품 긁어오기 완료, {}개의 작품이 포함되어 있으며, 작품 정보 가져오기를 시작합니다',
  ],
  _排行榜任务完成: [
    '本页面抓取完毕。<br>当前有{}个作品，开始获取作品信息。',
    '本頁面擷取完畢。<br>目前有 {} 個作品，開始取得作品資訊。',
    'This page is crawled and now has {} works.<br> Start getting the works for more information.',
    'このページのクロール終了。<br>{}枚の作品があります。 作品情報の取得を開始します。',
    '이 페이지 긁어오기 완료되었습니다<br>현재 {}개의 작품이 있으며, 작품 정보 가져오기를 시작합니다',
  ],
  _开始获取作品信息: [
    '开始获取作品信息',
    '開始取得作品資訊',
    'Start getting work data',
    '作品情報の取得を開始します',
    '작품 정보 가져오기 시작',
  ],
  _列表页抓取进度: [
    '已抓取列表页 {} 个页面',
    '已擷取清單頁 {} 個頁面',
    'Has acquired {} list pages',
    '{} のリストページを取得しました',
    '{}개의 목록 페이지를 획득하였습니다',
  ],
  _列表页抓取进度2: [
    '正在抓取列表页 {}/{}',
    '正在抓取列表頁 {}/{}',
    'crawling list page {}/{}',
    'リストページの取得 {}/{}',
    '목록 페이지 긁어오는 중 {}/{}',
  ],
  _列表页抓取完成: [
    '列表页面抓取完成',
    '清單頁面擷取完成',
    'The list page is crawled',
    'リストページがクロールされ',
    '목록 페이지 긁어오기 완료',
  ],
  _抓取结果为零: [
    '抓取完毕，但没有找到符合筛选条件的作品。',
    '擷取完畢，但沒有找到符合篩選條件的作品。',
    'Crawl complete but did not find works that match the filter criteria.',
    'クロールは終了しましたが、フィルタ条件に一致する作品が見つかりませんでした。',
    '긁어오기가 완료되었지만 필터 조건과 일치하는 작품을 찾지 못했습니다.',
  ],
  _当前任务尚未完成: [
    '当前任务尚未完成',
    '目前工作尚未完成',
    'The current task has not yet been completed',
    '現在の作業はまだ完了していません',
    '현재 작업이 아직 완료되지 않았습니다',
  ],
  _当前任务尚未完成2: [
    '当前任务尚未完成，请等待完成后再下载。',
    '目前工作尚未完成，請等待完成後再下載。',
    'The current task has not yet been completed',
    '現在の作業はまだ完了していません、完了するまでお待ちください',
    '현재 작업이 아직 완료되지 않았습니다, 완료될 때까지 기다려주세요.',
  ],
  _列表抓取完成开始获取作品页: [
    '当前列表中有{}张作品，开始获取作品信息',
    '目前清單中有 {} 張作品，開始取得作品資訊',
    'Now has {} works. Start getting the works for more information.',
    '{} 枚の作品があります。 作品情報の取得を開始します。',
    '현재 {}개의 작품이 있습니다, 작품 정보 가져오기를 시작합니다',
  ],
  _开始获取作品页面: [
    '开始获取作品页面',
    '開始取得作品頁面',
    'Start getting the works page',
    '作品ページの取得を開始する',
    '작품 페이지 가져오기 시작',
  ],
  _无权访问: [
    '无权访问 {}，跳过该作品。',
    '沒有權限存取 {}，跳過該作品。',
    'No access {}, skip.',
    '{} のアクセス権限がありません、作品を無視する。',
    '{}에 접근 권한이 없습니다, 이 작업을 건너뜁니다.',
  ],
  _作品页状态码0: [
    '请求的 URL 不可访问 (0)',
    '要求的 URL 無法存取 (0)',
    'The requested URL is not accessible (0)',
    '要求された URL にアクセスできません (0)',
    '요청한 URL에 접근할 수 없습니다 (0)',
  ],
  _作品页状态码400: [
    '该作品已被删除 (400)',
    '該作品已被刪除 (400)',
    'The work has been deleted (400)',
    '作品は削除されました (400)',
    '이 작품은 삭제되었습니다 (400)',
  ],
  _作品页状态码401: [
    '请您登录 Pixiv 账号然后重试。(401)',
    '請您登入 Pixiv 帳號後重試。(401)',
    'Please log in to your Pixiv account and try again. (401)',
    'Pixiv アカウントにログインして、もう一度お試しください。(401)',
    'Pixiv 계정에 로그인 후 다시 시도해주세요. (401)',
  ],
  _作品页状态码403: [
    '无权访问请求的 URL (403)',
    '沒有權限存取要求的 URL (403)',
    'Have no access to the requested URL (403)',
    'リクエストされた URL にアクセスできない (403)',
    '요청한 URL에 접근 권한이 없습니다 (403)',
  ],
  _作品页状态码404: [
    '404 not found',
    '404 not found',
    '404 not found',
    '404 not found',
    '404 not found',
  ],
  _作品页状态码429: [
    '错误代码：429（请求数量过多）。下载器会重新抓取它。',
    '錯誤程式碼：429（請求數量過多）。下载器会重新抓取它。',
    'Error code: 429 (Too many requests). The downloader will re-crawl it.',
    'エラー コード: 429 (要求が多すぎます)。ダウンローダーはそれを再クロールします。',
    '오류 코드: 429(요청이 너무 많음). 다운로더가 다시 크롤링합니다.',
  ],
  _作品页状态码500: [
    'Pixiv 拒绝返回数据 (500)。下载器会重新抓取它。',
    'Pixiv 拒絕返回資料 (500)。下载器会重新抓取它。',
    'Pixiv refuses to return data (500). The downloader will re-crawl it.',
    'ピクシブはデータの返却を拒否します (500)。ダウンローダーはそれを再クロールします。',
    'pixiv는 데이터 반환을 거부합니다 (500). 다운로더가 다시 크롤링합니다.',
  ],
  _正在抓取: [
    '正在抓取，请等待……',
    '擷取中，請稍後……',
    'Getting, please wait...',
    'クロール中、しばらくお待ちください...',
    '얻어오는 중, 잠시만 기다려주세요...',
  ],
  _获取全部书签作品: [
    '获取全部书签作品，时间可能比较长，请耐心等待。',
    '取得全部書籤作品，時間可能比較長，請耐心等待。',
    'Get all bookmarked works, the time may be longer, please wait.',
    'ブックマークしたすべての作品を取得すると、時間がかかることがあります。お待ちください。',
    '북마크된 작품을 모두 가져오는 것은 시간이 오래 걸릴 수 있으니 기다려주세요.',
  ],
  _抓取图片网址遇到中断: [
    '当前任务已中断!',
    '目前工作已中斷！',
    'The current task has been interrupted.',
    '現在の作業が中断されました。',
    '현재 작업이 중단되었습니다!',
  ],
  _关闭: ['关闭', '關閉', 'close', 'クローズ', '닫기'],
  _输出信息: [
    '输出信息',
    '輸出資訊',
    'Output information',
    '出力情報',
    '출력 정보',
  ],
  _复制: ['复制', '複製', 'Copy', 'コピー', '복사'],
  _已复制到剪贴板: [
    '已复制到剪贴板，可直接粘贴',
    '已複製至剪貼簿，可直接貼上',
    'Has been copied to the clipboard',
    'クリップボードにコピーされました',
    '클립보드에 복사되었습니다.',
  ],
  _下载设置: [
    '下载设置',
    '下載設定',
    'Download settings',
    'ダウンロード設定',
    '다운로드 설정',
  ],
  _收起展开设置项: [
    '收起/展开设置项',
    '摺疊/展開設定項目',
    'Collapse/expand settings',
    '設定の折りたたみ/展開',
    '설정 축소/확장',
  ],
  _github: [
    'Github 页面，欢迎 star',
    'Github 頁面，歡迎 star',
    'Github page, if you like, please star it',
    'Github のページ、star をクリックしてください',
    'Github, 유용하셨다면 Star를 주세요.',
  ],
  _wiki: ['使用手册', 'Wiki', 'Wiki', 'マニュアル', '위키'],
  _快捷键切换显示隐藏: [
    '使用 Alt + X，可以显示和隐藏下载面板',
    'Alt + X 可以顯示或隱藏下載面板。',
    'Use Alt + X to show and hide the download panel',
    'Alt + X てダウンロードパネルを表示および非表示にする',
    'Alt + X를 사용하여 다운로드 패널 보이기 및 숨기기',
  ],
  _隐藏下载面板: [
    '隐藏下载面板（Alt + X）',
    '隱藏下載面板（Alt + X）',
    'Hide the download panel (Alt + X)',
    'ダウンロードパネルを非表示にする（Alt + X）',
    '다운로드 패널 숨기기 (Alt + X)',
  ],
  _共抓取到n个文件: [
    '共抓取到 {} 个文件',
    '共擷取到 {} 個檔案',
    'Crawl a total of {} files',
    '合計 {} つのファイルがあります',
    '총 {}개의 파일을 긁어왔습니다',
  ],
  _共抓取到n个作品: [
    '共抓取到 {} 个作品',
    '共擷取到 {} 個作品',
    'Crawl a total of {} works',
    '合計 {} つの作品があります',
    '총 {}개의 작품을 긁어왔습니다',
  ],
  _命名规则: [
    ' <span class="key">命名</span>规则',
    '<span class="key">命名</span>規則',
    '<span class="key">Naming</span> rule',
    '<span class="key">命名</span>規則',
    '<span class="key">명명</span> 규칙',
  ],
  _设置文件夹名的提示: [
    `可以使用 '<span class="key">/</span>' 建立文件夹。示例：`,
    `可以使用斜線（<span class="key">/</span>）建立資料夾。範例：`,
    `You can create a directory with '<span class="key">/</span>'. Example：`,
    `フォルダーは '<span class="key">/</span>' で作成できます。例：`,
    `'<span class="key">/</span>'을 사용하여 디렉토리를 생성할 수 있습니다.<br>예:`,
  ],
  _添加命名标记前缀: [
    '添加命名标记<span class="key">前缀</span>',
    '加入命名標記<span class="key">前綴</span>',
    'Add named tag <span class="key">prefix</span>',
    '前にタグの名前を追加',
    '명명된 태그 추가 <span class="key">접두사</span>',
  ],
  _添加字段名称提示: [
    `例如，在用户名前面添加“user_”标记`,
    '例如，在使用者名稱前面加入「user_」標記。',
    `For example, add the 'user_' tag in front of the username`,
    'たとえば、ユーザー名の前に 「user_」タグを追加します。',
    `예: 유저명 앞에 'user_' 태그 추가`,
  ],
  _命名标记id: [
    '默认文件名，如 44920385_p0',
    '預設檔案名稱，例如：44920385_p0。',
    'Default file name, for example 44920385_p0',
    'デフォルトのファイル名，例 44920385_p0',
    '기본 파일명. 예: 44920385_p0',
  ],
  _命名标记title: [
    '作品标题',
    '作品標題',
    'Works title',
    '作品のタイトル',
    '작품 제목',
  ],
  _命名标记tags: [
    '作品的标签列表',
    '作品的標籤清單',
    'The tags of the work',
    '作品のタグ',
    '작품 태그',
  ],
  _命名标记user: [
    '用户名字',
    '使用者名稱',
    'User name',
    'ユーザー名',
    '유저명',
  ],
  _用户id: ['用户 ID', '使用者 ID', 'User ID', 'ユーザー ID', '유저 ID'],
  _命名标记px: [
    '宽度和高度',
    '寬度和高度',
    'Width and height',
    '幅と高さ',
    '너비와 높이',
  ],
  _命名标记bmk: [
    'Bookmark count，作品的收藏数。把它放在最前面可以让文件按收藏数排序。',
    'Bookmark count，作品的收藏數。將它放在最前面可以讓檔案依收藏數排序。',
    'Bookmark count, bookmarks number of works.',
    'Bookmark count，作品のボックマークの数、前に追加することでボックマーク数で并べることができます。',
    '북마크 수. 맨 앞에 두면 북마크 수별로 문서를 정렬할 수 있습니다.',
  ],
  _命名标记bmk_id: [
    'Bookmark Id。你收藏的每一个作品都会有一个 Bookmark Id。收藏的时间越晚，Bookmark Id 就越大。当你下载你的收藏时，可以使用 {bmk_id} 作为排序依据。',
    'Bookmark Id。你收藏的每一個作品都會有一個 Bookmark Id。收藏的時間越晚，Bookmark Id 就越大。當你下載你的收藏時，可以使用 {bmk_id} 作為排序依據。',
    'Bookmark Id. Every work in your bookmarks will have a Bookmark Id. The later the bookmark is added, the larger the Bookmark Id. When you download your bookmarks, you can use {bmk_id} as a sorting basis.',
    'ブックマークID。 ブックマーク内のすべての作品にはブックマークIDがあります。 ブックマークを後で追加すると、ブックマークIDが大きくなります。 ブックマークをダウンロードするときは、{bmk_id}を並べ替えの基準として使用できます。',
    '북마크 ID. 당신이 북마크하고 있는 작품마다 북마크 ID가 있습니다. 북마크 시간이 늦어질수록 북마크 ID는 커집니다. 북마크를 다운로드할때 {bmk_id}를 기준으로 정렬할 수 있습니다.',
  ],
  _命名标记bmk_1000: [
    '作品收藏数的简化显示。例如：0+、1000+、2000+、3000+ ……',
    '作品收藏數的簡化顯示。例如：0+、1000+、2000+、3000+ ……',
    'Simplified number of bookmark, e.g. 0+、1000+、2000+、3000+ ……',
    '作品のボックマークの数の簡略表示。 例：0+、1000+、2000+、3000+ ……',
    '단순화된 북마크 수. 예: 0+, 1000+, 2000+, 3000+ ……',
  ],
  _命名标记like: [
    'Like count，作品的点赞数。',
    'Like count，作品的點讚數。',
    'Like count.',
    'Like count。',
    '좋아요 수',
  ],
  _命名标记view: [
    'View count，作品的浏览量。',
    'View count，作品的瀏覽量。',
    'View count.',
    'View count。',
    '조회수',
  ],
  _命名标记id_num: [
    '数字 id，如 44920385',
    '數字 id，例如：44920385。',
    'Number id, for example 44920385',
    '44920385 などの番号 ID',
    '숫자 ID. 예: 44920385',
  ],
  _命名标记p_num: [
    '图片在作品内的序号，如 0、1、2 …… 每个作品都会重新计数。',
    '圖片在作品內的序號，例如：0、1、2……每個作品都將重新計數。',
    'The serial number of the image in the work, such as 0, 1, 2 ... Each work will be recounted.',
    '0、1、2 など、作品の画像のシリアル番号。各ピースは再集計されます。',
    '작품 안에 있는 번호. 예: 0, 1, 2 …… 작품마다 다시 세어봅니다.',
  ],
  _命名标记tags_trans: [
    '作品的标签列表，附带翻译后的标签（如果有）',
    '作品的標籤清單，包含翻譯後的標籤（如果有的話）。',
    'The tags of the work, with the translated tag (if any)',
    '作品のタグリスト、翻訳付きタグ(あれば)',
    '작품 태그, 번역된 태그 (있다면)',
  ],
  _命名标记tags_transl_only: [
    '翻译后的标签列表',
    '譯後的標籤清單。',
    'Translated tags',
    '翻訳后のタグリスト',
    '번역된 태그',
  ],
  _命名标记date: [
    '作品的创建时间。如 2019-08-29',
    '作品的建立時間。例如：2019-08-29。',
    'The time the creation of the work. Such as 2019-08-29',
    '作品の作成時間。例 2019-08-29',
    '작품 생성 날짜. 예: 2019-08-29',
  ],
  _命名标记rank: [
    '作品在排行榜中的排名。如 #1、#2 …… 只能在排行榜页面中使用。',
    '作品在排行榜中的排名。例如：#1、#2……只能在排行榜頁面中使用。',
    'The ranking of the work in the ranking pages. Such as #1, #2 ... Can only be used in ranking pages.',
    '作品のランキング。例え　#1、#2 …… ランキングページのみで使用できます。',
    '작품의 랭킹. 예: #1, #2 …… 랭킹 페이지에서만 사용할 수 있습니다.',
  ],
  _命名标记type: [
    '作品类型，分为：Illustration, Manga, Ugoira, Novel',
    '作品類型，分為：Illustration, Manga, Ugoira, Novel',
    'The type of work, divided into：Illustration, Manga, Ugoira, Novel',
    '作品分類は：Illustration, Manga, Ugoira, Novel',
    '작품 유형: 일러스트, 만화, 움직이는 일러스트, 소설',
  ],
  _命名标记提醒: [
    '为了防止文件名重复，命名规则里一定要包含 {id} 或者 {id_num}{p_num}。<br>您可以使用多个标记；建议在不同标记之间添加分割用的字符。示例：{id}-{user_id}<br>* 在某些情况下，会有一些标记不可用。',
    '為了防止檔名重複，命名規則裡一定要包含 {id} 或者 {id_num}{p_num}。可以使用多個標記；建議在不同標記之間加入分隔用的字元。範例：{id}-{user_id}<br>＊某些情況下有些標記無法使用。',
    'To prevent duplicate file names, {id} or {id_num}{p_num} must be included in the naming rules.<br>You can use multiple tags, and you can add a separate character between different tags. Example: {id}-{user_id}<br>* In some cases, some tags will not be available.',
    'ファイル名の重複を防ぐために、命名規則には {id} または {id_num}{p_num} を含める必要があります。<br>複数のタグを使用することができます；異なるタグ間の分割のために文字を追加することをお勧めします。例：{id}-{user_id}<br>* 場合によっては、一部のタグが利用できず。',
    '파일명이 중복되지 않도록, 명명 규칙에는 {id} 또는 {id_num}{p_num}이 포함되어야 합니다.<br>여러 태그를 사용할 수 있습니다. 서로 다른 태그 사이에 구분자를 넣는 것을 권장합니다. 예: {id}-{user}<br>* 경우에 따라서는 사용할 수 없는 태그가 있을 수 있습니다.',
  ],
  _命名规则一定要包含id: [
    '为了防止文件名重复，命名规则里一定要包含 {id} 或者 {id_num}{p_num}',
    '為了防止檔名重複，命名規則裡一定要包含 {id} 或者 {id_num}{p_num}。',
    'To prevent duplicate file names, {id} or {id_num}{p_num} must be included in the naming rules.',
    'ファイル名の重複を防ぐために、命名規則には {id} または {id_num}{p_num} を含める必要があります。',
    '파일명이 중복되지 않도록, 명명 규칙에는 {id} 또는 {id_num}{p_num}이 포함되어야 합니다.',
  ],
  _文件夹标记PTag: [
    '当前页面的标签。当前页面没有标签时不可用。',
    '目前頁面的標籤。目前頁面沒有標籤時無法使用。',
    'The tag of the current page. Not available if the current page has no tag.',
    '現在のページのタグ。現在のページのタグ がないときは使用できません。',
    '현재 페이지 태그. 태그가 없는 경우 사용할 수 없습니다.',
  ],
  _命名标记seriesTitle: [
    '系列标题，只在系列页面中可用（小说系列、漫画系列）。',
    '系列標題，只在系列頁面中可用（小說系列、漫畫系列）。',
    'Series title, only available in series pages (Novel series, Manga series).',
    'シリーズタイトル，シリーズページのみ（小説連載、漫画連載）。',
    '시리즈 제목, 시리즈 페이지에서만 사용 가능(소설 시리즈, 만화 시리즈).',
  ],
  _命名标记seriesOrder: [
    '作品在系列中的序号，如 #1 #2。只在系列页面中可用（小说系列、漫画系列）。',
    '作品在系列中的編號，如 #1 #2。只在系列頁面中可用（小說系列、漫畫系列）。',
    'The number of the work in the series, such as #1 #2. only available in series pages (Novel series, Manga series).',
    'シリーズの中の作品の番号，例え #1 #2。シリーズページのみ（小説連載、漫画連載）。',
    '시리즈 내 작품 번호. 예: #1 #2. 시리즈 페이지에서만 사용 가능(소설 시리즈, 만화 시리즈).',
  ],
  _命名标记seriesId: [
    '系列 ID，只在系列页面中可用（小说系列、漫画系列）。',
    '系列 ID，只在系列頁面中可用（小說系列、漫畫系列）。',
    'Series ID, only available in series pages (Novel series, Manga series).',
    'シリーズ ID，シリーズページのみ（小説連載、漫画連載）。',
    '시리즈 ID, 시리즈 페이지에서만 사용 가능(소설 시리즈, 만화 시리즈).',
  ],
  _文件夹标记PTitle: [
    '当前页面的标题',
    '目前頁面的標題',
    'The title of this page',
    'ページのタイトル',
    '현재 페이지 제목',
  ],
  _预览文件名: [
    '预览文件名',
    '預覽檔案名稱',
    'Preview file name',
    'ファイル名のプレビュー',
    '파일명 미리보기',
  ],
  _下载线程: [
    '下载<span class="key">线程</span>',
    '下載<span class="key">執行緒</span>',
    'Download <span class="key">thread</span>',
    '同時ダウンロード数',
    '다운로드 <span class="key">쓰레드</span>',
  ],
  _下载线程的说明: [
    `你可以输入 1-${Config.downloadThreadMax} 之间的数字，设置同时下载的数量`,
    `你可以輸入 1-${Config.downloadThreadMax} 之間的數字，設定同時下載的數量。`,
    `You can type a number between 1-${Config.downloadThreadMax} to set the number of concurrent downloads`,
    `同時ダウンロード数を設定、1-${Config.downloadThreadMax} の数値を入力してください`,
    `1-${Config.downloadThreadMax} 사이의 숫자를 입력하여 동시 다운로드 수를 설정할 수 있습니다.`,
  ],
  _开始下载: [
    '开始下载',
    '開始下載',
    'Start download',
    '開始',
    '다운로드 시작',
  ],
  _暂停下载: [
    '暂停下载',
    '暫停下載',
    'Pause download',
    '一時停止',
    '다운로드 일시중지',
  ],
  _停止下载: ['停止下载', '停止下載', 'Stop download', '停止', '다운로드 정지'],
  _复制url: [
    '复制 URL',
    '複製下載網址',
    'Copy URLs',
    'URL をコピー',
    'URL 복사',
  ],
  _当前状态: ['当前状态 ', '目前狀態：', 'State ', '現在の状態 ', '현재 상태'],
  _未开始下载: [
    '未开始下载',
    '未開始下載',
    'Not yet started downloading',
    'まだダウンロードを開始していません',
    '아직 다운로드를 시작하지 않았습니다.',
  ],
  _下载进度: [
    '下载进度',
    '下載進度',
    'Total progress',
    '概要',
    '다운로드 진행률',
  ],
  _常见问题: ['常见问题', '常見問題', 'Help', 'よくある質問', '도움말'],
  _uuid: [
    '如果下载后的文件名异常，请禁用其他有下载功能的浏览器扩展。<br>例如：Chrono 下载管理器、free Download Manager、Image Downloader、DownThemAll! 等。',
    '如果下載後的檔案名稱異常，請停用其他有下載功能的瀏覽器擴充功能。<br>例如：Chrono 下载管理器、free Download Manager、Image Downloader、DownThemAll! 等。',
    'If the file name after downloading is abnormal, disable other browser extensions that have download capabilities.<br>For example: Chrono Download Manager, free Download Manager, Image Downloader, DownThemAll! and more.',
    'ダウンロード後のファイル名が異常な場合は、ダウンロード機能を持つ他のブラウザ拡張機能を無効にしてください。<br>例：Chrono Download Manager, free Download Manager, Image Downloader, DownThemAll! など。',
    '다운로드 후 파일명이 이상할 경우 다운로드 기능이 있는 다른 브라우저 확장 프로그램을 비활성화해주세요.예: Chrono Download Manager, free Download Manager、Image Downloader、DownThemAll! 등.',
  ],
  _常见问题说明: [
    '下载的文件保存在浏览器的下载目录里。<br><br>建议在浏览器的下载设置中关闭“下载前询问每个文件的保存位置”。<br><br>如果下载后的文件名异常，请禁用其他有下载功能的浏览器扩展。<br><br>如果你使用 ssr、v2ray 等代理软件，开启全局代理有助于提高下载速度。<br><br>QQ群：675174717<br><br>在 Wiki 查看常见问题：<br><a href="https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/常见问题" target="_blank">https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/常见问题</a><br><br>中文教程视频：<br><a href="https://www.youtube.com/playlist?list=PLO2Mj4AiZzWEpN6x_lAG8mzeNyJzd478d" target="_blank">https://www.youtube.com/playlist?list=PLO2Mj4AiZzWEpN6x_lAG8mzeNyJzd478d</a>',
    '下載的檔案儲存在瀏覽器的下載目錄裡。<br><br>請不要在瀏覽器的下載選項裡選取「下載每個檔案前先詢問儲存位置」。<br><br>如果下載後的檔名異常，請停用其他有下載功能的瀏覽器擴充功能。',
    'The downloaded file is saved in the browser`s download directory. <br><br>It is recommended to turn off "Ask where to save each file before downloading" in the browser`s download settings.<br><br>If the file name after downloading is abnormal, disable other browser extensions that have download capabilities.',
    'ダウンロードしたファイルは、ブラウザのダウンロードディレクトリに保存されます。<br><br>ブラウザのダウンロード設定で 「 ダウンロード前に各ファイルの保存場所を確認する 」 をオフにすることをお勧めします。<br><br>ダウンロード後のファイル名が異常な場合は、ダウンロード機能を持つ他のブラウザ拡張機能を無効にしてください。',
    '다운로드한 파일은 브라우저의 다운로드 디렉토리에 저장됩니다.<br><br>브라우저의 다운로드 설정에서 "다운로드 전에 각 파일의 저장 위치 확인"을 끄는 것이 좋습니다.<br><br>다운로드 후 파일명이 이상할 경우 다운로드 기능이 있는 다른 브라우저 확장 프로그램을 비활성화해주세요.',
  ],
  _首次下载显示的提示: [
    '下载的文件保存在浏览器的下载目录里。<br><br>建议您在浏览器的下载设置中关闭“下载前询问每个文件的保存位置”。<br><br>如果你使用 ssr、v2ray 等代理软件，开启全局代理有助于提高下载速度。',
    '下載的檔案儲存在瀏覽器的下載目錄裡。<br><br>請不要在瀏覽器的下載選項裡選取「下載每個檔案前先詢問儲存位置」。',
    'The downloaded file is saved in the browser`s download directory. <br><br>It is recommended to turn off "Ask where to save each file before downloading" in the browser`s download settings.',
    'ダウンロードしたファイルは、ブラウザのダウンロードディレクトリに保存されます。<br><br>ブラウザのダウンロード設定で 「 ダウンロード前に各ファイルの保存場所を確認する 」 をオフにすることをお勧めします。',
    '다운로드한 파일은 브라우저의 다운로드 디렉토리에 저장됩니다.<br><br>브라우저의 다운로드 설정에서 "다운로드 전에 각 파일의 저장 위치 확인"을 끄는 것이 좋습니다.',
  ],
  _正在下载中: [
    '正在下载中',
    '正在下載',
    'Downloading',
    'ダウンロード中',
    '다운로드 중',
  ],
  _下载完毕: [
    '✓ 下载完毕',
    '✓ 下載完畢',
    '✓ Download complete',
    '✓ ダウンロードが完了しました',
    '✓ 다운로드 완료',
  ],
  _下载完毕2: [
    '下载完毕',
    '下載完畢',
    'Download complete',
    'ダウンロードが完了しました',
    '다운로드 완료',
  ],
  _已暂停: [
    '下载已暂停',
    '下載已暫停',
    'Download is paused',
    'ダウンロードは一時停止中です',
    '다운로드 일시중지',
  ],
  _已停止: [
    '下载已停止',
    '下載已停止',
    'Download stopped',
    'ダウンロードが停止しました',
    '다운로드 정지',
  ],
  _已下载: ['已下载', '已下載', 'downloaded', 'downloaded', '다운로드됨'],
  _抓取完毕: [
    '抓取完毕！',
    '擷取完畢！',
    'Crawl complete!',
    'クロールが終了しました！',
    '긁어오기 완료!',
  ],
  _快速下载本页: [
    '快速下载本页作品 (Alt + Q)',
    '快速下載本頁作品 (Alt + Q)',
    'Download this work quickly (Alt + Q)',
    'この作品をすばやくダウンロードする (Alt + Q)',
    '작품 빠른 다운로드 (Alt + Q)',
  ],
  _从本页开始抓取new: [
    '从本页开始抓取新作品',
    '從本頁開始擷取新作品',
    'Crawl the new works from this page',
    'このページから新しい作品を入手する',
    '이 페이지부터 새 작품 긁어오기',
  ],
  _从本页开始抓取old: [
    '从本页开始抓取旧作品',
    '從本頁開始擷取舊作品',
    'Crawl the old works from this page',
    'このページから古い作品を入手する',
    '이 페이지부터 오래된 작품 긁어오기',
  ],
  _抓取推荐作品: [
    '抓取推荐作品',
    '擷取推薦作品',
    'Crawl the recommend works',
    '推奨作品をダウンロードする',
    '추천 작품 긁어오기',
  ],
  _抓取推荐作品Title: [
    '抓取页面底部的的推荐作品',
    '擷取頁面底部的推薦作品。',
    'Crawl the recommended works at the bottom of the page',
    'ページの下部で推奨作品をクロールします',
    '페이지 하단 추천 작품 긁어오기',
  ],
  _抓取相关作品: [
    '抓取相关作品',
    '擷取相關作品',
    'Crawl the related works',
    '関連作品をダウンロードする',
    '관련 작품 긁어오기',
  ],
  _调整完毕: [
    '调整完毕，当前有{}个作品。',
    '調整完畢，目前有 {} 個作品。',
    'The adjustment is complete and now has {} works.',
    '調整が完了し、今、{} の作品があります。',
    '조정이 완료되어, 현재 {}개의 작품이 있습니다.',
  ],
  _抓取当前作品: [
    '抓取当前作品',
    '擷取目前作品',
    'Crawl the current work',
    '現在の作品をクロールする',
    '현재 작품 긁어오기',
  ],
  _抓取当前作品Title: [
    '抓取当前列表里的所有作品',
    '擷取目前清單裡的所有作品',
    'Crawl all the works in the current list',
    '現在のリスト内のすべての作品をクロールする',
    '현재 목록에 있는 모든 작품 긁어오기',
  ],
  _清除多图作品: [
    '清除多图作品',
    '清除多圖作品',
    'Remove multi-image works',
    '複数画像をクリア',
    '여러 이미지 작품 지우기',
  ],
  _清除动图作品: [
    '清除动图作品',
    '清除動圖作品',
    'Remove ugoira work',
    'うごイラ作品を削除する',
    '움직이는 일러스트 작품 지우기',
  ],
  _手动删除作品: [
    '手动删除作品',
    '手動刪除作品',
    'Manually delete the work',
    '作品を手動で削除する',
    '수동으로 작품 지우기',
  ],
  _手动删除作品Title: [
    '可以在下载前手动删除不需要的作品',
    '可以在下載前手動刪除不需要的作品，點擊作品刪除。',
    'You can manually delete unwanted work before downloading',
    'ダウンロードする前に不要な作品を手動で削除することができます',
    '다운로드를 원하지 않는 작품을 수동으로 지울 수 있습니다.',
  ],
  _退出手动删除: [
    '退出手动删除',
    '結束手動刪除',
    'Exit manually delete',
    '削除モードを終了する',
    '수동 지우기 종료',
  ],
  _抓取本页作品: [
    '抓取本页作品',
    '擷取本頁作品',
    'Crawl this page works',
    'このページをクロールする',
    '이 페이지의 작품 긁어오기',
  ],
  _抓取本页作品Title: [
    '抓取本页列表中的所有作品',
    '擷取本頁清單中的所有作品',
    'Crawl this page works',
    'このページの全ての作品をクロールする',
    '이 페이지의 모든 작품 긁어오기',
  ],
  _抓取本排行榜作品: [
    '抓取本排行榜作品',
    '擷取本排行榜作品',
    'Crawl the works in this list',
    'このリストの作品をクロールする',
    '이 목록의 작품 긁어오기',
  ],
  _抓取本排行榜作品Title: [
    '抓取本排行榜的所有作品，包括现在尚未加载出来的。',
    '擷取本排行榜的所有作品，包括現在尚未載入出來的。',
    'Crawl all of the works in this list, including those that are not yet loaded.',
    'まだ読み込まれていないものを含めて、このリストの作品をダウンロードする',
    '아직 불러오지 않은 작품을 포함하여, 이 목록의 모든 작품을 긁어옵니다.',
  ],
  _抓取首次登场的作品: [
    '抓取首次登场作品',
    '擷取首次登場作品',
    'Crawl the debut works',
    '初登場作品をダウンロードする',
    '데뷔작 긁어오기',
  ],
  _抓取首次登场的作品Title: [
    '只下载首次登场的作品',
    '只下載首次登場的作品',
    'Download only debut works',
    '初登場作品のみダウンロードします',
    '데뷔작만 다운로드',
  ],
  _抓取该页面的图片: [
    '抓取该页面的图片',
    '擷取該頁面的圖片',
    'Crawl the image of the page',
    'ページの画像をクロールする',
    '페이지의 이미지 긁어오기',
  ],
  _抓取相似图片: [
    '抓取相似图片',
    '擷取相似圖片',
    'Crawl similar works',
    '類似の作品をクロールする',
    '비슷한 작품 긁어오기',
  ],
  _想要获取多少个作品: [
    '您想要获取多少个作品？',
    '想要取得多少個作品？',
    'How many works do you want to download?',
    'いくつの作品をダウンロードしたいですか？',
    '몇 개의 작품을 다운로드하시겠습니까?',
  ],
  _数字提示1: [
    '-1, 或者大于 0',
    '-1，或是大於 0',
    '-1, or greater than 0',
    '-1、または 0 より大きい',
    '-1, 또는 0보다 크게',
  ],
  _下载大家的新作品: [
    '下载大家的新作品',
    '下載大家的新作品',
    'Download everyone`s new work',
    'みんなの新作をダウンロードする',
    '모두의 새 작품 다운로드',
  ],
  _屏蔽设定: [
    '屏蔽設定',
    '封鎖設定',
    'Mute settings',
    'ミュート設定',
    '차단 설정',
  ],
  _举报: ['举报', '回報', 'Report', '報告', '신고'],
  _输入id进行抓取: [
    '输入 id 进行抓取',
    '輸入 id 進行擷取',
    'Type id to crawl',
    'idを入力してダウンロードする',
    '유형 ID 긁어오기',
  ],
  _输入id进行抓取的提示文字: [
    '请输入作品 id。如果有多个 id，则以换行分割（即每行一个id）',
    '請輸入作品 id。如果有多個 id，則以換行分隔（即每行一個 id）。',
    'Please type the illustration id. If there is more than one id, one id per line.',
    'イラストレーターIDを入力してください。 複数の id がある場合は、1 行に 1 つの id を付けます。',
    '일러스트 작품 ID를 입력해주세요. 여러 개의 ID가 있으면 줄을 바꾸어주세요 (한 줄에 한 개의 ID)',
  ],
  _开始抓取: [
    '开始抓取',
    '開始擷取',
    'Start crawl',
    'クロールを開始する',
    '긁어오기 시작',
  ],
  _给未分类作品添加添加tag: [
    '给未分类作品添加标签',
    '幫未分類的作品加入標籤',
    'Add tag to unclassified work',
    '未分類の作品にタグを追加',
    '분류되지 않은 작품에 태그 추가',
  ],
  _id不合法: [
    'id不合法',
    'id 不合法',
    'id is illegal',
    'id が不正な',
    '올바르지 않은 ID',
  ],
  _快速收藏: [
    '快速收藏',
    '快速收藏',
    'Quick bookmarks',
    'クイックブックマーク',
    '빠른 북마크',
  ],
  _启用: ['启用', '啟用', 'Enable', '有効にする', '활성화'],
  _自动开始下载: [
    '<span class="key">自动</span>开始下载',
    '<span class="key">自動</span>開始下載',
    'Download starts <span class="key">automatically</span>',
    'ダウンロードは自動的に開始されます',
    '<span class="key">자동으로</span> 다운로드 시작',
  ],
  _自动开始下载的提示: [
    '当“开始下载”状态可用时，自动开始下载，不需要点击下载按钮。',
    '當可下載時自動開始下載，不需要點選下載按鈕。',
    'When the &quot;Start Downloa&quot; status is available, the download starts automatically and no need to click the download button.',
    '「ダウンロードを開始する」ステータスが利用可能になると、ダウンロードは自動的に開始され、ダウンロードボタンをクリックする必要はありません。',
    '"다운로드 시작" 상태가 활성화되면, 다운로드가 자동으로 시작되고 다운로드 시작 버튼을 클릭할 필요가 없게 됩니다.',
  ],
  _转换任务提示: [
    '正在转换 {} 个文件',
    '正在轉換 {} 個檔案',
    'Converting {} files',
    '{} ファイルの変換',
    '{}개의 파일을 변환하는 중',
  ],
  _最近更新: [
    '最近更新',
    '最近更新',
    'What`s new',
    '最近更新する',
    '새로운 기능',
  ],
  _确定: ['确定', '確定', 'Ok', '確定', '확인'],
  _file404: [
    '404 错误：文件 {} 不存在。',
    '404 錯誤：檔案 {} 不存在。',
    '404 error: File {} does not exist.',
    '404 エラー：ファイル {} は存在しません。',
    '404 오류: 파일 {}이 존재하지 않습니다.',
  ],
  _文件下载失败: [
    '文件 {} 下载失败',
    '檔案 {} 下載失敗',
    'File {} download failed',
    'ファイル {} のダウンロードを失敗しました',
    '파일 {} 다운로드 실패',
  ],
  _是否重置设置: [
    '是否重置设置？',
    '確定要重設設定嗎？',
    'Do you want to reset the settings?',
    '設定をリセットしますか？',
    '설정을 초기화하시겠습니까?',
  ],
  _newver: [
    '有新版本可用',
    '有新版本可更新',
    'A new version is available',
    '新しいバージョンがあります',
    '새 버전이 있습니다',
  ],
  _快速下载建立文件夹: [
    '快速下载时，始终建立文件夹',
    '快速下載時，始終建立資料夾',
    'Always create folder when downloading quickly',
    'クイックダウンロード時、常にフォルダを作成します',
    '빠른 다운로드 시, 항상 디렉토리 생성',
  ],
  _id范围: [
    '<span class="key">ID</span> 范围',
    '<span class="key">ID</span> 範圍',
    '<span class="key">ID</span> range',
    '<span class="key">ID</span> 範囲',
    '<span class="key">ID</span> 범위',
  ],
  _设置id范围提示: [
    '您可以输入一个作品 id，抓取比它新或者比它旧的作品',
    '可以輸入一個作品 id，擷取比它新或者比它舊的作品。',
    'You can type a work id and crawl works that are newer or older than it',
    '1 つの作品 id を入力することで、それより新しいあるいは古い作品をクロールことができます',
    '작품 ID를 입력하여, 그보다 새로운 혹은 오래된 작품을 긁어올 수 있습니다.',
  ],
  _大于: ['大于', '大於', 'Bigger than', 'より大きい', '보다 큼'],
  _小于: ['小于', '小於', 'Less than', 'より小さい', '보다 작음'],
  _投稿时间: [
    '投稿<span class="key">时间</span>',
    '投稿<span class="key">時間</span>',
    'Posting <span class="key">date</span>',
    '投稿日時',
    '게시 <span class="key">날짜</span>',
  ],
  _设置投稿时间提示: [
    '您可以下载指定时间内发布的作品',
    '可以下載指定時間內發布的作品。',
    'You can download works posted in a specified period of time',
    '指定された時間内に配信された作品をダウンロードすることができます',
    '지정된 기간 내에 게시된 작품을 다운로드할 수 있습니다.',
  ],
  _时间范围: ['时间范围', '時間範圍', 'Time range', '時間範囲', '시간 범위'],
  _必须大于0: [
    '必须大于 0',
    '必須大於 0',
    'must be greater than 0',
    '0 より大きくなければなりません',
    '0보다 커야합니다',
  ],
  _开始筛选: [
    '开始筛选',
    '開始篩選',
    'Start screening',
    'スクリーニング開始',
    '선별 시작',
  ],
  _开始筛选Title: [
    '按照设置来筛选当前标签里的作品。',
    '按照設定來篩選目前標籤裡的作品。',
    'Screen the works in the current tag.',
    '現在のタグにある作品を設定によってスクリーニングする',
    '설정에 따라 현재 태그 내 작품을 선별합니다.',
  ],
  _在结果中筛选: [
    '在结果中筛选',
    '在結果中篩選',
    'Screen in results',
    '結果の中からスクリーニング',
    '결과 중에서 선별',
  ],
  _在结果中筛选说明: [
    '您可以改变设置，并在结果中再次筛选。',
    '可以變更設定，並在結果中再次篩選。',
    'You can change the settings and screen again in the results.',
    '設定を変えて、結果の中で再びスクリーニングすることができます。',
    '설정을 변경하고, 결과를 다시 선별할 수 있습니다',
  ],
  _抓取筛选结果: [
    '抓取筛选结果',
    '擷取篩選結果',
    'Crawl the screening results',
    'スクリーニングの結果をクロールする',
    '선별 결과 긁어오기',
  ],
  _尚未开始筛选: [
    '尚未开始筛选',
    '尚未開始篩選',
    'Screening has not started',
    'まだスクリーニングを開始していない',
    '선별이 시작되지 않았습니다',
  ],
  _没有数据可供使用: [
    '没有数据可供使用',
    '沒有資料可供使用',
    'No data is available.',
    '使用可能なデータはない',
    '사용 가능한 데이터가 없습니다',
  ],
  _预览搜索结果: [
    '<span class="key">预览</span>搜索页面的筛选结果',
    '<span class="key">預覽</span>搜尋頁面的篩選結果',
    '<span class="key">Preview</span> filter results on search page',
    '検索ページのフィルタ結果をプレビューします',
    '<span class="key">미리보기</span> 검색 페이지 필터 결과',
  ],
  _预览搜索结果说明: [
    '下载器可以把符合条件的作品显示在当前页面上。如果抓取结果太多导致页面崩溃，请关闭这个功能。<br>启用预览功能时，下载器不会自动开始下载。',
    '下載器可以將符合條件的作品顯示在目前頁面上。如果擷取結果太多導致頁面當掉，請關閉這個功能。<br>啟用預覽功能時，下載器不會自動開始下載。',
    'The downloader can display the qualified works on the current page. If too many crawling results cause the page to crash, turn off this feature.<br>When the preview feature is enabled, the downloader does not start downloading automatically.',
    'ローダは、該当する作品を現在のページに表示することができます。クロール結果が多すぎてページが崩れる場合は、この機能をオフにしてください。<br>プレビュー機能を有効にすると、ダウンロードは自動的に開始されません。',
    '다운로더는 조건에 맞는 작품을 현재 페이지에 표시할 수 있습니다. 긁어오기 결과가 너무 많아서 페이지가 충돌하면 이 기능을 꺼주세요.<br> 미리보기를 사용하면 다운로드가 자동으로 시작되지 않습니다.',
  ],
  _目录名使用: [
    '目录名使用：',
    '資料夾名稱使用：',
    'Name: ',
    'ディレクトリ名の使用：',
    '이름: ',
  ],
  _目录名: ['目录名', '資料夾名稱', 'Name', 'ディレクトリ名', '이름'],
  _启用快速收藏: [
    '启用快速收藏',
    '開啟快速收藏',
    'Enable quick bookmark',
    'クイックボックマークを有効にする',
    '빠른 북마크 활성화',
  ],
  _启用快速收藏说明: [
    '当你点击下载器添加的收藏按钮(☆)，把作品添加到书签时，自动添加这个作品的标签。',
    '當點選下載器新增的收藏按鈕（☆），將作品加入書籤時，自動新增這個作品的標籤。',
    'When you click the favorite button (☆) added by the downloader to bookmark a work, the tag of the work is automatically added.',
    'ダウンローダーに追加されたボックマークボタン「☆」をクリックして、作品をブックマークに追加すると、自動的に作品のタグが追加されます。',
    '다운로더에 추가된 북마크 버튼(☆)을 클릭하여 북마크에 작품을 추가하면 자동으로 이 작품의 태그가 추가됩니다.',
  ],
  _新增设置项: [
    '新增设置项',
    '新增設定項目',
    'Added setting items',
    '新たな機能を追加されました',
    '새로운 설정 항목 추가',
  ],
  _新增功能: ['新增功能', '新增功能', 'New feature', '新機能', '새로운 기능'],
  _抓取: ['抓取', '擷取', 'Crawl', 'クロール', '긁어오기'],
  _下载: ['下载', '下載', 'Download', 'ダウンロード', '다운로드'],
  _其他: ['其他', '其他', 'Other', 'その他', '그 외'],
  _更多: ['更多', '更多', 'More', 'もっと', '더보기'],
  _第一张图不带序号: [
    '第一张图不带<span class="key">序号</span>',
    '第一張圖片不包含<span class="key">序號</span>',
    'The first image without a <span class="key">serial number</span>',
    '最初のイメージの番号を削除',
    '<span class="key">일련번호</span>가 없는 첫 번째 이미지',
  ],
  _第一张图不带序号说明: [
    '去掉每个作品第一张图的序号。例如 80036479_p0 变成 80036479',
    '去掉每個作品第一張圖的序號。例如：80036479_p0 變成 80036479。',
    'Remove the serial number of the first image of each work. For example 80036479_p0 becomes 80036479.',
    '作品ごとの最初のイメージの番号を削除します。例えば 80036479_p0 は 80036479 になります。',
    '작품마다 첫 번째 이미지의 일련번호를 지웁니다.<br>예: 80036479_p0은 80036479가 됩니다.',
  ],
  _最小值: ['最小值', '最小值', 'Minimum', '最小値', '최소'],
  _最大值: ['最大值', '最大值', 'Maximum', '最大値', '최대'],
  _单图作品: [
    '单图作品',
    '單圖作品',
    'Single image works',
    'シングルイメージ作品',
    '단일 이미지 작품',
  ],
  _彩色图片: [
    '彩色图片',
    '彩色圖片',
    'Color images',
    'カラーイメージ',
    '컬러 이미지',
  ],
  _黑白图片: [
    '黑白图片',
    '黑白圖片',
    'Black and white images',
    '白黒イメージ',
    '흑백 이미지',
  ],
  _不保存图片因为颜色: [
    '{} 没有被保存，因为它的颜色不符合设定。',
    '{} 並未儲存，因為它的色彩不符合設定。',
    '{} was not saved because its colors do not match the settings.',
    '{} は色が設定に合わないため、保存されていません。',
    '{} 색상이 설정과 일치하지 않아, 저장되지 않았습니다.',
  ],
  _同时转换多少个动图: [
    '同时<span class="key">转换</span>多少个动图',
    '同時<span class="key">轉換</span>多少個動圖',
    'How many animations are <span class="key">converted</span> at the same time',
    '同時変換のうごイラの上限',
    '동시에 <span class="key">변환할</span> 움직이는 일러스트 수',
  ],
  _同时转换多少个动图警告: [
    '同时转换多个动图会增加资源占用。<br>转换动图时，请保持该标签页激活，否则浏览器会降低转换速度。',
    '同時轉換多個動圖會增加資源占用。<br>轉換動圖時，請保持這個分頁啟動，否則瀏覽器會降低轉換速度。',
    'Converting multiple animations at the same time will increase resource consumption. <br> Please keep the tab active when converting animation, otherwise the browser will reduce the conversion speed.',
    '複数の動画を同時に変換すると、リソースの占有が増加します。<br>うごイラを変換するときは、このタブを有効にしてください。そうしないと、ブラウザは変換速度を下げます。',
    '여러 움직이는 일러스트를 동시에 변환하면 리소스가 더 많이 사용됩니다.<br>움직이는 일러스트를 변환할 때 이 탭을 활성화하지 않으면 브라우저에서 변환 속도를 줄일 수 있습니다.',
  ],
  _提示: ['提示', '提示', 'Tip', 'ヒント', '팁'],
  _提示2: ['提示', '提示', 'Tip', '？', '팁'],
  _fanboxDownloader: [
    'Fanbox 下载器',
    'Fanbox 下載器',
    'Fanbox Downloader',
    'Fanbox ダウンロード',
    'Fanbox 다운로더',
  ],
  _不保存图片因为体积: [
    '{} 没有被保存，因为它的体积不符合设定。',
    '{} 並未儲存，因為它的大小不符合設定。',
    '{} was not saved because its size do not match the settings.',
    '{} はファイルサイズが設定に合わないため、保存されていません。',
    '{} 크기가 설정에 맞지 않아, 저장되지 않았습니다.',
  ],
  _文件体积限制: [
    '文件<span class="key">体积</span>限制',
    '檔案<span class="key">體積</span>限制',
    'File <span class="key">size</span> limit',
    'ファイルサイズ制限',
    '파일 <span class="key">크기</span> 제한',
  ],
  _不符合要求的文件不会被保存: [
    '不符合要求的文件不会被保存。',
    '不會儲存不符合要求的檔案。',
    'Files that do not meet the requirements will not be saved.',
    '設定 に合わないファイルは保存されません。',
    '요구 사항을 충족하지 않는 파일은 저장되지 않습니다.',
  ],
  _小说: ['小说', '小說', 'Novel', '小説', '소설'],
  _抓取系列小说: [
    '抓取系列小说',
    '擷取系列小說',
    'Crawl series of novels',
    '小説のシリーズをクロールする',
    '시리즈 소설 긁어오기',
  ],
  _合并系列小说: [
    '合并系列小说',
    '合併系列小說',
    'Merge series of novels',
    'シリーズ小説の統合',
    '시리즈 소설 합치기',
  ],
  _小说保存格式: [
    '<span class="key">小说</span>保存格式',
    '<span class="key">小說</span>儲存格式',
    'Save the <span class="key">novel</span> as',
    '<span class="key">小説</span>の保存形式',
    '<span class="key">소설</span>저장 형식',
  ],
  _在小说里保存元数据: [
    '在小说里保存<span class="key">元数据</span>',
    '在小說裡儲存<span class="key">元資料</span>',
    'Save <span class="key">metadata</span> in the novel',
    '小説の中にメタデータを保存する',
    '소설 내 <span class="key">메타데이터</span> 저장',
  ],
  _在小说里保存元数据提示: [
    '把作者、网址等信息保存到小说里',
    '將作者、網址等資訊儲存到小說裡',
    'Save the author, URL and other information in the file',
    '作者やURLなどの情報をファイルの中に保存します。',
    '작가, URL, 그 외 정보를 소설 내에 저장합니다.',
  ],
  _收藏本页面的所有作品: [
    '收藏本页面的所有作品',
    '收藏本頁面的所有作品',
    'Bookmark all works on this page',
    'この頁の全ての作品をブックマークに追加します',
    '이 페이지의 북마크된 모든 작품 다운로드',
  ],
  _输出内容太多已经为你保存到文件: [
    '因为输出内容太多，已经为您保存到文件。',
    '因為輸出內容太多，已經為你儲存到檔案。',
    'Because the output is too much, it has been saved to a file.',
    '出力内容が多いため、txt ファイルに保存しました。',
    '출력 내용이 너무 많아, 파일로 저장했습니다.',
  ],
  _不下载重复文件: [
    '不下载<span class="key">重复</span>文件',
    '不下載<span class="key">重複</span>檔案',
    'Don`t download <span class="key">duplicate</span> files',
    '重複ファイルをダウンロードしない',
    '<span class="key">중복</span>파일 다운로드하지 않기',
  ],
  _不下载重复文件的提示: [
    '下载器会保存自己的下载记录，以避免下载重复的文件。<br>当你清除 Cookie 和其他站点数据时，下载器的记录也会被清除。',
    '下載器會儲存自己的下載紀錄，以避免下載重複的檔案。<br>當你清除 Cookie 和其他站點資料時，下載器的紀錄也會被清除。',
    `The downloader will save its download record to avoid downloading duplicate files.<br>When you clear cookies and other site data, the downloader's records will also be cleared.`,
    'ダウンローダーは独自のダウンロード履歴を保存して、重複ファイルのダウンロードを回避する。<br>cookie と他のサイトデータを削除すると、ダウンローダーの記録も削除されます。',
    '다운로더가 중복되는 파일을 다운로드하지 않도록 자신의 다운로드 기록을 저장합니다.<br>쿠키와 다른 사이트 데이터를 지울 때 다운로드 기록도 삭제됩니다.',
  ],
  _策略: ['策略：', '策略：', 'Strategy:', 'フィルター：', '전략:'],
  _严格: ['严格', '嚴格', 'Strict', '厳格', '엄격하게'],
  _宽松: ['宽松', '寬鬆', 'Loose', '緩い', '느슨하게'],
  _严格模式说明: [
    '判断条件：作品的 id、上传日期、文件名',
    '判斷條件：作品的 id、上傳日期、檔名',
    'Judgment conditions: id, upload date, file name of the work',
    '審査条件：作品のID、アップロード日、ファイル名',
    '판정 조건: 작품 ID, 업로드 날짜, 파일명',
  ],
  _宽松模式说明: [
    '判断条件：作品的 id、上传日期',
    '判斷條件：作品的 id、上傳日期',
    'Judgment conditions: id, upload date of the work',
    '審査条件：作品のID、アップロード日',
    '판정 조건: 작품 ID, 업로드 날짜',
  ],
  _清除下载记录: [
    '清除下载记录',
    '清除下載紀錄',
    'Clear download record',
    '履歴をクリア',
    '다운로드 기록 비우기',
  ],
  _下载记录已清除: [
    '下载记录已清除',
    '已清除下載紀錄',
    'Download record has been cleared',
    'ダウンロード履歴がクリアされました',
    '다운로드 기록이 비워졌습니다',
  ],
  _跳过下载因为重复文件: [
    '检测到文件 {} 已经下载过，跳过此次下载',
    '偵測到檔案 {} 已經下載過，跳過此次下載。',
    'Skip downloading duplicate files {}',
    '重複ファイル {} をスキップ',
    '파일 {}이(가) 이미 다운로드되어 있어, 다운로드를 건너뜁니다',
  ],
  _保存用户头像为图标: [
    '保存用户头像为图标',
    '將使用者頭貼另存為圖示檔案',
    'Save user avatar as icon',
    'プロフィール画像をアイコンとして保存',
    '아이콘으로 유저 프로필 이미지 저장',
  ],
  _保存用户头像为图标说明: [
    '把用户头像保存为 ico 文件，可以手动设置成文件夹的图标。',
    '將使用者頭貼儲存為 ico 檔案，可以手動設定成資料夾圖示。',
    'Save user avatar as icon',
    'ユーザーのプロフィール画像を ico ファイルとして保存して、フォルダーアイコンとして設定できます。',
    '유저 프로필 이미지를 ico 파일로 저장하면, 디렉토리 아이콘으로 수동 설정할 수 있습니다.',
  ],
  _正在保存抓取结果: [
    '正在保存抓取结果',
    '正在儲存擷取結果',
    'Saving crawl results',
    'クロール結果を保存しています',
    '긁어오기 결과 저장 중',
  ],
  _已保存抓取结果: [
    '已保存抓取结果',
    '已儲存擷取結果',
    'Crawl results saved',
    'クロール結果を保存しました',
    '긁어오기 결과가 저장되었습니다',
  ],
  _正在恢复抓取结果: [
    '正在恢复抓取结果',
    '正在還原擷取結果',
    'Restoring crawl results',
    'クロール結果を再開しています',
    '긁어오기 결과 복구 중',
  ],
  _已恢复抓取结果: [
    '已恢复抓取结果',
    '已還原擷取結果',
    'Crawl results resumed',
    'クロール結果を再開しました',
    '긁어오기 결과가 복구되었습니다',
  ],
  _清空已保存的抓取结果: [
    '清空已保存的抓取结果',
    '清除已儲存的擷取結果',
    'Clear saved crawl results',
    'セーブしたクロール結果をクリアします',
    '저장된 긁어오기 결과 비우기',
  ],
  _数据清除完毕: [
    '数据清除完毕',
    '資料清除完畢',
    'Data cleared',
    'クリアされたデータ',
    '데이터가 비워졌습니다',
  ],
  _已跳过n个文件: [
    '已跳过 {} 个文件',
    '已跳過 {} 個檔案',
    '{} files skipped',
    '{} つのファイルをスキップしました',
    '{}개의 파일을 건너뛰었습니다',
  ],
  _不保存图片因为宽高: [
    '{} 没有被保存，因为它的宽高不符合设定。',
    '{} 並未儲存，因為它的寬高不符合設定。',
    '{} was not saved because its width and height do not match the settings.',
    '{} は幅と高さが設定に合わないため、保存されていません。',
    '{} 너비와 높이가 설정에 맞지 않아, 저장되지 않았습니다.',
  ],
  _显示下载面板: [
    '显示下载面板 (Alt + X)',
    '顯示下載面板 (Alt + X)',
    'Show download panel (Alt + X)',
    'ダウンロードパネルを表示 (Alt + X)',
    '다운로드 패널 보이기 (Alt + X)',
  ],
  _保存: ['保存', '儲存', 'Save', '保存', '저장'],
  _加载: ['加载', '載入', 'Load', 'ロード', '불러오기'],
  _保存命名规则提示: [
    '保存命名规则，最多 20 个',
    '儲存命名規則，最多 20 個',
    'Save naming rule, up to 20',
    '命名規則を保存します。最大 20 個まで',
    '명명 규칙 저장, 최대 20개',
  ],
  _已保存命名规则: [
    '已保存命名规则',
    '已儲存命名規則',
    'Naming rule saved',
    '命名規則を保存しました',
    '명명 규칙이 저장되었습니다.',
  ],
  _命名: ['命名', '命名', 'Name', '命名', '이름'],
  _无损: ['无损', '無損', 'Lossless', 'ロスレス', '무손실'],
  _文件名长度限制: [
    '文件名<span class="key">长度</span>限制',
    '檔案名稱<span class="key">長度</span>限制',
    'File name <span class="key">length</span> limit',
    'ファイル名の長さ制限',
    '파일명 <span class="key">길이</span> 제한',
  ],
  _导出csv: [
    '导出 CSV 文件',
    '匯出 CSV 檔',
    'Export CSV file',
    'CSV ファイルをエクスポート',
    'CSV 파일 내보내기',
  ],
  _导出抓取结果: [
    '导出抓取结果',
    '匯出擷取結果',
    'Export results',
    'クロール結果をエクスポート',
    '결과 내보내기',
  ],
  _导入抓取结果: [
    '导入抓取结果',
    '匯入擷取結果',
    'Import results',
    'クロール結果をインポート',
    '결과 불러오기',
  ],
  _导入成功: [
    '导入成功',
    '匯入成功',
    'Import successfully',
    'インポート成功',
    '가져오기 성공',
  ],
  _导出成功: [
    '导出成功',
    '匯出成功',
    'Export successfully',
    'エクスポート成功',
    '내보내기 성공',
  ],
  _图片尺寸: [
    '图片<span class="key">尺寸</span>',
    '圖片<span class="key">尺寸</span>',
    'Image <span class="key">size</span>',
    '画像<span class="key">サイズ</span>',
    '이미지 <span class="key">크기</span>',
  ],
  _图片尺寸2: [
    '图片尺寸',
    '圖片尺寸',
    'Image size',
    '画像サイズ',
    '이미지 크기',
  ],
  _原图: ['原图', '原圖', 'Original', 'Original', '원본'],
  _普通: ['普通', '普通', 'Regular', 'Regular', '레귤러'],
  _小图: ['小图', '小圖', 'Small', 'Small', '스몰'],
  _方形缩略图: [
    '方形缩略图',
    '方形縮圖',
    'Square thumbnail',
    'Square thumbnail',
    '정사각형 썸네일',
  ],
  _导出: ['导出', '匯出', 'Export', 'エクスポート', '내보내기'],
  _导入: ['导入', '匯入', 'Import', 'インポート', '불러오기'],
  _清除: ['清除', '清除', 'Clear', 'クリア', '비우기'],
  _导入下载记录: [
    '导入下载记录',
    '匯入下載紀錄',
    'Import download record',
    'ダウンロード記録をインポート',
    '다운로드 기록 불러오기',
  ],
  _完成: ['完成', '完成', 'Completed', '完了', '완료됨'],
  _日期格式: [
    '日期和时间<span class="key">格式</span>',
    '日期和時間<span class="key">格式</span>',
    'Date and time <span class="key">format</span>',
    '日付と時刻の書式',
    '날짜 및 시간 <span class="key">형식</span>',
  ],
  _日期格式提示: [
    '你可以使用以下标记来设置日期和时间格式。这会影响命名规则里的 {date} 和 {task_date}。<br>对于时间如 2021-04-30T06:40:08',
    '你可以使用以下標記來設定日期和時間格式。這會影響命名規則裡的 {date} 和 {task_date}。<br>對於資料如：2021-04-30T06:40:08。',
    'You can use the following notation to set the date and time format. This will affect {date} and {task_date} in the naming rules. <br>For time such as 2021-04-30T06:40:08',
    '以下のタグを使用して日時と時刻の書式を設定することができます。 これは命名規則の {date} と {task_date} に影響します。 <br> 例：2021-04-30T06:40:08',
    '다음 표기법을 사용하여 날짜 및 시간 형식을 설정할 수 있습니다.<br>이것은 명명 규칙에 있는 {date}와 {task_date}에 영향을 미칩니다.<br>예: 2021-04-30T06:40:08',
  ],
  _命名标记taskDate: [
    '本次任务抓取完成时的时间。例如：2020-10-21',
    '本次工作擷取完成時的時間。例如：2020-10-21。',
    'The time when the task was crawl completed. For example: 2020-10-21',
    'この作業のクロールが完了した時刻です。 例：2020-10-21',
    '긁어오기 작업을 완료한 날짜입니다. 예: 2020-10-21',
  ],
  _自动检测: ['自动检测', '自動偵測', 'Auto', '自動検出', '자동'],
  _变更语言后刷新页面的提示: [
    '更换语言后，请刷新页面。',
    '變更語言後，請重新整理頁面。',
    'Please refresh the page after changing the language.',
    '言語を変更した後は、ページを更新してください。',
    '언어 변경 후, 페이지를 새로고침 해주세요.',
  ],
  _公开: ['公开', '公開', 'Public', '公開', '공개'],
  _不公开: ['不公开', '非公開', 'Private', '非公開', '비공개'],
  _已收藏: ['已收藏', '已收藏', 'Bookmarked', 'ブックマークした', '북마크됨'],
  _已收藏带参数: [
    '已收藏 {}',
    '已收藏 {}',
    'Bookmarked {}',
    'ブックマークした {}',
    '북마크된 {}',
  ],
  _未收藏: [
    '未收藏',
    '未收藏',
    'Not bookmarked',
    'ブックマークされていない',
    '북마크되지 않음',
  ],
  _下载之后收藏作品: [
    '下载之后<span class="key">收藏</span>作品',
    '下載之後<span class="key">收藏</span>作品',
    '<span class="key">Bookmark</span> works after downloading',
    'ダウンロードした作品をブックマークする',
    '다운로드 후 작품 <span class="key">북마크</span>',
  ],
  _下载之后收藏作品的提示: [
    '下载文件之后，自动收藏这个作品。',
    '下載檔案之後，自動收藏這個作品。',
    'After you download a file, the downloader will automatically bookmark the work.',
    'ダウンロード後、作品は自動的にブックマークされます。',
    '파일을 다운로드하면, 자동으로 작품을 북마크합니다.',
  ],
  _收藏设置: [
    '下载器的<span class="key">收藏</span>按钮 (✩)',
    '下載器的<span class="key">收藏</span>按鈕 (✩)',
    `Downloader's <span class="key">bookmark</span> button (✩)`,
    'ダウンローダーの<span class="key">ブックマーク</span>ボタン (✩)',
    '다운로더의 <span class="key">북마크</span> 버튼 (☆)',
  ],
  _添加tag: ['添加标签', '加入標籤', 'Add tag', 'タグを追加', '태그 추가'],
  _不添加tag: [
    '不添加标签',
    '不加入標籤',
    "Don't add tag",
    'タグなし',
    '태그 추가하지 않기',
  ],
  _用户阻止名单: [
    '用户<span class="key">阻止</span>名单',
    '使用者<span class="key">阻止</span>名單',
    'User <span class="key">block</span> list',
    'ユーザーブロックリスト',
    '유저 <span class="key">차단</span> 목록',
  ],
  _用户阻止名单的说明: [
    '不下载这些用户的作品。需要输入用户 id。如果有多个用户 id，使用英文逗号,分割。',
    '不下載這些使用者的作品。需要輸入使用者 id。若有多個使用者 id，使用半形逗號（,）分隔。',
    'The works of these users will not be downloaded. Need to type the user ID. If there are multiple user ID, use comma (,) separated.',
    'これらのユーザーの作品はダウンロードしません。ユーザー ID が必要です。複数のユーザ ID は "," で区切ってください。',
    '이 유저들의 작품은 다운로드되지 않습니다. 유저 ID를 입력해야 합니다.<br>여러 유저 ID가 있는 경우 쉼표(,)로 구분합니다.',
  ],
  _全部: ['全部', '全部', 'All', '全部', '전부'],
  _任一: ['任一', '任一', 'One', '何れか', '하나만'],
  _颜色主题: [
    '颜色<span class="key">主题</span>',
    '色彩<span class="key">主題</span>',
    'Color <span class="key">theme</span>',
    'カラーテーマ',
    '<class key="key">테마</span>',
  ],
  _管理设置: [
    '管理<span class="key">设置</span>',
    '管理<span class="key">設定</span>',
    'Manage <span class="key">settings</span>',
    '<span class="key">設定</span>の管理',
    '<span class="key">설정</span> 관리',
  ],
  _导出设置: [
    '导出设置',
    '匯出設定',
    'Export settings',
    'エクスポート設定',
    '내보내기',
  ],
  _导入设置: [
    '导入设置',
    '匯入設定',
    'Import settings',
    'インポート設定',
    '불러오기',
  ],
  _重置设置: [
    '重置设置',
    '重設設定',
    'Reset settings',
    'リセット設定',
    '설정 초기화',
  ],
  _日均收藏数量: [
    '日均收藏数量',
    '日均收藏數量',
    'Average number of daily bookmarks',
    '1 日の平均ブックマーク数',
    '일일 평균 북마크 수',
  ],
  _日均收藏数量的提示: [
    '你可以设置作品的平均每日收藏数量。满足条件的作品会被下载。',
    '您可以設定作品的平均每日收藏數量。滿足條件的作品會被下載。',
    'You can set the average daily bookmarks number of works. Works that meet the conditions will be downloaded.',
    '作品の 1 日の平均ブックマーク数を設定することができます。条件を満した作品はダウンロードされます。',
    '작품의 일일 평균 북마크 수를 설정할 수 있습니다. 조건을 만족한 작품은 다운로드됩니다.',
  ],
  _下载用户列表: [
    '下载用户列表',
    '下載使用者列表',
    'Download users list',
    'ユーザーリストのダウンロード',
    '유저 목록 다운로드',
  ],
  _手动选择作品: [
    '手动选择作品',
    '手動選擇作品',
    'Manually select',
    '手動で作品を選ぶ',
    '수동 선택',
  ],
  _抓取选择的作品: [
    '抓取选择的作品',
    '擷取選擇的作品',
    'Crawl selected works',
    '選ばれた作品をクロール',
    '선택된 작품 긁어오기',
  ],
  _抓取选择的作品2: [
    '抓取选择的作品 {}',
    '擷取選擇的作品 {}',
    'Crawl selected works {}',
    '選ばれた作品をクロール {}',
    '선택된 작품 긁어오기 {}',
  ],
  _清空选择的作品: [
    '清空选择的作品',
    '清空選擇的作品',
    'Clear selected works',
    '選んだ作品をクリアします',
    '선택된 작품 비우기',
  ],
  _暂停选择: [
    '暂停选择',
    '暫停選擇',
    'Pause select',
    '選択を一時停止',
    '선택 일시중지',
  ],
  _继续选择: [
    '继续选择',
    '繼續選擇',
    'Continue select',
    '選択を続ける',
    '선택 이어하기',
  ],
  _离开页面前提示选择的作品未抓取: [
    '选择的作品尚未抓取。现在离开此页面会导致你选择的作品被清空。',
    '選擇的作品尚未擷取。現在離開此頁面會導致您選擇的作品被清空。',
    'The selected work has not been crawled. Leaving this page now will cause your selected work to be cleared.',
    '選ばれた作品はまだクロールしていません。今このページを離れると、選ばれた作品がクリアされます。',
    '선택된 작품을 아직 긁어오지 않았습니다. 지금 현재 페이지를 떠나면 선택된 작품이 비워집니다.',
  ],
  _排除了所有作品类型: [
    '排除了所有作品类型',
    '排除了所有作品類型',
    'Excluded all work types',
    'すべての作品種類を除外しました',
    '모든 작품 유형 제외',
  ],
  _为作品建立单独的文件夹: [
    '为<span class="key">每个</span>作品建立单独的文件夹',
    '為<span class="key">每個</span>作品建立單獨的資料夾',
    'Create a separate folder for <span class="key">each</span> work',
    '作品ごとに別フォルダを作成',
    '작품마다 <span class="key">별도</span>의 디렉토리 생성',
  ],
  _为作品建立单独的文件夹说明: [
    '这里应该使用 {id_num} 代替 {id}',
    '這裡應該使用 {id_num} 代替 {id}',
    'Here {id_num} should be used instead of {id}',
    'ここでは、{id} の代わりに {id_num} を使用する必要があります',
    '여기서는 {id}대신 {id_num}을 사용해야 합니다',
  ],
  _文件数量大于: [
    '文件数量 >',
    '檔案數量 >',
    'Number of files >',
    'ファイル数 >',
    '파일 수 >',
  ],
  _保存用户头像: [
    '保存用户头像',
    '儲存使用者頭貼',
    'Save user avatar',
    'ユーザーアイコンの保存',
    '유저 프로필 이미지 저장',
  ],
  _保存用户封面: [
    '保存用户封面',
    '儲存使用者封面',
    'Save user cover',
    'ユーザーカバーの保存',
    '유저 커버 저장',
  ],
  _待处理: ['待处理', '待處理', 'Pending', '処理待ち', '처리 대기'],
  _超出最大页码: [
    '超出最大页码：',
    '超出最大頁碼：',
    'Maximum page number exceeded:',
    '最大ページ数を超えました：',
    '최대 페이지 번호 초과:',
  ],
  _针对特定用户屏蔽tag: [
    '针对特定用户屏蔽<span class="key">标签</span>',
    '針對特定使用者排除<span class="key">標籤</span>',
    'Block <span class="key">tags</span> for specific users',
    '特定のユーザーに対して<span class="key">タグ</span>をブロック',
    '특정 유저에 대한 차단 <span class="key">태그</span>',
  ],
  _展开收起: [
    '展开/收起',
    '展開/摺疊',
    'Expand/Collapse',
    '展開/折りたたみ',
    '확장/축소',
  ],
  _展开: ['展开', '展開', 'Expand', '展開', '확장'],
  _收起: ['收起', '摺疊', 'Collapse', '折りたたみ', '축소'],
  _把r18作品存入指定的文件夹里: [
    '把 <span class="key">R-18(G)</span> 作品存入指定的文件夹里',
    '把 <span class="key">R-18(G)</span> 作品存入指定的資料夾裡',
    'Save the <span class="key">R-18(G)</span> works in the designated folder',
    '<span class="key">R-18(G)</span> の作品を指定のフォルダに入れる',
    '<span class="key">R-18(G)</span> 작품을 지정된 디렉토리에 저장',
  ],
  _必填项不能为空: [
    '必填项不能为空',
    '必填項不能為空',
    'Required fields cannot be empty',
    '必須フィールドが入力されていません',
    '필수 입력 항목은 비워둘 수 없습니다',
  ],
  _用户ID必须是数字: [
    '用户 ID 必须是数字',
    '使用者 ID 必須是數字',
    'User ID must be a number',
    'ユーザー ID は数字です',
    '유저 ID는 숫자만 허용합니다',
  ],
  _必须是数字: [
    '必须是数字',
    '必須是數字',
    'Number',
    '数字でなければなりません',
    '숫자만 허용',
  ],
  _tag用逗号分割: [
    '多个标签使用英文逗号,分割',
    '多個標籤使用半形逗號（,）分隔',
    'Multiple tags use comma (,) split',
    '複数のタグはカンマ「,」で区切ってください',
    '여러 태그는 쉼표(,)로 구분합니다.',
  ],
  _添加: ['添加', '新增', 'Add', '追加', '추가'],
  _取消: ['取消', '取消', 'Cancel', 'キャンセル', '취소'],
  _更新: ['更新', '更新', 'Update', '更新', '업데이트'],
  _删除: ['删除', '刪除', 'Delete', '削除', '제거'],
  _添加成功: [
    '添加成功',
    '新增成功',
    'Added successfully',
    '追加されました',
    '성공적으로 추가되었습니다.',
  ],
  _更新成功: [
    '更新成功',
    '更新成功',
    'update completed',
    '更新成功',
    '업데이트에 성공하였습니다.',
  ],
  _在作品缩略图上显示放大按钮: [
    '在作品缩略图上显示<span class="key">放大</span>按钮',
    '在作品縮圖上顯示<span class="key">放大</span>按鈕',
    'Show <span class="key">zoom</span> button on thumbnail',
    '作品のサムネイルに<span class="key">拡大</span>ボタンを表示',
    '썸네일에 <span class="key">확대</span> 버튼 표시',
  ],
  _在作品缩略图上显示下载按钮: [
    '在作品缩略图上显示<span class="key">下载</span>按钮',
    '在作品縮圖上顯示<span class="key">下載</span>按鈕',
    'Show <span class="key">download</span> button on thumbnail',
    '作品のサムネイルに<span class="key">ダウンロード</span>ボタンを表示',
    '썸네일에 <span class="key">다운로드</span> 버튼 표시',
  ],
  _已发送下载请求: [
    '已发送下载请求',
    '已傳送下載請求',
    'Download request sent',
    'ダウンロードリクエストを送信しました',
    '다운로드 요청 전송',
  ],
  _HowToUse: [
    '点击页面右侧的蓝色按钮可以打开下载器面板。',
    '點選頁面右側的藍色按鈕可以開啟下載器面板。',
    'Click the blue button on the right side of the page to open the downloader panel.',
    'ページ右側の青いボタンをクリックすると、ダウンローダーパネルが開きます。',
    '페이지 오른쪽에 있는 파란색 버튼을 클릭하면 다운로드 패널이 열립니다.',
  ],
  _我知道了: ['我知道了', '我知道了', 'OK', '分かりました', '확인'],
  _背景图片: [
    '<span class="key">背景</span>图片',
    '<span class="key">背景</span>圖片',
    '<span class="key">Background</span> image',
    '<span class="key">背景</span>画像',
    '<span class="key">배경</span> 이미지',
  ],
  _选择文件: [
    '选择文件',
    '選擇檔案',
    'Select a file',
    'ファイルを選択',
    '파일 선택',
  ],
  _不透明度: ['不透明度', '不透明度', 'Opacity', '不透明度', '투명도'],
  _对齐方式: ['对齐方式', '對齊方式', 'Alignment', '揃え方式', '정렬'],
  _顶部: ['顶部', '頂部', 'top', '上揃え', '상단'],
  _居中: ['居中', '居中', 'center', '中央揃え', '중앙'],
  _根据作品类型自动建立文件夹: [
    '根据作品<span class="key">类型</span>自动建立文件夹',
    '根據作品<span class="key">類型</span>自動建立資料夾',
    'Create folders based on the <span class="key">type</span> of work',
    '作品種類に応じてフォルダを自動作成',
    '작품 <span class="key">유형</span>에 따라 자동으로 디렉토리 생성',
  ],
  _使用第一个匹配的tag建立文件夹: [
    '使用第一个匹配的<span class="key">标签</span>建立文件夹',
    '使用第一個符合的<span class="key">標籤</span>建立資料夾',
    'Create a folder with the first matched <span class="key">tag</span>',
    '最初の一致するタグにフォルダを作成',
    '첫 번째 일치하는 <span class="key">태그</span>로 디렉토리 생성',
  ],
  _使用匹配的tag建立文件夹的说明: [
    '如果作品的标签列表里含有用户设置的标签，就会使用这个标签建立文件夹（仅限第一个）',
    '如果作品的標籤列表裡含有使用者設定的標籤，就會使用這個標籤建立資料夾（僅限第一個）',
    'If the tag list of the work contains a tag set by the user, this tag will be used to create a folder (only the first one)',
    '作品のタグリストにユーザーが設定したタグが含まれている場合、そのタグを使用してフォルダが作成されます。(最初の1つだけ)',
    '작품의 태그에 유저가 설정한 태그가 포함되어 있다면, 태그를 사용하여 디렉토리를 생성합니다. (첫 번째 태그만 해당)',
  ],
  _全年龄: ['全年龄', '全年齡', 'All ages', '全年齢', '전체 연령'],
  _没有符合条件的结果: [
    '没有符合条件的结果',
    '沒有符合條件的結果',
    'There are no eligible results',
    '対象となる結果はありません',
    '조건에 부합하는 결과가 없습니다',
  ],
  _收藏: ['收藏', '收藏', 'Bookmark', 'ブックマーク', '북마크'],
  _已加入收藏: [
    '已加入收藏',
    '已加入收藏',
    'Bookmarked',
    'ブックマークした',
    '북마크됨',
  ],
  _全屏查看: [
    '全屏',
    '全螢幕',
    'Full screen view',
    '全画面表示',
    '전체 화면 보기',
  ],
  _抓取id区间: [
    '抓取 id 区间',
    '擷取 id 區間',
    'Crawl id range',
    'id 範囲をクロール',
    'ID 범위 긁어오기',
  ],
  _抓取id区间说明: [
    '你可以设置一个作品 id 范围，抓取此范围内的所有作品（包含开始和结束的 id）。\n注意：如果一次任务中产生的抓取结果数量太多，可能会导致页面崩溃。',
    '你可以設定一個作品 id 範圍，擷取此範圍內的所有作品（包含開始和結束的 id）。\n注意：如果一次任務中產生的擷取結果數量太多，可能會導致頁面崩潰。',
    'You can set a range of work id and grab all works in this range (including the begin and end id). \nNote: If the number of crawling results in a task is too much, it may cause the page to crash.',
    '作品 id の範囲を設定し、その範囲内のすべての作品をクロールすることができます。「開始 id と終了 id を含む」\n注意：1 つのタスクであまりにも多くのクロール結果を生成すると、ページがクラッシュする可能性があります。',
    '작품 ID 범위를 설정할 수 있습니다. 이 범위 내의 모든 작품 (시작과 끝 ID 포함).\n참고: 작업의 긁어오기 결과가 너무 많으면 페이지가 충돌할 수 있습니다.',
  ],
  _抓取id区间起点: [
    '请输入开始的 id',
    '請輸入開始的 id',
    'Please type in the beginning id',
    '開始 id を入力してください',
    '시작 ID를 입력해주세요',
  ],
  _抓取id区间终点: [
    '请输入结束的 id',
    '請輸入結束的 id',
    'Please type  in the ending id',
    '終了 id を入力してください',
    '끝 ID를 입력해주세요',
  ],
  _选项卡切换方式: [
    '<span class="key">选项卡</span>切换方式',
    '<span class="key">頁籤</span>切換方式',
    'How to switch <span class="key">tabs</span>',
    'タブ切り替え方式',
    '<span class="key">탭</span> 전환 방식',
  ],
  _鼠标经过: [
    '鼠标经过',
    '滑鼠經過',
    'Mouse over',
    'マウスオーバー',
    '마우스 올리기',
  ],
  _鼠标点击: [
    '鼠标点击',
    '滑鼠點選',
    'Mouse click',
    'マウスクリック',
    '마우스 클릭',
  ],
  _在序号前面填充0: [
    '在序号前面<span class="key">填充 0</span>',
    '在序號前面<span class="key">填充 0</span>',
    '<span class="key">Add 0</span> in front of the serial number',
    'シリアル番号の前に 0 を記入',
    '일련번호 앞 <span class="key">0 채우기</span>',
  ],
  _序号总长度: [
    '序号总长度',
    '序號總長度',
    'Total length of serial number',
    'シリアル番号の全長',
    '일련번호 전체 길이',
  ],
  _完全一致: ['完全一致', '完全一致', 'Perfect match', '完全一致', '완전 일치'],
  _部分一致: ['部分一致', '部分一致', 'Partial match', '部分一致', '부분 일치'],
  _位置: ['位置', '位置', 'Position', '位置', '위치'],
  _左: ['左', '左', 'Left', '左', '왼쪽'],
  _右: ['右', '右', 'Right', '右', '오른쪽'],
  _多图作品只下载前几张图片: [
    '多图作品只下载<span class="key">前几张</span>图片',
    '多圖作品只下載<span class="key">前幾張</span>圖片',
    'Multi-image works only download the <span class="key">first few</span> images',
    'マルチ作品は最初の何枚の画像のみをダウンロードする',
    '여러 이미지 작품은 <span class="key">처음 몇 개</span>의 이미지만 다운로드합니까',
  ],
  _多图作品的图片数量上限: [
    '多图作品的图片<span class="key">数量</span>上限',
    '多圖作品的圖片<span class="key">數量</span>上限',
    '<span class="key">Maximum number</span> of images for multi-image works',
    'マルチ作品の最大画像数',
    '여러 이미지 작품의 <span class="key">최대 수</sapn>',
  ],
  _超出此限制的多图作品不会被下载: [
    '超出此限制的多图作品不会被下载',
    '不會下載超出此限制的多圖作品',
    'Multi-image works exceeding this limit will not be downloaded',
    'この制限を超えたマルチ作品はダウンロードされません',
    '이 제한을 초과하는 여러 이미지 작품은 다운로드되지 않습니다.',
  ],
  _在搜索页面添加快捷搜索区域: [
    '在搜索页面添加快捷<span class="key">搜索</span>区域',
    '在搜尋頁面新增快速<span class="key">搜尋</span>區域',
    'Add a quick <span class="key">search</span> area on the search page',
    '検索ページにクイック検索領域を追加します',
    '검색 페이지에 빠른 <span class="key">검색</span> 영역 추가',
  ],
  _保存作品的元数据: [
    '保存作品的<span class="key">元数据</span>',
    '儲存作品的<span class="key">元資料</span>',
    'Save the <span class="key">metadata</span> of the work',
    '作品のメタデータを保存する',
    '작품 <span class="key">메타데이터</span> 저장',
  ],
  _保存作品的元数据说明: [
    '为每个作品建立一个 txt 文件保存它的元数据',
    '為每個作品建立一個 txt 檔案儲存它的元資料',
    'Create a txt file for each work to save its metadata',
    '作品ごとに txt ファイルを作成して、メタデータを保存します',
    '각 작품에 대한 메타데이터를 저장하는 txt 파일 생성',
  ],
  _在不同的页面类型中使用不同的命名规则: [
    '在不同的页面类型中使用<span class="key">不同</span>的命名规则',
    '在不同的頁面類型中使用<span class="key">不同</span>的命名規則',
    'Use <span class="key">different</span> naming rules in different page types',
    'ページの種類によって異なる命名規則を使用',
    '페이지 유형에 따라 <span class="key">다른</span> 명명 규칙 사용',
  ],
  _显示高级设置: [
    '显示<span class="key">高级</span>设置',
    '顯示<span class="key">進階</span>設定',
    'Show <span class="key">advanced</span> settings',
    '詳細設定を表示する',
    '<span class="key">고급</span> 설정 보기',
  ],
  _显示高级设置说明: [
    '被隐藏的设置仍然会发挥作用',
    '被隱藏的設定仍然會發揮作用',
    'Hidden settings will still work',
    '隠していた設定がそのまま機能する',
    '숨겨진 설정은 계속 작동합니다.',
  ],
  _状态码为0的错误提示: [
    '下载时发生错误，状态码为 0，请求未成功。可能的原因：<br><br>1. 系统磁盘的剩余空间可能不足（建议剩余空间大于 4GB）。请尝试清理系统磁盘空间，然后重新启动浏览器，继续未完成的下载。<br><br>2. 网络错误。可能是网络代理导致的问题。如果你使用 Nginx 或者 Apache 反代理访问 pixiv，请换成梯子。',
    '下載時發生錯誤，狀態碼為 0，請求未成功。可能的原因：<br><br>1. 系統磁碟的剩餘空間可能不足（建議剩餘空間大於 4GB）。請嘗試清理系統磁碟空間，然後重新啟動瀏覽器，繼續未完成的下載。<br><br>2. 網路錯誤。可能是網路代理導致的問題。',
    'An error occurred while downloading, the status code is 0, and the request was unsuccessful. Possible reasons: <br><br>1. The remaining space of the system disk may be insufficient (it is recommended that the remaining space be greater than 4GB). Please try to clear the system disk space, and then restart the browser to continue the unfinished download. <br><br>2. Network error. It may be a problem caused by a network proxy.',
    'ダウンロード中にエラーが発生し、ステータスコードは0で、リクエストは失敗しました。 考えられる理由：<br> <br> 1。 システムディスクの残りのスペースが不足している可能性があります（残りのスペースは4GBを超えることをお勧めします）。 システムのディスク領域をクリアしてから、ブラウザを再起動して、未完了のダウンロードを続行してください。 <br> <br> 2。 ネットワークエラー。 ネットワークプロキシが原因の問題である可能性があります。',
    '다운로드 중 오류가 발생했으며, 상태 코드가 0이고 요청에 실패했습니다. 가능한 원인: <br><br>1. 시스템 디스크의 남은 공간이 부족할 수 있습니다(남은 공간은 4GB보다 큰 것이 좋습니다). 시스템 디스크 공간을 비운 다음 브라우저를 다시 시작하여 완료되지 않은 다운로드를 계속해주세요. <br><br>2. 네트워크 오류. 네트워크 프록시로 인한 문제일 수 있습니다.',
  ],
  _下载完成后显示通知: [
    '下载完成后显示<span class="key">通知</span>',
    '下載完成後顯示<span class="key">通知</span>',
    'Show <span class="key">notification</span> after download is complete',
    'ダウンロードが完了した後に通知を表示する',
    '다운로드가 완료되면 <span class="key">알림</span> 표시',
  ],
  _高亮显示关键字: [
    '<span class="key">高亮</span>显示关键字',
    '<span class="key">標明</span>顯示關鍵字',
    '<span class="key">Highlight</span> keywords',
    'キーワードを強調表示',
    '<span class="key">강조</span> 키워드 표시',
  ],
  _抓取标签列表: [
    '抓取标签列表',
    '擷取標籤列表',
    'Crawl a list of tags',
    'タグのリストをクロール',
    '태그 긁어오기',
  ],
  _抓取标签列表的输入框提示: [
    '请输入你要抓取的标签列表。多个标签之间使用换行分割',
    '請輸入你要擷取的標籤列表。多個標籤之間使用換行分隔',
    'Please type the list of tags you want to crawl. Use line breaks between multiple tags',
    'クロールしたいタグのリストを入力してください。 複数のタグを改行で分割',
    '긁어올 태그를 입력해주세요. 여러 태그는 줄 바꿈 사용',
  ],
  _抓取标签列表的文件夹提示: [
    '在抓取标签列表时，你可以使用 {p_tag} 或者 {p_title} 标记获取当前抓取的标签，并用来建立文件夹。例如：{p_tag}/{id}',
    '在擷取標籤列表時，你可以使用 {p_tag} 或者 {p_title} 標記獲取目前擷取的標籤，並用來建立資料夾。例如：{p_tag}/{id}',
    'When crawling the tag list, you can use {p_tag} or {p_title} tags to get the tags currently crawled and use them to create folders. For example: {p_tag}/{id}',
    'タグリストをクロールする時に、 {p_tag} や {p_title}を使用すると、現在クロールされているタグを取得し、それらを使ってフォルダを作成することができます。例：{p_tag}/{id}',
    '태그를 긁어올 때 {p_tag} 또는 {p_title} 태그를 사용하여, 긁어온 태그로 디렉토리를 생성할 수 있습니다. 예: {p_tag}/{id}',
  ],
  _停止抓取标签列表: [
    '停止抓取标签列表',
    '停止擷取標籤列表',
    'Stop crawling the list of tags',
    'タグリストのクロールを停止',
    '태그 긁어오기 정지',
  ],
  _等待下载的标签: [
    '等待下载的标签',
    '等待下載的標籤',
    'Tags waiting to be downloaded',
    'ダウンロード待ちのタグ',
    '다운로드 대기 중인 태그',
  ],
  _你确定要停止抓取吗: [
    '你确定要停止抓取吗？',
    '確定要停止擷取嗎？',
    'Are you sure you want to stop crawling?',
    '本当にクロールをやめたいのか',
    '긁어오기를 중지하시겠습니까?',
  ],
  _只能在搜索页面使用: [
    '只能在搜索页面使用',
    '只能在搜尋頁面使用',
    'Can only be used on the search page',
    '検索ページでのみ使用できます',
    '검색 페이지에서만 사용 가능',
  ],
  _自动导出抓取结果: [
    '自动<span class="key">导出</span>抓取结果',
    '自動<span class="key">匯出</span>擷取結果',
    'Automatically <span class="key">export</span> crawl results',
    'クロール結果の自動エクスポート',
    '자동으로 긁어오기 결과 <span class="key">내보내기</span>',
  ],
  _抓取结果: [
    '抓取结果',
    '擷取結果',
    'Crawl results',
    'クロール結果',
    '긁어오기 결과',
  ],
  _文件格式: [
    '文件格式',
    '檔案格式',
    'File format',
    'ファイル形式',
    '파일 형식',
  ],
  _格式: ['格式', '格式', 'Format', '形式', '형식'],
  _预览作品: [
    '<span class="key">预览</span>作品',
    '<span class="key">預覽</span>作品',
    '<span class="key">Preview</span> works',
    '作品のプレビュー',
    '작품 <span class="key">미리보기</span>',
  ],
  _点击鼠标左键可以关闭预览图: [
    '点击鼠标左键可以关闭预览图',
    '點選滑鼠左鍵可以關閉預覽圖',
    'Click the left mouse button to close the preview',
    'マウスの左クリックでプレビュー画像を閉じる',
    '마우스 왼쪽 버튼을 클릭하면 미리보기를 닫습니다',
  ],
  _尺寸: ['尺寸', '尺寸', 'Size', 'サイズ', '크기'],
  _允许鼠标停留在预览图上: [
    '允许鼠标停留在预览图上',
    '允許滑鼠停留在預覽圖上',
    'Allow the mouse to stay on the preview image',
    'プレビュー画像の上にマウスを置くことができます',
    '마우스가 미리보기 이미지 위에서 유지되도록 허용',
  ],
  _点击预览图时下载作品: [
    '点击预览图时下载作品',
    '點選預覽圖時下載作品',
    'Download the work when you click on the preview',
    'プレビュー画像をクリックするとその作品がダウンロードされます',
    '미리보기 이미지를 클릭하면 작품 다운로드',
  ],
  _转换动图时页面被隐藏的提示: [
    '这个标签页正在转换动图。如果这个标签页被隐藏了，转换速度可能会变慢。',
    '這個標籤頁正在轉換動圖。如果這個標籤頁被隱藏了，轉換速度可能會變慢。',
    'This tab page is converting ugoira. If this tab page is hidden, the conversion speed may slow down.',
    'このタブページはうごイラを変換しています。 このタブを非表示にすると、変換速度が低下する場合があります。',
    '이 탭은 움직이는 일러스트를 변환하는 중입니다.이 탭이 숨겨지면 변환 속도가 느려질 수 있습니다.',
  ],
  _原始尺寸: [
    '原始尺寸',
    '原始尺寸',
    'Original size',
    'オリジナルサイズ',
    '원본 크기',
  ],
  _增强: ['增强', '增強', 'Enhance', '強化機能', '향상'],
  _长按右键显示大图: [
    '在缩略图上长按鼠标右键时显示<span class="key">大图</span>',
    '在縮圖上長按滑鼠右鍵時顯示<span class="key">大圖</span>',
    'Long press the right mouse button on the thumbnail to display the <span class="key">large image</span>',
    'サムネイルでマウスの右ボタンを長押しすると、大きな画像が表示されます。',
    '썸네일을 마우스 오른쪽 버튼으로 클릭했을 때 <span class="key">큰 이미지</span> 표시',
  ],
  _鼠标滚轮切换图片: [
    '预览多图作品时，可以使用鼠标滚轮切换图片。',
    '預覽多圖作品時，可以使用滑鼠滾輪切換圖片。',
    'When previewing multi-image works, you can use the mouse wheel to switch images.',
    '複数画像をプレビューする際に、マウスホイールを使って画像を切り替えることができます。',
    '여러 이미지 작품을 미리 볼 때, 마우스 휠을 사용하여 이미지를 전환할 수 있습니다.',
  ],
  _whatisnew: [
    `当抓取作品发生429 错误时，下载器会重新抓取这个作品。`,
    `當抓取作品發生429 錯誤時，下載器會重新抓取這個作品。`,
    `When a 429 error occurs when crawling a work, the downloader will re-crawl the work.`,
    `作品のクロール時に429エラーが発生した場合、ダウンローダは作品を再クロールします。`,
    `작품을 크롤링할 때 429 오류가 발생하면 다운로더가 작품을 다시 크롤링합니다.`,
  ],
  _等待时间: ['等待时间', '等待時間', 'Waiting time', '待ち時間', '대기 시간'],
  _格式错误: [
    '格式错误',
    '格式錯誤',
    'Format error',
    'フォーマットエラー',
    '형식 오류',
  ],
  _下载数量错误: [
    '下载的页数（作品）数量设置错误',
    '下載的頁數（作品）數量設定錯誤',
    'The number of downloaded pages (works) is set incorrectly',
    '下载页数（作品）设置不正确',
    '다운로드할 페이지 수(작품) 설정 오류',
  ],
  _默认下载多页: [
    '开始抓取, 如有多页，默认会下载全部。',
    '開始擷取，如有多頁，預設會下載全部。',
    'Start crawl, if there are multiple pages, the default will be downloaded.',
    'クロールを開始する、複数のページがある場合、デフォルトですべてをダウンロードされます。',
    '긁어오기를 시작합니다. 여러 페이지가 있으면 기본적으로 모두 다운로드됩니다.',
  ],
  _在Patreon赞助我: [
    '在 Patreon 赞助我',
    '在 Patreon 贊助我',
    'Become a patron',
    'Become a patron',
    'Become a patron',
  ],
  _赞助我: ['赞助我', '贊助我', 'Sponsor me', '支援する', '후원하기'],
  _赞助方式提示: [
    `非常感谢您的支持！<br>
    您可以在 Patreon 上赞助我：<br>
    <a href="https://www.patreon.com/xuejianxianzun" target="_blank">https://www.patreon.com/xuejianxianzun</a><br>
    中国大陆用户可以在“爱发电”上赞助我：<br>
    <a href="https://afdian.net/@xuejianxianzun" target="_blank">https://afdian.net/@xuejianxianzun</a><br>
    也可以扫描二维码：<br>
    <a href="https://github.com/xuejianxianzun/PixivBatchDownloader#%E6%94%AF%E6%8C%81%E5%92%8C%E6%8D%90%E5%8A%A9" target="_blank">在 Github 上查看二维码</a> 或者加入 QQ 群 675174717，在群文件里查看二维码。
    `,
    `非常感謝您的支持！<br>
    您可以在 Patreon 上贊助我：<br>
    <a href="https://www.patreon.com/xuejianxianzun" target="_blank">https://www.patreon.com/xuejianxianzun</a><br>
    中國大陸使用者可以在“愛發電”上贊助我：<br>
    <a href="https://afdian.net/@xuejianxianzun" target="_blank">https://afdian.net/@xuejianxianzun</a><br>
    也可以掃描行動條碼（QR Code）：<br>
    <a href="https://github.com/xuejianxianzun/PixivBatchDownloader#%E6%94%AF%E6%8C%81%E5%92%8C%E6%8D%90%E5%8A%A9" target="_blank">在 Github 上檢視行動條碼</a> 或者加入 QQ 群 675174717 檢視行動條碼。
    `,
    `Thank you very much for your support!<br>
    You can sponsor me on Patreon: <br>
    <a href="https://www.patreon.com/xuejianxianzun" target="_blank">https://www.patreon.com/xuejianxianzun</a>
    `,
    `ご支援してくださった皆様、本当にありがとうございました。<br>
    ご支援してくださった方は、以下の Patreon で：<br>
    <a href="https://www.patreon.com/xuejianxianzun" target="_blank"> https://www.patreon.com/xuejianxianzun </a>
    `,
    `지원해주셔서 정말 감사합니다!<br>
    Patreon에서 저를 후원해주세요<br>
    <a href="https://www.patreon.com/xuejianxianzun" target="_blank">https://www.patreon.com/xuejianxianzun</a>
    `,
  ],
  _替换方形缩略图以显示图片比例: [
    '替换方形<span class="key">缩略图</span>以显示图片比例',
    '替換方形<span class="key">縮圖</span>以顯示圖片比例',
    'Replace square <span class="key">thumbnails</span> to show image ratio',
    '正方形のサムネイルを置き換えて、画像のスケールを表示。',
    '이미지 종횡비를 표시하기 위해 정사각형 <span class="key">썸네일</span> 교체',
  ],
  _只有一个抓取结果时不建立文件夹: [
    '只有一个抓取结果时<span class="key">不建立</span>文件夹',
    '只有一個擷取結果時<span class="key">不建立</span>資料夾',
    '<span class="key">Do not create</span> a folder when there is only one crawl result',
    'クロール結果が１つのみの場合、フォルダを作成しない',
    '긁어오기 결과가 하나일 때 디렉토리 <span class="key">생성하지 않기</span>',
  ],
  _搜索页面页数限制: [
    '由于 pixiv 的限制，下载器最多只能抓取到第 {} 页。',
    '由於 pixiv 的限制，下載器最多只能擷取到第 {} 頁。',
    'Due to the limitation of pixiv, the downloader can only crawl up to the {}th page.',
    'pixiv の制限により、ダウンローダーは {} ページ目までしかクロールできません。',
    'pixiv 제한으로 인해 최대 {} 페이지까지만 다운로드 받을 수 있습니다.',
  ],
  _获取图片的宽高时出现错误: [
    '获取图片的宽高时出现错误：',
    '獲取圖片的寬高時出現錯誤：',
    'An error occurred while getting the width and height of the image:',
    '画像の幅と高さの取得中にエラーが発生しました：',
    '이미지의 너비를 가져오는 도중 오류가 발생했습니다:',
  ],
  _上限: ['上限', '上限', 'Upper limit', '上限', '상한'],
  _预览搜索结果的数量达到上限的提示: [
    '预览搜索结果的数量已经达到上限，剩余的结果不会显示。',
    '預覽搜尋結果的數量已經達到上限，剩餘的結果不會顯示。',
    'The number of preview search results has reached the upper limit, and the remaining results will not be displayed.',
    'プレビュー検索結果の数が上限に達し、残りの結果は表示されません。',
    '미리보기 검색 결과 수가 상한에 도달하여, 남은 결과는 표시되지 않습니다.',
  ],
  _新增命名标记: [
    '新增命名标记',
    '新增命名標記',
    'Add named tag',
    '名前付きタグを追加',
    '명명된 태그 추가',
  ],
  _自定义用户名: [
    '自定义<span class="key">用户名</span>',
    '自訂<span class="key">使用者名稱</span>',
    'Customize <span class="key">username</span>',
    'カスタムユーザー名',
    '사용자 정의 <span class="key">유저명</span>',
  ],
  _自定义用户名的说明: [
    `有些用户可能会改名，如果你想使用他原来的名字，你可以在这里手动设置他的名字。<br>
    你也可以为用户设置别名。<br>
    当你在命名规则中使用 {user} 标记时，下载器会优先使用你设置的名字。`,
    `有些使用者可能會改名，如果你想使用他原來的名字，你可以在這裡手動設定他的名字。<br>
    你也可以為使用者設定別名。<br>
    當你在命名規則中使用 {user} 標記時，下載器會優先使用你設定的名字。`,
    `Some users may change their name. If you want to use his original name, you can manually set his name here. <br>
    You can also set aliases for users. <br>
    When you use the {user} tag in the naming rule, the downloader will give priority to the name you set.`,
    `ユーザーによっては名前を変更する場合があります。元の名前を使いたい場合は、ここで名前を手動で設定することができます。<br>
    また、ユーザーの別名を設定することも可能です。<br>
    命名規則で {user} タグを使用すると、ダウンローダーは設定された名前を優先的に使用します。`,
    `일부 유저는 이름을 바꿀 수 있습니다. 만약 당신이 그의 원래 이름을 사용하고 싶다면, 당신은 여기에서 그의 이름을 수동으로 설정할 수 있습니다.<br>
    사용자의 별칭을 설정할 수도 있습니다. <br>
    명명 규칙에 {user} 태그를 사용할 때 다운로드더가 사용자 정의 유저명을 우선시합니다.`,
  ],
  _移除用户名中的at和后续字符: [
    '移除用户名中的 <span class="key">@</span> 和后续字符',
    '移除使用者名稱中的 <span class="key">@</span> 和後續字元',
    'Remove <span class="key">@</span> and subsequent characters in username',
    'ユーザー名から <span class="key">@</span> 以降の文字を削除する',
    '유저명에서 @와 후속 문자 제거',
  ],
  _移除用户名中的at和后续字符的说明: [
    '例如：Anmi@画集発売中 → Anmi',
    '例如：Anmi@画集発売中 → Anmi',
    'For example：Anmi@画集発売中 → Anmi',
    '例：Anmi@画集発売中 → Anmi',
    '예: Anmi@画集発売中 → Anmi',
  ],
  _抓取被限制时返回空结果的提示: [
    'Pixiv 返回了空数据。下载器已暂停抓取，并且会在等待几分钟后继续抓取。',
    'Pixiv 返回了空資料。下載器已暫停抓取，並且會在等待幾分鐘後繼續抓取。',
    'Pixiv returned empty data. The downloader has paused crawling and will resume crawling after a few minutes.',
    'Pixivが空のデータを返しました。 ダウンローダーはクロールを一時停止し、数分後にクロールを再開します。',
    'Pixiv가 빈 데이터를 반환했습니다. 다운로더가 긁어오기를 일시 중지하고 몇 분 동안 기다린 후 긁어오기를 계속합니다.',
  ],
  _解决了抓取搜索页面时被限制的问题的说明: [
    '解决了抓取搜索页面时可能会被 Pixiv 限制的问题。',
    '解決了抓取搜尋頁面時可能會被 Pixiv 限制的問題。',
    'Fixed an issue where crawling search pages could be restricted by Pixiv.',
    'Pixivで検索ページのクロールが制限される問題を修正しました。',
    '검색 페이지를 긁어올 때 Pixiv에 의해 제한될 수 있는 문제를 해결했습니다.',
  ],
  _搜索模式: ['搜索模式', '搜尋模式', 'Search mode', '検索モード', '검색 모드'],
  _标签部分一致: [
    '标签（部分一致）',
    '標籤（部分一致）',
    'Tags (partial match)',
    'タグ（部分一致）',
    '태그 (부분 일치)',
  ],
  _标签完全一致: [
    '标签（完全一致）',
    '標籤（完全一致）',
    'Tags (perfect match)',
    'タグ（完全一致）',
    '태그 (완전 일치)',
  ],
  _标题说明文字: [
    '标题、说明文字',
    '標題、說明文字',
    'Title, Caption',
    'タイトル・キャプション',
    '제목, 설명',
  ],
  _正文: ['正文', '本文', 'Text', '本文', '본문'],
  _标签标题说明文字: [
    '标签、标题、说明文字',
    '標籤、標題、說明文字',
    'Tags, Titles, Captions',
    'タグ・タイトル・キャプション',
    '태그, 제목, 설명',
  ],
  _save_file_failed_tip: [
    `{} 保存失败，code：{}。下载器将会重试下载这个文件。`,
    `{} 儲存失敗，code：{}。下載器將會重試下載這個檔案。`,
    `{} save failed, code: {}. The downloader will retry to download the file.`,
    `{} 保存に失敗しました。code：{}。ダウンローダーはファイルのダウンロードを再試行します。`,
    `{} 저장에 실패했습니다. 코드: {}. 다운로드더가 파일 다운로드를 다시 시도합니다.`,
  ],
  _user_canceled_tip: [
    `{} 未保存，code：{}。`,
    `{} 未儲存，code：{}。`,
    `{} not saved, code: {}.`,
    `{} 保存されていません。code：{}。`,
    `{} 저장되지 않음, 코드: {}.`,
  ],
  _FILE_FAILED_tip: [
    '可能是文件名太长，或是其他原因导致文件保存失败。你可以尝试启用高级设置里的“文件名长度限制”。',
    '可能是檔名太長，或是其他原因導致檔案儲存失敗。你可以嘗試啟用高階設定裡的“檔案名稱長度限制”。',
    'Maybe the file name is too long, or other reasons cause the file to fail to save. You can try enabling "File name length limit" in advanced settings.',
    'ファイル名が長すぎるか、他の理由でファイルの保存に失敗した可能性があります。 詳細設定で「ファイル名の長さ制限」を有効にしてみてください。',
    '파일명이 너무 길거나 다른 이유로 저장에 실패한 것 같습니다. 고급 설정에서 "파일명 길이 제한"을 사용하도록 설정할 수 있습니다.',
  ],
  _显示摘要信息: [
    '显示摘要信息',
    '顯示摘要資訊',
    'Show summary',
    '要約情報を表示する',
    '요약 정보 표시',
  ],
  _显示更大的缩略图: [
    '显示<span class="key">更大</span>的缩略图',
    '顯示<span class="key">更大</span>的縮圖',
    'show <span class="key">larger</span> thumbnails',
    '大きなサムネイルを表示する',
    '<span class="key">더 큰</span> 썸네일 표시',
  ],
  _横图占用二倍宽度: [
    '横图占用二倍宽度',
    '橫圖佔用二倍寬度',
    'Horizontal image takes up double the width',
    '水平方向の画像は幅の2倍を占めます',
    '가로 그림은 두 배의 너비를 차지',
  ],
  _该功能默认开启: [
    '这个功能默认启用。',
    '這個功能預設啟用。',
    'This feature is enabled by default.',
    'この機能はデフォルトで有効になっています。',
    '이 기능은 기본적으로 활성화됩니다.',
  ],
  _你可以在更多选项卡的xx分类里找到它: [
    '你可以在“更多”选项卡 → “{}”分类里找到它。（需要先启用“显示高级设置”）',
    '你可以在“更多”選項卡 → “{}”分類裡找到它。（需要先啟用“顯示進階設定”）',
    'You can find it in the "More" tab → "{}" category. ("Show advanced settings" needs to be enabled first)',
    '[もっと]タブ→[{}]カテゴリにあります。 （最初に「詳細設定を表示」を有効にする必要があります）',
    '"더보기" 탭 → "{}" 카테고리에서 찾을 수 있습니다. ("고급 설정 보기"를 먼저 활성화해야 합니다.)',
  ],
  _使用鼠标滚轮切换作品里的图片: [
    '使用鼠标滚轮切换多图作品里的图片',
    '使用滑鼠滾輪切換多圖作品裡的圖片',
    'Use the mouse wheel to switch images in multi-image works',
    'マウスホイールを使用して、マルチイメージ作品のイメージを切り替えます',
    '마우스 휠을 사용하여 여러 이미지 작품에서 이미지 전환',
  ],
  _这可能会阻止页面滚动: [
    '这可能会阻止页面滚动',
    '這可能會阻止頁面滾動',
    'This might stop the page from scrolling',
    'ページのスクロールを妨げる可能性があります',
    '이 기능은 페이지를 스크롤하지 못하게 할 수 있습니다.',
  ],
  _动图转换失败的提示: [
    '动图转换失败，id：{}',
    '動圖轉換失敗，id：{}',
    'Ugoira(animation) conversion failed, id: {}',
    'うごイラの変換に失敗しました、id：{}',
    '움직이는 일러스트 변환에 실패했습니다, ID: {}',
  ],
  _作品id无法下载带状态码: [
    '{} 无法下载，状态码：{}',
    '{} 無法下載，狀態碼：{}',
    '{} failed to download, status code: {}',
    '{} ダウンロードに失敗しました、ステータスコード：{}',
    '{} 다운로드할 수 없습니다, 상태 코드: {}',
  ],
  _作品总数为0: [
    '作品总数为 0，Pixiv 可能拒绝了此次抓取。请稍后重试。',
    '作品總數為 0，Pixiv 可能拒絕了此次抓取。請稍後重試。',
    'The total number of works is 0, Pixiv may have refused this crawl. Please try again later.',
    '作品の総数は 0 です。 Pixivがこのクロールを拒否した可能性があります。 後でもう一度やり直してください。',
    '총 작품 수가 0개입니다, Pixiv가 이번 긁어오기를 거부한 것으로 보입니다. 잠시 후에 다시 시도해주세요.',
  ],
  _快捷键AltP: [
    '快捷键 Alt + P',
    '快捷鍵 Alt + P',
    'Hot key: Alt + P',
    'ホットキー Alt + P',
    '단축키: Alt + P',
  ],
  _优化预览作品功能: [
    '优化“预览作品”功能',
    '最佳化“預覽作品”功能',
    'Optimize the "Preview Works" function',
    '「作品のプレビュー」機能を最適化する',
    '"작품 미리보기" 기능 최적화',
  ],
  _1230更新说明: [
    `1. 在网页标题上显示剩余下载数量<br>
    下载时，网页标题上会显示还有多少个文件尚未下载。<br>
    这样，用户不需要打开下载面板就能够知道下载进度。<br><br>
    2. 用户可以在下载时添加一些新的下载任务。`,
    `1. 在網頁標題上顯示剩餘下載數量<br>
    下載時，網頁標題上會顯示還有多少個檔案尚未下載。<br>
    這樣，使用者不需要開啟下載面板就能夠知道下載進度。<br><br>
    2. 使用者可以在下載時新增一些新的下載任務。`,
    `1. Show remaining downloads on page title<br>
    While downloading, the page title will show how many files are not yet downloaded. <br>
    In this way, the user can know the download progress without opening the download panel.<br><br>
    2. Users can add some new download tasks while downloading.`,
    `1. ページタイトルに残りのダウンロードを表示する<br>
    ダウンロード中、ページタイトルにはまだダウンロードされていないファイルの数が表示されます。 <br>
    このようにして、ユーザーはダウンロードパネルを開かなくてもダウンロードの進行状況を知ることができます。<br><br>
    2. ユーザーは、ダウンロード中にいくつかの新しいダウンロードタスクを追加できます。`,
    `1. 페이지 제목에 남은 다운로드 수를 표시합니다<br>
    다운로드하는 동안, 페이지 제목에 아직 다운로드하지 않은 파일이 몇 개 더 있는지 표시됩니다.<br>
    이렇게 하면 사용자는 다운로드 패널을 열지 않고도 다운로드 진행 상황을 알 수 있습니다.<br><br>
    2.사용자는 다운로드 중 새 다운로드 작업을 추가할 수 있습니다.
    `,
  ],
  _设定资料: [
    '设定资料',
    '設定資料',
    'Reference materials',
    '設定資料',
    '설정 자료',
  ],
  _年龄限制: [
    '<span class="key">年龄</span>限制',
    '<span class="key">年齡</span>限制',
    '<span class="key">Age</span> limit',
    '<span class="key">年齢</span>制限',
    '<span class="key">연령</span> 제한',
  ],
  _收藏状态: [
    '<span class="key">收藏</span>状态',
    '<span class="key">收藏</span>狀態',
    '<span class="key">Bookmark</span> status',
    'ブックマークステータス',
    '<span class="key">북마크</span> 상태',
  ],
  _图片色彩: [
    '图片<span class="key">色彩</span>',
    '圖片<span class="key">色彩</span>',
    'Image <span class="key">color</span>',
    '画像の<span class="key">色</span>',
    '이미지 <span class="key">색채</span>',
  ],
  _图片数量: [
    '图片<span class="key">数量</span>',
    '圖片<span class="key">數量</span>',
    '<span class="key">Number</span> of images',
    '画像の<span class="key">数</span>',
    '이미지 <span class="key">수</span>',
  ],
  _不抓取多图作品的最后一张图片: [
    '不抓取多图作品的<span class="key">最后一张</span>图片',
    '不抓取多圖作品的<span class="key">最後一張</span>圖片',
    'Do not crawl the <span class="key">last image</span> of multi-image works',
    'マルチ画像作品の<span class="key">最後の画像</span>をつかまないでください',
    '여러 이미지의 <span class="key">마지막 이미지</span> 긁어오지 않기',
  ],
  _下载小说的封面图片: [
    '下载小说的<span class="key">封面</span>图片',
    '下載小說的<span class="key">封面</span>圖片',
    'Download the <span class="key">cover</span> image of the novel',
    '小説の<span class="key">表紙画像</span>をダウンロード',
    '소설 <span class="key">커버</span> 이미지 다운로드',
  ],
  _预览动图: [
    '<span class="key">预览</span>动图',
    '<span class="key">預覽</span>動圖',
    '<span class="key">Preview</span> Ugoira',
    'うごイラのプレビュー',
    '움직이는 일러스트 <span class="key">미리보기</span>',
  ],
  _1282更新说明: [
    `加快转换动图的速度；<br>优化预览作品的体验；<br>添加了韩语文本。`,
    `加快轉換動圖的速度；<br>最佳化預覽作品的體驗；<br>添加了韓語文字。`,
    `Speed up the conversion of Ugoira;<br>Optimize the experience of previewing works;<br>Add Korean text.`,
    `うごイラの変換を高速化します;<br>作品のプレビュー体験を最適化します;<br>韓国語のテキストを追加します。`,
    `움직이는 일러스트 변환 속도 향상,<br>优化预览图片的体验,<br>한국어 텍스트 추가.`,
  ],
  _过度访问警告警告: [
    '下载器检测到你可能收到了 pixiv 的警告消息，这通常是因为过度下载导致的。<br>请等待一段时间再继续下载。',
    '下載器檢測到你可能收到了 pixiv 的警告訊息，這通常是因為過度下載導致的。<br>請等待一段時間再繼續下載。',
    'The downloader has detected that you may have received a warning message from pixiv, usually due to excessive downloads.<br>Please wait for a while before continuing the download.',
    'ダウンロードが多すぎるため、pixivから警告メッセージが届いた可能性があることをダウンローダーが検出しました。<br>ダウンロードを続行する前に、しばらくお待ちください。',
    '다운로더는 일반적으로 과도한 다운로드로 인해 pixiv에서 경고 메시지를 수신했을 수 있음을 감지했습니다.<br>다운로드를 계속하기 전에 잠시 기다려 주십시오.',
  ],
  _下载小说里的内嵌图片: [
    '下载小说里的<span class="key">内嵌</span>图片',
    '下載小說裡的<span class="key">內嵌</span>圖片',
    'Download <span class="key">embedded</span> images in novels',
    '小説に埋め込まれた画像をダウンロードする',
    '소설에서 <span class="key">인라인</span> 이미지 다운로드',
  ],
  _其他优化: [
    '其他优化',
    '其他最佳化',
    'Other optimizations',
    'その他の最適化',
    '기타 최적화',
  ],
  _隐藏浏览器底部的下载栏: [
    '隐藏浏览器底部的<span class="key">下载栏</span>',
    '隱藏瀏覽器底部的<span class="key">下載欄</span>',
    `Hide the <span class="key">download bar</span> at the bottom of the browser`,
    'ブラウザの下部にあるダウンロードバーを非表示にします',
    '브라우저 하단의 <span class="key">다운로드 바</span> 숨기기',
  ],
  _没有可用的抓取结果: [
    '没有可用的抓取结果',
    '沒有可用的抓取結果',
    'No crawl results available',
    'クロール結果がありません',
    '사용 가능한 크롤링 결과가 없습니다.',
  ],
  _预览作品时按快捷键D可以下载这个作品: [
    '预览作品时，按快捷键 <span class="key">D</span> 可以下载这个作品。',
    '預覽作品時，按快捷鍵 <span class="key">D</span> 可以下載這個作品。',
    'When previewing a work, press the shortcut key <span class="key">D</span> to download the work.',
    '作品をプレビューしているときに、ショートカット キー <span class="key">D</span> を押すと、作品をダウンロードできます。',
    '이미지를 미리 보는 동안 바로 가기 <span class="key">D</span>를 눌러 다운로드하세요.',
  ],
  _定时抓取: [
    '定时抓取',
    '定時抓取',
    'Timed crawl',
    '時限クロール',
    '시간 제한 크롤링',
  ],
  _定时抓取说明: [
    '每隔一定时间，自动开始抓取和下载。',
    '每隔一定時間，自動開始抓取和下載。',
    'Automatically start crawling and downloading at regular intervals.',
    '定期的にクロールとダウンロードを自動的に開始します。',
    '정기적으로 자동으로 크롤링 및 다운로드를 시작합니다.',
  ],
  _定时抓取已启动的提示: [
    '定时抓取已启动，间隔时间：{} 分钟。',
    '定時抓取已啟動，間隔時間：{} 分鐘。',
    'Timed crawl started, interval: {} minutes.',
    '時限クロールが開始されました。間隔: {} 分。',
    '시간 제한 크롤링이 시작되었습니다. 간격: {}분. ',
  ],
  _定时抓取已启动的提示2: [
    '请不要关闭这个标签页，也不要改变这个标签页的 URL。<br>建议启用“不下载重复文件”功能，以避免下载重复的文件。<br><br>如果这个扩展程序自动更新了，那么这个页面将不能正常下载文件（需要刷新页面来恢复正常）。 如果你想长期执行定时抓取任务，建议安装下载器的离线版本，以免因为自动更新而导致问题。<br>你可以在这里下载离线安装包：<a href="https://github.com/xuejianxianzun/PixivBatchDownloader/releases" target="_blank">Releases page</a>',
    '請不要關閉這個標籤頁，也不要改變這個標籤頁的 URL。<br>建議啟用“不下載重複檔案”功能，以避免下載重複的檔案。<br><br>如果這個擴充套件程式自動更新了，那麼這個頁面將不能正常下載檔案（需要重新整理頁面來恢復正常）。 如果你想長期執行定時抓取任務，建議安裝下載器的離線版本，以免因為自動更新而導致問題。<br>你可以在這裡下載離線安裝包：<a href="https://github.com/xuejianxianzun/PixivBatchDownloader/releases" target="_blank">Releases page</a>',
    'Please do not close this tab or change the URL of this tab. <br>It is recommended to enable the "Do not download duplicate files" feature to avoid downloading duplicate files.<br><br>If the extension is automatically updated, the page will not be able to download files normally (refresh the page to restore normal). If you want to perform scheduled crawling tasks for a long time, it is recommended to install the offline version of the downloader to avoid problems caused by automatic updates.<br>You can download the offline installation package here: <a href="https://github.com/xuejianxianzun/PixivBatchDownloader/releases" target="_blank">Releases page</a>',
    'このタブを閉じたり、このタブの URL を変更したりしないでください。<br>重複ファイルのダウンロードを避けるために、「重複ファイルをダウンロードしない」機能を有効にすることをお勧めします。<br><br>拡張機能が自動的に更新されると、ページはファイルを正常にダウンロードできなくなります (ページを更新して正常に戻します)。 スケジュールされたクロール タスクを長時間実行する場合は、自動更新による問題を回避するために、ダウンローダのオフライン バージョンをインストールすることをお勧めします。<br>オフライン インストール パッケージは、次の場所からダウンロードできます。<a href="https://github.com/xuejianxianzun/PixivBatchDownloader/releases" target="_blank">Releases page</a>',
    '이 탭을 닫거나 이 탭의 URL을 변경하지 마십시오.<br>중복 파일 다운로드를 방지하기 위해 "중복 파일 다운로드 금지" 기능을 활성화하는 것이 좋습니다.<br><br>확장자가 자동으로 업데이트되면 페이지에서 파일을 정상적으로 다운로드할 수 없습니다(페이지를 새로고침하여 정상으로 복원). 예약된 크롤링 작업을 장기간 수행하려면 자동 업데이트로 인한 문제를 방지하기 위해 다운로더의 오프라인 버전을 설치하는 것이 좋습니다.<br>여기에서 오프라인 설치 패키지를 다운로드할 수 있습니다. <a href="https://github.com/xuejianxianzun/PixivBatchDownloader/releases" target="_blank">Releases page</a>',
  ],
  _定时抓取的间隔时间: [
    '定时抓取的间隔时间',
    '定時抓取的間隔時間',
    'The interval time of timed crawl',
    '時間指定クロールの間隔時間',
    '정기 크롤링 간격 시간',
  ],
  _分钟: ['分钟', '分鐘', 'Minute', '分', '분'],
  _定时抓取的时间超过最大值: [
    '定时抓取的间隔时间超过最大值：',
    '定時抓取的間隔時間超過最大值：',
    'The interval of timed crawl exceeds the maximum value: ',
    '時間指定クロールの間隔が最大値を超えています: ',
    '시간 지정 크롤링 간격이 최대값을 초과합니다: ',
  ],
  _定时抓取的时间最小值: [
    '定时抓取的间隔时间最小值为 1 分钟。',
    '定時抓取的間隔時間最小值為 1 分鐘。',
    'The minimum interval for timed crawls is 1 minute.',
    '時間指定クロールの最小間隔は 1 分です。',
    '시간 지정 크롤링의 최소 간격은 1분입니다.',
  ],
  _取消定时抓取: [
    '取消定时抓取',
    '取消定時抓取',
    'Cancel timed crawl',
    '時間指定クロールをキャンセル',
    '시간 지정 크롤링 취소',
  ],
  _已取消定时抓取: [
    '已取消定时抓取',
    '已取消定時抓取',
    'Timed crawl canceled',
    '時間指定クロールがキャンセルされました',
    '예약된 크롤링이 취소되었습니다.',
  ],
  _因为URL变化取消定时抓取任务: [
    '因为 URL 变化，定时抓取任务已被取消。',
    '因為 URL 變化，定時抓取任務已被取消。',
    'The timed crawl task has been canceled due to URL changes.',
    'URL が変更されたため、時間指定クロール タスクがキャンセルされました。',
    'URL 변경으로 인해 시간이 지정된 크롤링 작업이 취소되었습니다.',
  ],
  _开始定时抓取: [
    '开始定时抓取',
    '開始定時抓取',
    'Start timed crawling',
    '時間指定クロールを開始する',
    '시간 지정 크롤링 시작',
  ],
  _等待下一次定时抓取: [
    '等待下一次定时抓取',
    '等待下一次定時抓取',
    'Wait for the next timed crawl',
    '次回の時限クロールを待つ',
    '다음 시간 크롤링을 기다립니다.',
  ],
  _当前时间: [
    '当前时间：',
    '當前時間：',
    'Current time: ',
    '現在の時刻：',
    '현재 시간: ',
  ],
  _仅在部分页面中可用: [
    '仅在部分页面中可用。',
    '僅在部分頁面中可用。',
    'Only available on some pages.',
    '一部のページのみ利用可能です。',
    '일부 페이지에서만 사용할 수 있습니다.',
  ],
  _发生错误原因: [
    '发生错误，原因：',
    '發生錯誤，原因：',
    'An error occurred due to:',
    '次の理由でエラーが発生しました:',
    '다음으로 인해 오류가 발생했습니다.',
  ],
  _扩展程序已更新: [
    '扩展程序已更新。',
    '擴充套件程式已更新。',
    'The extension has been updated.',
    '拡張機能が更新されました。',
    '확장이 업데이트되었습니다.',
  ],
  _未知错误: [
    '未知错误。',
    '未知錯誤。',
    'unknown mistake.',
    '未知の間違い。',
    '알 수 없는 실수.',
  ],
  _请刷新页面: [
    '请刷新页面。',
    '請重新整理頁面。',
    'Please refresh the page.',
    'ページを更新してください。',
    '페이지를 새로고침하세요.',
  ],
  _减慢抓取速度: [
    '减慢抓取速度',
    '減慢抓取速度',
    'Slow down crawl',
    'クロールを遅くする',
    '천천히 크롤링',
  ],
  _减慢抓取速度的说明: [
    '减慢抓取速度可以避免在抓取时被 Pixiv 临时限制。但这会增加抓取时间。',
    '減慢抓取速度可以避免在抓取時被 Pixiv 臨時限制。但這會增加抓取時間。',
    'Slow down the crawl to avoid being temporarily restricted by Pixiv while crawling. But this will increase the crawl time.',
    'クロール中にPixivによって一時的に制限されないように、クロールを遅くします。 ただし、これによりクロール時間が長くなります。',
    '크롤링하는 동안 Pixiv에 의해 일시적으로 제한되지 않도록 크롤링 속도를 늦춥니다. 그러나 이것은 크롤링 시간을 증가시킵니다.',
  ],
  _作品数量: ['作品数量', '作品數量', 'Number of works', '作品数', '작품 수'],
  _慢速抓取: [
    '慢速抓取',
    '慢速抓取',
    'slow crawl',
    'クロールが遅い',
    '느린 크롤링',
  ],
}

export { langText }
