import { Config } from './config/Config'

// 储存下载器使用的多语言文本
// 在属性名前面加上下划线，和文本内容做出区别
// {} 是占位符
// <br> 是换行

const langText = {
  _只下载已收藏: [
    '只下载已收藏',
    '只下載已收藏',
    'Download only bookmarked works',
    'ブックマークのみをダウンロードする',
  ],
  _下载作品类型: [
    '下载作品类型',
    '下載作品類型',
    'Download work type',
    'ダウンロード作品の種類',
  ],
  _作品类型: [
    '作品<span class="key">类型</span>',
    '作品<span class="key">類型</span>',
    '<span class="key">Type</span> of work',
    '作品の<span class="key">種類</span>',
  ],
  _不能含有tag: [
    '<span class="key">不能</span>含有标签',
    '<span class="key">不能</span>含有標籤',
    '<span class="key">Exclude</span> tag',
    'タグを除外する',
  ],
  _排除tag的提示文字: [
    '您可在下载前设置要排除的标签，这样在下载时将不会下载含有这些标签的作品。不区分大小写；如需排除多个标签，请使用英文逗号分隔。请注意要排除的标签的优先级大于要包含的tag的优先级。',
    '可在下載前設定要排除的標籤，下載時將排除含有這些標籤的作品，不區分大小寫；如需排除多個標籤，請使用半形逗號（,）分隔。請注意，要排除的標籤優先於要包含的標籤。',
    'Before downloading, you can set the tag you want to exclude. Not case sensitive; If you need to set multiple tags, you can use comma (,) separated. The excluded tag takes precedence over the included tag',
    'ダウンロード前に、除外するタグを設定できます。大文字と小文字を区別しない；複数のタグを設定する必要がある場合は、「,」で区切ってください。除外されたタグは、必要なタグよりも優先されます',
  ],
  _设置了排除tag之后的提示: [
    '排除标签：',
    '排除標籤：',
    'Excludes tag: ',
    '以下のタグを除外：',
  ],
  _必须含有tag: [
    '<span class="key">必须</span>含有标签',
    '<span class="key">必須</span>含有標籤',
    '<span class="key">Include</span> tag',
    '<span class="key">必要な</span>タグ',
  ],
  _必须tag的提示文字: [
    '您可在下载前设置作品里必须包含的标签，不区分大小写；如需包含多个标签，请使用英文逗号分隔。',
    '可在下載前設定作品裡必須包含的標籤，不區分大小寫；如需包含多個標籤，請使用半形逗號（,）分隔。',
    'Before downloading, you can set the tag that must be included. Not case sensitive; If you need to set multiple tags, you can use comma (,) separated. ',
    'ダウンロードする前に、必要なタグを設定することができます。大文字と小文字を区別しない；複数のタグを設定する必要がある場合は、「,」で区切ってください。',
  ],
  _设置了必须tag之后的提示: [
    '包含标签：',
    '包含標籤：',
    'Include tag: ',
    '以下の タグ を含める：',
  ],
  _图片的宽高比例: [
    '图片的宽高<span class="key">比例</span>',
    '圖片的寬高<span class="key">比例</span>',
    'Aspect <span class="key">ratio</span>',
    '画像の縦横比',
  ],
  _设置宽高比例Title: [
    '设置宽高比例，也可以手动输入宽高比',
    '設定寬高比，也可以手動輸入寬高比。',
    'Set the aspect ratio, or manually type the aspect ratio',
    '縦横比を設定する、手動で縦横比を入力することもできる',
  ],
  _不限制: ['不限制', '不限制', 'not limited', '無制限'],
  _横图: ['横图', '橫圖', 'Horizontal', '横長'],
  _竖图: ['竖图', '豎圖', 'Vertical', '縦長'],
  _正方形: ['正方形', '正方形', 'Square', '正方形'],
  _输入宽高比: ['宽高比 >=', '寬高比 >=', 'Aspect ratio >=', '縦横比 >='],
  _设置了宽高比之后的提示: [
    '宽高比：{}',
    '寬高比：{}',
    'Aspect ratio: {}',
    '縦横比：{}',
  ],
  _宽高比必须是数字: [
    '宽高比必须是数字',
    '寬高比必須是數字',
    'The aspect ratio must be a number',
    '縦横比は数値でなければなりません',
  ],
  _图片的宽高: [
    '图片的<span class="key">宽高</span>',
    '圖片的<span class="key">寬高</span>',
    '<span class="key">width</span> and height',
    '画像の幅と高さ',
  ],
  _筛选宽高的提示文字: [
    '请输入最小宽度和最小高度，不会下载不符合要求的图片。',
    '請輸入最小寬度和最小高度，只會下載符合要求的圖片。',
    'Please type the minimum width and minimum height. Will not download images that do not meet the requirements',
    '最小幅と最小高さを入力してください。要件を満たしていない画像はダウンロードされません。',
  ],
  _本次输入的数值无效: [
    '本次输入的数值无效',
    '本次輸入的數值無效',
    'Invalid input',
    '無効な入力',
  ],
  _宽度: ['宽度', '寬度', 'Width', '幅'],
  _或者: [' 或者 ', ' 或是 ', ' or ', ' または '],
  _并且: [' 并且 ', ' 並且 ', ' and ', ' そして '],
  _高度: ['高度', '高度', 'height', '高さ'],
  _抓取多少作品: [
    '抓取<span class="key">多少</span>作品',
    '擷取<span class="key">多少</span>作品',
    'How <span class="key">many</span> works to crawl',
    'クロールする作品の数',
  ],
  _抓取多少页面: [
    '抓取<span class="key">多少</span>页面',
    '擷取<span class="key">多少</span>頁面',
    'How <span class="key">many</span> pages to crawl',
    'クロールするページ数',
  ],
  _收藏数量: [
    '<span class="key">收藏</span>数量',
    '<span class="key">收藏</span>數量',
    'Number of <span class="key">bookmarks</span>',
    'ブックマークの数',
  ],
  _设置收藏数量的提示: [
    '如果作品的收藏数小于设置的数字，作品不会被下载。',
    '只會下載設定收藏數範圍內的作品。',
    'If the number of bookmarks of the work is less than the set number, the work will not be downloaded.',
    '作品のブックマークされた数が設定された数字よりも少ない場合、作品はダウンロードされません。',
  ],
  _筛选收藏数的提示文字: [
    '请输入一个数字，如果作品的收藏数小于这个数字，作品不会被下载。',
    '請輸入數字，只會下載設定收藏數範圍內的作品。',
    'Please type a number. If the number of bookmarks of the work is less than this number, the work will not be downloaded.',
    '数字を入力してください。 作品のブックマークされた数がこの数字より少ない場合、作品はダウンロードされません。',
  ],
  _收藏数大于: [
    '收藏数 >= ',
    '收藏數 >= ',
    'Number of bookmarks >= ',
    'ブックマークの数 >= ',
  ],
  _收藏数小于: [
    '收藏数 <= ',
    '收藏數 <= ',
    'Number of bookmarks <= ',
    'ブックマークの数 <= ',
  ],
  _本次任务已全部完成: [
    '本次任务已全部完成。',
    '本次工作已全部完成',
    'This task has been completed.',
    'この作業は完了しました。',
  ],
  _本次任务条件: [
    '本次任务条件: ',
    '本次工作條件：',
    'This task condition: ',
    'この作業の条件：',
  ],
  _参数不合法: [
    '参数不合法，本次操作已取消。',
    '參數不合法，本次動作已取消。',
    'Parameter is not legal, this operation has been canceled.',
    'パラメータは有効ではありません。この操作はキャンセルされました。',
  ],
  _向下获取所有作品: [
    '向下获取所有作品',
    '向下取得所有作品',
    'download all the work from this page.',
    'このページからすべての作品をダウンロードする。',
  ],
  _从本页开始下载提示: [
    '从本页开始下载<br>如果要限制下载的页数，请输入从1开始的数字。<br>1为仅下载本页。',
    '從本頁開始下載。<br>如果要限制下載的頁數，請輸入從 1 開始的數字。<br>1 為僅下載本頁。',
    'Download from this page<br>If you want to set the number of pages to download, type a number starting at 1. <br>1 is to download only this page.',
    'このページからダウンロードする<br>ダウンロードするページを設定する場合は、1から始まる数字を入力してください。<br>1 は現在のページのみをダウンロードする。',
  ],
  _下载所有页面: [
    '下载所有页面',
    '下載所有頁面',
    'download all pages',
    'すべてのページをダウンロードする',
  ],
  _下载x个相关作品: [
    '下载 {} 个相关作品',
    '下載 {} 個相關作品',
    'download {} related works.',
    '関連作品 {} 枚をダウンロードする。',
  ],
  _下载所有相关作品: [
    '下载所有相关作品',
    '下載所有相關作品',
    'download all related works.',
    '関連作品をすべてダウンロードする。',
  ],
  _下载推荐作品: [
    '下载推荐作品',
    '下載推薦作品',
    'download recommend works',
    'お勧め作品をダウンロードする',
  ],
  _下载排行榜前x个作品: [
    '下载排行榜前 {} 个作品',
    '下載排行榜前 {} 個作品',
    'download the top {} works in the ranking list',
    'ランク前 {} 位の作品をダウンロードする。',
  ],
  _输入超过了最大值: [
    '您输入的数字超过了最大值',
    '輸入的數字超出最大值',
    'The number you set exceeds the maximum',
    '入力した番号が最大値を超えています',
  ],
  _从本页开始下载x页: [
    '从本页开始下载 {} 页',
    '從本頁開始下載 {} 頁',
    'download {} pages from this page',
    'このページから {} ページをダウンロードする',
  ],
  _从本页开始下载x个: [
    '从本页开始下载 {} 个作品',
    '從本頁開始下載 {} 個作品',
    'Download {} works from this page.',
    'このページから {} 枚の作品をダウンロード。',
  ],
  _任务开始0: ['任务开始', '工作開始', 'Task starts', '作業が開始されます'],
  _排除作品类型: [
    '排除作品类型：',
    '排除作品類型：',
    'Excludes these types of works: ',
    'これらのタイプの作品を除外：',
  ],
  _多图作品: ['多图作品', '多圖作品', 'Multi-image works', '複数画像作品'],
  _多图下载设置: [
    '多图下载设置',
    '多圖下載設定',
    'Download multi-image works',
    '複数画像設定',
  ],
  _不下载: ['不下载', '不下載', 'No', '必要なし'],
  _全部下载: ['全部下载', '全部下載', 'Yes', '全部ダウンロード'],
  _插画: ['插画', '插畫', 'Illustrations', 'イラスト'],
  _漫画: ['漫画', '漫畫', 'Manga', '漫画'],
  _动图: ['动图', '動圖', 'Ugoira', 'うごイラ'],
  _动图保存格式: [
    '<span class="key">动图</span>保存格式',
    '<span class="key">動圖</span>儲存格式',
    'Save the <span class="key">ugoira</span> work as',
    'うごイラの保存タイプ',
  ],
  _动图保存格式title: [
    '下载动图时，可以把它转换成视频文件',
    '下載動圖時，可轉換為影片檔。',
    'When you download a ugoira work, you can convert it to a video file.',
    'うごイラをダウンロードするとき、動画に変換することができます。',
  ],
  _webmVideo: ['WebM 视频', '影片（WebM）', 'WebM video', 'WebM ビデオ'],
  _gif: ['GIF 图片', '圖片（GIF）', 'GIF image', 'GIF 画像'],
  _apng: ['APNG 图片', '圖片（APNG）', 'APNG image', 'APNG 画像'],
  _zipFile: ['Zip 文件', '壓縮檔（Zip）', 'Zip file', 'ZIP ファイル'],
  _当前作品个数: [
    '当前有 {} 个作品 ',
    '目前有 {} 個作品 ',
    'There are now {} works ',
    '今は　{}　枚の作品があります ',
  ],
  _当前有x个用户: [
    '当前有 {} 个用户 ',
    '目前有 {} 個使用者 ',
    'There are currently {} users ',
    '現在 {} 人のユーザーがいます ',
  ],
  _已抓取x个用户: [
    '已抓取 {} 个用户 ',
    '已擷取 {} 個使用者 ',
    'crawled {} users',
    'クロールされた {} ユーザー',
  ],
  _排行榜进度: [
    '已抓取本页面第{}部分',
    '已擷取本頁面第 {} 部分',
    'Part {} of this page has been crawled',
    'このページの第　{}　部がクロールされました',
  ],
  _新作品进度: [
    '已抓取本页面 {} 个作品',
    '已擷取本頁面 {} 個作品',
    'This page has been crawled {} works',
    'このページの {} つの作品をクロールしました',
  ],
  _抓取多少个作品: [
    '抓取本页面 {} 个作品',
    '擷取本頁面 {} 個作品',
    'Crawl this page {} works',
    'このページの {} つの作品をクロールします',
  ],
  _相关作品抓取完毕: [
    '相关作品抓取完毕。包含有{}个作品，开始获取作品信息。',
    '相關作品擷取完畢。包含有 {} 個作品，開始取得作品資訊。',
    'The related works have been crawled. Contains {} works and starts getting information about the work.',
    '関連作品はクロールされました。 {} 作品を含み、その作品に関する情報の取得を開始します。',
  ],
  _排行榜任务完成: [
    '本页面抓取完毕。<br>当前有{}个作品，开始获取作品信息。',
    '本頁面擷取完畢。<br>目前有 {} 個作品，開始取得作品資訊。',
    'This page is crawled and now has {} works.<br> Start getting the works for more information.',
    'このページのクロール終了。<br>{}枚の作品があります。 作品情報の取得を開始します。',
  ],
  _开始获取作品信息: [
    '开始获取作品信息',
    '開始取得作品資訊',
    'Start getting work data',
    '作品情報の取得を開始します',
  ],
  _列表页抓取进度: [
    '已抓取列表页 {} 个页面',
    '已擷取清單頁 {} 個頁面',
    'Has acquired {} list pages',
    '{} のリストページを取得しました',
  ],
  _列表页抓取进度2: [
    '正在抓取列表页 {}/{}',
    '正在抓取列表頁 {}/{}',
    'crawling list page {}/{}',
    'リストページの取得 {}/{}',
  ],
  _列表页抓取完成: [
    '列表页面抓取完成',
    '清單頁面擷取完成',
    'The list page is crawled',
    'リストページがクロールされ',
  ],
  _抓取结果为零: [
    '抓取完毕，但没有找到符合筛选条件的作品。',
    '擷取完畢，但沒有找到符合篩選條件的作品。',
    'Crawl complete but did not find works that match the filter criteria.',
    'クロールは終了しましたが、フィルタ条件に一致する作品が見つかりませんでした。',
  ],
  _当前任务尚未完成: [
    '当前任务尚未完成',
    '目前工作尚未完成',
    'The current task has not yet been completed',
    '現在の作業はまだ完了していません',
  ],
  _当前任务尚未完成2: [
    '当前任务尚未完成，请等待完成后再下载。',
    '目前工作尚未完成，請等待完成後再下載。',
    'The current task has not yet been completed',
    '現在の作業はまだ完了していません、完了するまでお待ちください',
  ],
  _列表抓取完成开始获取作品页: [
    '当前列表中有{}张作品，开始获取作品信息',
    '目前清單中有 {} 張作品，開始取得作品資訊',
    'Now has {} works. Start getting the works for more information.',
    '{} 枚の作品があります。 作品情報の取得を開始します。',
  ],
  _开始获取作品页面: [
    '开始获取作品页面',
    '開始取得作品頁面',
    'Start getting the works page',
    '作品ページの取得を開始する',
  ],
  _无权访问: [
    '无权访问 {}，跳过该作品。',
    '沒有權限存取 {}，跳過該作品。',
    'No access {}, skip.',
    '{} のアクセス権限がありません、作品を無視する。',
  ],
  _作品页状态码0: [
    '请求的 URL 不可访问 (0)',
    '要求的 URL 無法存取 (0)',
    'The requested URL is not accessible (0)',
    '要求された URL にアクセスできません (0)',
  ],
  _作品页状态码400: [
    '该作品已被删除 (400)',
    '該作品已被刪除 (400)',
    'The work has been deleted (400)',
    '作品は削除されました (400)',
  ],
  _作品页状态码403: [
    '无权访问请求的 URL (403)',
    '沒有權限存取要求的 URL (403)',
    'Have no access to the requested URL (403',
    'リクエストされた URL にアクセスできない (403)',
  ],
  _作品页状态码404: [
    '404 not found',
    '404 not found',
    '404 not found',
    '404 not found',
  ],
  _正在抓取: [
    '正在抓取，请等待……',
    '擷取中，請稍後……',
    'Getting, please wait...',
    'クロール中、しばらくお待ちください...',
  ],
  _获取全部书签作品: [
    '获取全部书签作品，时间可能比较长，请耐心等待。',
    '取得全部書籤作品，時間可能比較長，請耐心等待。',
    'Get all bookmarked works, the time may be longer, please wait.',
    'ブックマークしたすべての作品を取得すると、時間がかかることがあります。お待ちください。',
  ],
  _抓取图片网址遇到中断: [
    '当前任务已中断!',
    '目前工作已中斷！',
    'The current task has been interrupted.',
    '現在の作業が中断されました。',
  ],
  _关闭: ['关闭', '關閉', 'close', 'クローズ'],
  _输出信息: ['输出信息', '輸出資訊', 'Output information', '出力情報'],
  _复制: ['复制', '複製', 'Copy', 'コピー'],
  _已复制到剪贴板: [
    '已复制到剪贴板，可直接粘贴',
    '已複製至剪貼簿，可直接貼上',
    'Has been copied to the clipboard',
    'クリップボードにコピーされました',
  ],
  _下载设置: ['下载设置', '下載設定', 'Download settings', 'ダウンロード設定'],
  _收起展开设置项: [
    '收起/展开设置项',
    '摺疊/展開設定項目',
    'Collapse/expand settings',
    '設定の折りたたみ/展開',
  ],
  _github: [
    'Github 页面，欢迎 star',
    'Github 頁面，歡迎 star',
    'Github page, if you like, please star it',
    'Github のページ、star をクリックしてください',
  ],
  _wiki: ['使用手册', 'Wiki', 'Wiki', 'マニュアル'],
  _快捷键切换显示隐藏: [
    '使用 Alt + X，可以显示和隐藏下载面板',
    'Alt + X 可以顯示或隱藏下載面板。',
    'Use Alt + X to show and hide the download panel',
    'Alt + X てダウンロードパネルを表示および非表示にする',
  ],
  _隐藏下载面板: [
    '隐藏下载面板（Alt + X）',
    '隱藏下載面板（Alt + X）',
    'Hide the download panel (Alt + X)',
    'ダウンロードパネルを非表示にする（Alt + X）',
  ],
  _共抓取到n个文件: [
    '共抓取到 {} 个文件',
    '共擷取到 {} 個檔案',
    'Crawl a total of {} files',
    '合計 {} つのファイルがあります',
  ],
  _共抓取到n个作品: [
    '共抓取到 {} 个作品',
    '共擷取到 {} 個作品',
    'Crawl a total of {} works',
    '合計 {} つの作品があります',
  ],
  _命名规则: [
    ' <span class="key">命名</span>规则',
    '<span class="key">命名</span>規則',
    '<span class="key">Naming</span> rule',
    '<span class="key">命名</span>規則',
  ],
  _设置文件夹名的提示: [
    "可以使用 '/' 建立文件夹。示例：",
    '可以使用斜線（/）建立資料夾。範例：',
    "You can create a directory with '/'. Example：",
    "フォルダーは '/' で作成できます。例：",
  ],
  _添加命名标记前缀: [
    '添加命名标记<span class="key">前缀</span>',
    '加入命名標記<span class="key">前綴</span>',
    'Add named tag <span class="key">prefix</span>',
    '前にタグの名前を追加',
  ],
  _添加字段名称提示: [
    `例如，在用户名前面添加“user_”标记`,
    '例如，在使用者名稱前面加入「user_」標記。',
    `For example, add the 'user_' tag in front of the username`,
    'たとえば、ユーザー名の前に 「user_」タグを追加します。',
  ],
  _命名标记id: [
    '默认文件名，如 44920385_p0',
    '預設檔案名稱，例如：44920385_p0。',
    'Default file name, for example 44920385_p0',
    'デフォルトのファイル名，例 44920385_p0',
  ],
  _命名标记title: ['作品标题', '作品標題', 'Works title', '作品のタイトル'],
  _命名标记tags: [
    '作品的标签列表',
    '作品的標籤清單',
    'The tags of the work',
    '作品のタグ',
  ],
  _命名标记user: ['用户名字', '使用者名稱', 'User name', 'ユーザー名'],
  _用户id: ['用户 ID', '使用者 ID', 'User ID', 'ユーザー ID'],
  _命名标记px: ['宽度和高度', '寬度和高度', 'Width and height', '幅と高さ'],
  _命名标记bmk: [
    'Bookmark count，作品的收藏数。把它放在最前面可以让文件按收藏数排序。',
    'Bookmark count，作品的收藏數。將它放在最前面可以讓檔案依收藏數排序。',
    'Bookmark count, bookmarks number of works.',
    'Bookmark count，作品のボックマークの数、前に追加することでボックマーク数で并べることができます。',
  ],
  _命名标记bmk_id: [
    'Bookmark Id。你收藏的每一个作品都会有一个 Bookmark Id。收藏的时间越晚，Bookmark Id 就越大。当你下载你的收藏时，可以使用 {bmk_id} 作为排序依据。',
    'Bookmark Id。你收藏的每一個作品都會有一個 Bookmark Id。收藏的時間越晚，Bookmark Id 就越大。當你下載你的收藏時，可以使用 {bmk_id} 作為排序依據。',
    'Bookmark Id. Every work in your bookmarks will have a Bookmark Id. The later the bookmark is added, the larger the Bookmark Id. When you download your bookmarks, you can use {bmk_id} as a sorting basis.',
    'ブックマークID。 ブックマーク内のすべての作品にはブックマークIDがあります。 ブックマークを後で追加すると、ブックマークIDが大きくなります。 ブックマークをダウンロードするときは、{bmk_id}を並べ替えの基準として使用できます。',
  ],
  _命名标记bmk_1000: [
    '作品收藏数的简化显示。例如：0+、1000+、2000+、3000+ ……',
    '作品收藏數的簡化顯示。例如：0+、1000+、2000+、3000+ ……',
    'Simplified number of bookmark, e.g. 0+、1000+、2000+、3000+ ……',
    '作品のボックマークの数の簡略表示。 例：0+、1000+、2000+、3000+ ……',
  ],
  _命名标记like: [
    'Like count，作品的点赞数。',
    'Like count，作品的點讚數。',
    'Like count.',
    'Like count。',
  ],
  _命名标记view: [
    'View count，作品的浏览量。',
    'View count，作品的瀏覽量。',
    'View count.',
    'View count。',
  ],
  _命名标记id_num: [
    '数字 id，如 44920385',
    '數字 id，例如：44920385。',
    'Number id, for example 44920385',
    '44920385 などの番号 ID',
  ],
  _命名标记p_num: [
    '图片在作品内的序号，如 0、1、2 …… 每个作品都会重新计数。',
    '圖片在作品內的序號，例如：0、1、2……每個作品都將重新計數。',
    'The serial number of the image in the work, such as 0, 1, 2 ... Each work will be recounted.',
    '0、1、2 など、作品の画像のシリアル番号。各ピースは再集計されます。',
  ],
  _命名标记tags_trans: [
    '作品的标签列表，附带翻译后的标签（如果有）',
    '作品的標籤清單，包含翻譯後的標籤（如果有的話）。',
    'The tags of the work, with the translated tag (if any)',
    '作品のタグリスト、翻訳付きタグ(あれば)',
  ],
  _命名标记tags_transl_only: [
    '翻译后的标签列表',
    '譯後的標籤清單。',
    'Translated tags',
    '翻訳后のタグリスト',
  ],
  _命名标记date: [
    '作品的创建时间。如 2019-08-29',
    '作品的建立時間。例如：2019-08-29。',
    'The time the creation of the work. Such as 2019-08-29',
    '作品の作成時間。例 2019-08-29',
  ],
  _命名标记rank: [
    '作品在排行榜中的排名。如 #1、#2 …… 只能在排行榜页面中使用。',
    '作品在排行榜中的排名。例如：#1、#2……只能在排行榜頁面中使用。',
    'The ranking of the work in the ranking pages. Such as #1, #2 ... Can only be used in ranking pages.',
    '作品のランキング。例え　#1、#2 …… ランキングページのみで使用できます。',
  ],
  _命名标记type: [
    '作品类型，分为：Illustration, Manga, Ugoira, Novel',
    '作品類型，分為：Illustration, Manga, Ugoira, Novel',
    'The type of work, divided into：Illustration, Manga, Ugoira, Novel',
    '作品分類は：Illustration, Manga, Ugoira, Novel',
  ],
  _命名标记提醒: [
    '为了防止文件名重复，命名规则里一定要包含 {id} 或者 {id_num}{p_num}。<br>您可以使用多个标记；建议在不同标记之间添加分割用的字符。示例：{id}-{user_id}<br>* 在某些情况下，会有一些标记不可用。',
    '為了防止檔名重複，命名規則裡一定要包含 {id} 或者 {id_num}{p_num}。可以使用多個標記；建議在不同標記之間加入分隔用的字元。範例：{id}-{user_id}<br>＊某些情況下有些標記無法使用。',
    'To prevent duplicate file names, {id} or {id_num}{p_num} must be included in the naming rules.<br>You can use multiple tags, and you can add a separate character between different tags. Example: {id}-{user_id}<br>* In some cases, some tags will not be available.',
    'ファイル名の重複を防ぐために、命名規則には {id} または {id_num}{p_num} を含める必要があります。<br>複数のタグを使用することができます；異なるタグ間の分割のために文字を追加することをお勧めします。例：{id}-{user_id}<br>* 場合によっては、一部のタグが利用できず。',
  ],
  _命名规则一定要包含id: [
    '为了防止文件名重复，命名规则里一定要包含 {id} 或者 {id_num}{p_num}',
    '為了防止檔名重複，命名規則裡一定要包含 {id} 或者 {id_num}{p_num}。',
    'To prevent duplicate file names, {id} or {id_num}{p_num} must be included in the naming rules.',
    'ファイル名の重複を防ぐために、命名規則には {id} または {id_num}{p_num} を含める必要があります。',
  ],
  _文件夹标记PTag: [
    '当前页面的标签。当前页面没有标签时不可用。',
    '目前頁面的標籤。目前頁面沒有標籤時無法使用。',
    'The tag of the current page. Not available if the current page has no tag.',
    '現在のページのタグ。現在のページのタグ がないときは使用できません。',
  ],
  _命名标记seriesTitle: [
    '系列标题（可能为空）',
    '系列標題（可能為空）',
    'Series title (may be empty)',
    'シリーズタイトル（あれば）',
  ],
  _命名标记seriesOrder: [
    '作品在系列中的序号，如 #1 #2',
    '作品在系列中的編號，如 #1 #2',
    'The number of the work in the series, such as #1 #2',
    'シリーズの中の作品の番号，例え #1 #2',
  ],
  _命名标记seriesId: ['系列 ID', '系列 ID', 'Series ID', 'シリーズ ID'],
  _文件夹标记PTitle: [
    '当前页面的标题',
    '目前頁面的標題',
    'The title of this page',
    'ページのタイトル',
  ],
  _预览文件名: [
    '预览文件名',
    '預覽檔案名稱',
    'Preview file name',
    'ファイル名のプレビュー',
  ],
  _下载线程: [
    '下载<span class="key">线程</span>',
    '下載<span class="key">執行緒</span>',
    'Download <span class="key">thread</span>',
    '同時ダウンロード数',
  ],
  _下载线程的说明: [
    `你可以输入 1-${Config.downloadThreadMax} 之间的数字，设置同时下载的数量`,
    `你可以輸入 1-${Config.downloadThreadMax} 之間的數字，設定同時下載的數量。`,
    `You can type a number between 1-${Config.downloadThreadMax} to set the number of concurrent downloads`,
    `同時ダウンロード数を設定、1-${Config.downloadThreadMax} の数値を入力してください`,
  ],
  _开始下载: ['开始下载', '開始下載', 'Start download', '開始'],
  _暂停下载: ['暂停下载', '暫停下載', 'Pause download', '一時停止'],
  _停止下载: ['停止下载', '停止下載', 'Stop download', '停止'],
  _复制url: ['复制 URL', '複製下載網址', 'Copy URLs', 'URL をコピー'],
  _当前状态: ['当前状态 ', '目前狀態：', 'State ', '現在の状態 '],
  _未开始下载: [
    '未开始下载',
    '未開始下載',
    'Not yet started downloading',
    'まだダウンロードを開始していません',
  ],
  _下载进度: ['下载进度', '下載進度', 'Total progress', '概要'],
  _常见问题: ['常见问题', '常見問題', 'Help', 'よくある質問'],
  _uuid: [
    '如果下载后的文件名异常，请禁用其他有下载功能的浏览器扩展。',
    '如果下載後的檔案名稱異常，請停用其他有下載功能的瀏覽器擴充功能。',
    'If the file name after downloading is abnormal, disable other browser extensions that have download capabilities.',
    'ダウンロード後のファイル名が異常な場合は、ダウンロード機能を持つ他のブラウザ拡張機能を無効にしてください。',
  ],
  _常见问题说明: [
    '下载的文件保存在浏览器的下载目录里。<br><br>建议在浏览器的下载设置中关闭“下载前询问每个文件的保存位置”。<br><br>如果下载后的文件名异常，请禁用其他有下载功能的浏览器扩展。<br><br>如果你使用 ssr、v2ray 等代理软件，开启全局代理有助于提高下载速度。<br><br>QQ群：675174717<br><br>在 Wiki 查看常见问题：<br><a href="https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/常见问题" target="_blank">https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/常见问题</a><br><br>中文教程视频：<br><a href="https://www.youtube.com/playlist?list=PLO2Mj4AiZzWEpN6x_lAG8mzeNyJzd478d" target="_blank">https://www.youtube.com/playlist?list=PLO2Mj4AiZzWEpN6x_lAG8mzeNyJzd478d</a>',
    '下載的檔案儲存在瀏覽器的下載目錄裡。<br><br>請不要在瀏覽器的下載選項裡選取「下載每個檔案前先詢問儲存位置」。<br><br>如果下載後的檔名異常，請停用其他有下載功能的瀏覽器擴充功能。',
    'The downloaded file is saved in the browser`s download directory. <br><br>It is recommended to turn off "Ask where to save each file before downloading" in the browser`s download settings.<br><br>If the file name after downloading is abnormal, disable other browser extensions that have download capabilities.',
    'ダウンロードしたファイルは、ブラウザのダウンロードディレクトリに保存されます。<br><br>ブラウザのダウンロード設定で 「 ダウンロード前に各ファイルの保存場所を確認する 」 をオフにすることをお勧めします。<br><br>ダウンロード後のファイル名が異常な場合は、ダウンロード機能を持つ他のブラウザ拡張機能を無効にしてください。',
  ],
  _首次下载显示的提示: [
    '下载的文件保存在浏览器的下载目录里。<br><br>建议您在浏览器的下载设置中关闭“下载前询问每个文件的保存位置”。<br><br>如果你使用 ssr、v2ray 等代理软件，开启全局代理有助于提高下载速度。',
    '下載的檔案儲存在瀏覽器的下載目錄裡。<br><br>請不要在瀏覽器的下載選項裡選取「下載每個檔案前先詢問儲存位置」。',
    'The downloaded file is saved in the browser`s download directory. <br><br>It is recommended to turn off "Ask where to save each file before downloading" in the browser`s download settings.',
    'ダウンロードしたファイルは、ブラウザのダウンロードディレクトリに保存されます。<br><br>ブラウザのダウンロード設定で 「 ダウンロード前に各ファイルの保存場所を確認する 」 をオフにすることをお勧めします。',
  ],
  _正在下载中: ['正在下载中', '正在下載', 'Downloading', 'ダウンロード中'],
  _下载完毕: [
    '✓ 下载完毕',
    '✓ 下載完畢',
    '✓ Download complete',
    '✓ ダウンロードが完了しました',
  ],
  _下载完毕2: [
    '下载完毕',
    '下載完畢',
    'Download complete',
    'ダウンロードが完了しました',
  ],
  _已暂停: [
    '下载已暂停',
    '下載已暫停',
    'Download is paused',
    'ダウンロードは一時停止中です',
  ],
  _已停止: [
    '下载已停止',
    '下載已停止',
    'Download stopped',
    'ダウンロードが停止しました',
  ],
  _已下载: ['已下载', '已下載', 'downloaded', 'downloaded'],
  _抓取完毕: [
    '抓取完毕！',
    '擷取完畢！',
    'Crawl complete!',
    'クロールが終了しました！',
  ],
  _快速下载本页: [
    '快速下载本页作品 (Alt + Q)',
    '快速下載本頁作品 (Alt + Q)',
    'Download this work quickly (Alt + Q)',
    'この作品をすばやくダウンロードする (Alt + Q)',
  ],
  _从本页开始抓取new: [
    '从本页开始抓取新作品',
    '從本頁開始擷取新作品',
    'Crawl the new works from this page',
    'このページから新しい作品を入手する',
  ],
  _从本页开始抓取old: [
    '从本页开始抓取旧作品',
    '從本頁開始擷取舊作品',
    'Crawl the old works from this page',
    'このページから古い作品を入手する',
  ],
  _抓取推荐作品: [
    '抓取推荐作品',
    '擷取推薦作品',
    'Crawl the recommend works',
    '推奨作品をダウンロードする',
  ],
  _抓取推荐作品Title: [
    '抓取页面底部的的推荐作品',
    '擷取頁面底部的推薦作品。',
    'Crawl the recommended works at the bottom of the page',
    'ページの下部で推奨作品をクロールします',
  ],
  _抓取相关作品: [
    '抓取相关作品',
    '擷取相關作品',
    'Crawl the related works',
    '関連作品をダウンロードする',
  ],
  _调整完毕: [
    '调整完毕，当前有{}个作品。',
    '調整完畢，目前有 {} 個作品。',
    'The adjustment is complete and now has {} works.',
    '調整が完了し、今、{} の作品があります。',
  ],
  _抓取当前作品: [
    '抓取当前作品',
    '擷取目前作品',
    'Crawl the current work',
    '現在の作品をクロールする',
  ],
  _抓取当前作品Title: [
    '抓取当前列表里的所有作品',
    '擷取目前清單裡的所有作品',
    'Crawl all the works in the current list',
    '現在のリスト内のすべての作品をクロールする',
  ],
  _清除多图作品: [
    '清除多图作品',
    '清除多圖作品',
    'Remove multi-drawing works',
    '複数画像をクリア',
  ],
  _清除多图作品Title: [
    '如果不需要可以清除多图作品',
    '如果不需要可以清除多圖作品。',
    'If you do not need it, you can delete multiple graphs',
    '必要がない場合は、複数のグラフを削除することができます',
  ],
  _清除动图作品: [
    '清除动图作品',
    '清除動圖作品',
    'Remove ugoira work',
    'うごイラ作品を削除する',
  ],
  _清除动图作品Title: [
    '如果不需要可以清除动图作品',
    '如果不需要可以清除動圖作品。',
    'If you do not need it, you can delete the ugoira work',
    '必要がない場合は、うごイラを削除することができます',
  ],
  _手动删除作品: [
    '手动删除作品',
    '手動刪除作品',
    'Manually delete the work',
    '作品を手動で削除する',
  ],
  _手动删除作品Title: [
    '可以在下载前手动删除不需要的作品',
    '可以在下載前手動刪除不需要的作品，點擊作品刪除。',
    'You can manually delete unwanted work before downloading',
    'ダウンロードする前に不要な作品を手動で削除することができます',
  ],
  _退出手动删除: [
    '退出手动删除',
    '結束手動刪除',
    'Exit manually delete',
    '削除モードを終了する',
  ],
  _抓取本页作品: [
    '抓取本页作品',
    '擷取本頁作品',
    'Crawl this page works',
    'このページをクロールする',
  ],
  _抓取本页作品Title: [
    '抓取本页列表中的所有作品',
    '擷取本頁清單中的所有作品',
    'Crawl this page works',
    'このページの全ての作品をクロールする',
  ],
  _抓取本排行榜作品: [
    '抓取本排行榜作品',
    '擷取本排行榜作品',
    'Crawl the works in this list',
    'このリストの作品をクロールする',
  ],
  _抓取本排行榜作品Title: [
    '抓取本排行榜的所有作品，包括现在尚未加载出来的。',
    '擷取本排行榜的所有作品，包括現在尚未載入出來的。',
    'Crawl all of the works in this list, including those that are not yet loaded.',
    'まだ読み込まれていないものを含めて、このリストの作品をダウンロードする',
  ],
  _抓取首次登场的作品: [
    '抓取首次登场作品',
    '擷取首次登場作品',
    'Crawl the debut works',
    '初登場作品をダウンロードする',
  ],
  _抓取首次登场的作品Title: [
    '只下载首次登场的作品',
    '只下載首次登場的作品',
    'Download only debut works',
    '初登場作品のみダウンロードします',
  ],
  _抓取该页面的图片: [
    '抓取该页面的图片',
    '擷取該頁面的圖片',
    'Crawl the image of the page',
    'ページの画像をクロールする',
  ],
  _抓取相似图片: [
    '抓取相似图片',
    '擷取相似圖片',
    'Crawl similar works',
    '類似の作品をクロールする',
  ],
  _想要获取多少个作品: [
    '您想要获取多少个作品？',
    '想要取得多少個作品？',
    'How many works do you want to download?',
    'いくつの作品をダウンロードしたいですか？',
  ],
  _数字提示1: [
    '-1, 或者大于 0',
    '-1，或是大於 0',
    '-1, or greater than 0',
    '-1、または 0 より大きい',
  ],
  _下载大家的新作品: [
    '下载大家的新作品',
    '下載大家的新作品',
    'Download everyone`s new work',
    'みんなの新作をダウンロードする',
  ],
  _屏蔽设定: ['屏蔽設定', '封鎖設定', 'Mute settings', 'ミュート設定'],
  _举报: ['举报', '回報', 'Report', '報告'],
  _输入id进行抓取: [
    '输入 id 进行抓取',
    '輸入 id 進行擷取',
    'Type id to crawl',
    'idを入力してダウンロードする',
  ],
  _输入id进行抓取的提示文字: [
    '请输入作品 id。如果有多个 id，则以换行分割（即每行一个id）',
    '請輸入作品 id。如果有多個 id，則以換行分隔（即每行一個 id）。',
    'Please type the illustration id. If there is more than one id, one id per line.',
    'イラストレーターIDを入力してください。 複数の id がある場合は、1 行に 1 つの id を付けます。',
  ],
  _开始抓取: ['开始抓取', '開始擷取', 'Start crawl', 'クロールを開始する'],
  _给未分类作品添加添加tag: [
    '给未分类作品添加标签',
    '幫未分類的作品加入標籤',
    'Add tag to unclassified work',
    '未分類の作品にタグを追加',
  ],
  _id不合法: ['id不合法', 'id 不合法', 'id is illegal', 'id が不正な'],
  _快速收藏: [
    '快速收藏',
    '快速收藏',
    'Quick bookmarks',
    'クイックブックマーク',
  ],
  _启用: ['启用', '啟用', 'Enable', '有効にする'],
  _自动开始下载: [
    '<span class="key">自动</span>开始下载',
    '<span class="key">自動</span>開始下載',
    'Download starts <span class="key">automatically</span>',
    'ダウンロードは自動的に開始されます',
  ],
  _快速下载的提示: [
    '当“开始下载”状态可用时，自动开始下载，不需要点击下载按钮。',
    '當可下載時自動開始下載，不需要點選下載按鈕。',
    'When the &quot;Start Downloa&quot; status is available, the download starts automatically and no need to click the download button.',
    '「ダウンロードを開始する」ステータスが利用可能になると、ダウンロードは自動的に開始され、ダウンロードボタンをクリックする必要はありません。',
  ],
  _转换任务提示: [
    '正在转换 {} 个文件',
    '正在轉換 {} 個檔案',
    'Converting {} files',
    '{} ファイルの変換',
  ],
  _最近更新: ['最近更新', '最近更新', 'What`s new', '最近更新する'],
  _确定: ['确定', '確定', 'Ok', '確定'],
  _file404: [
    '404 错误：文件 {} 不存在。',
    '404 錯誤：檔案 {} 不存在。',
    '404 error: File {} does not exist.',
    '404 エラー：ファイル {} は存在しません。',
  ],
  _文件下载失败: [
    '文件 {} 下载失败',
    '檔案 {} 下載失敗',
    'File {} download failed',
    'ファイル {} のダウンロードを失敗しました',
  ],
  _是否重置设置: [
    '是否重置设置？',
    '確定要重設設定嗎？',
    'Do you want to reset the settings?',
    '設定をリセットしますか？',
  ],
  _newver: [
    '有新版本可用',
    '有新版本可更新',
    'A new version is available',
    '新しいバージョンがあります',
  ],
  _快速下载建立文件夹: [
    '快速下载时，始终建立文件夹',
    '快速下載時，始終建立資料夾',
    'Always create folder when downloading quickly',
    'クイックダウンロード時、常にフォルダを作成します',
  ],
  _id范围: [
    '<span class="key">ID</span> 范围',
    '<span class="key">ID</span> 範圍',
    '<span class="key">ID</span> range',
    '<span class="key">ID</span> 範囲',
  ],
  _设置id范围提示: [
    '您可以输入一个作品 id，抓取比它新或者比它旧的作品',
    '可以輸入一個作品 id，擷取比它新或者比它舊的作品。',
    'You can type a work id and crawl works that are newer or older than it',
    '1 つの作品 id を入力することで、それより新しいあるいは古い作品をクロールことができます',
  ],
  _大于: ['大于', '大於', 'Bigger than', 'より大きい'],
  _小于: ['小于', '小於', 'Less than', 'より小さい'],
  _投稿时间: [
    '投稿<span class="key">时间</span>',
    '投稿<span class="key">時間</span>',
    'Posting <span class="key">date</span>',
    '投稿日時',
  ],
  _设置投稿时间提示: [
    '您可以下载指定时间内发布的作品',
    '可以下載指定時間內發布的作品。',
    'You can download works posted in a specified period of time',
    '指定された時間内に配信された作品をダウンロードすることができます',
  ],
  _时间范围: ['时间范围', '時間範圍', 'Time range', '時間範囲'],
  _必须大于0: [
    '必须大于 0',
    '必須大於 0',
    'must be greater than 0',
    '0 より大きくなければなりません',
  ],
  _开始筛选: ['开始筛选', '開始篩選', 'Start screening', 'スクリーニング開始'],
  _开始筛选Title: [
    '按照设置来筛选当前标签里的作品。',
    '按照設定來篩選目前標籤裡的作品。',
    'Screen the works in the current tag.',
    '現在のタグにある作品を設定によってスクリーニングする',
  ],
  _在结果中筛选: [
    '在结果中筛选',
    '在結果中篩選',
    'Screen in results',
    '結果の中からスクリーニング',
  ],
  _在结果中筛选说明: [
    '您可以改变设置，并在结果中再次筛选。',
    '可以變更設定，並在結果中再次篩選。',
    'You can change the settings and screen again in the results.',
    '設定を変えて、結果の中で再びスクリーニングすることができます。',
  ],
  _抓取筛选结果: [
    '抓取筛选结果',
    '擷取篩選結果',
    'Crawl the screening results',
    'スクリーニングの結果をクロールする',
  ],
  _尚未开始筛选: [
    '尚未开始筛选',
    '尚未開始篩選',
    'Screening has not started',
    'まだスクリーニングを開始していない',
  ],
  _没有数据可供使用: [
    '没有数据可供使用',
    '沒有資料可供使用',
    'No data is available.',
    '使用可能なデータはない',
  ],
  _预览搜索结果: [
    '<span class="key">预览</span>搜索页面的筛选结果',
    '<span class="key">預覽</span>搜尋頁面的篩選結果',
    '<span class="key">Preview</span> filter results on search page',
    '検索ページのフィルタ結果をプレビューします',
  ],
  _预览搜索结果说明: [
    '下载器可以把符合条件的作品显示在当前页面上。如果抓取结果太多导致页面崩溃，请关闭这个功能。<br>启用预览功能时，下载器不会自动开始下载。',
    '下載器可以將符合條件的作品顯示在目前頁面上。如果擷取結果太多導致頁面當掉，請關閉這個功能。<br>啟用預覽功能時，下載器不會自動開始下載。',
    'The downloader can display the qualified works on the current page. If too many crawling results cause the page to crash, turn off this feature.<br>When the preview feature is enabled, the downloader does not start downloading automatically.',
    'ローダは、該当する作品を現在のページに表示することができます。クロール結果が多すぎてページが崩れる場合は、この機能をオフにしてください。<br>プレビュー機能を有効にすると、ダウンロードは自動的に開始されません。',
  ],
  _目录名使用: [
    '目录名使用：',
    '資料夾名稱使用：',
    'Name: ',
    'ディレクトリ名の使用：',
  ],
  _目录名: ['目录名', '資料夾名稱', 'Name', 'ディレクトリ名'],
  _启用快速收藏: [
    '启用快速收藏',
    '開啟快速收藏',
    'Enable quick bookmark',
    'クイックボックマークを有効にする',
  ],
  _启用快速收藏说明: [
    '当你点击下载器添加的收藏按钮(☆)，把作品添加到书签时，自动添加这个作品的标签。',
    '當點選下載器新增的收藏按鈕（☆），將作品加入書籤時，自動新增這個作品的標籤。',
    'When you click the favorite button (☆) added by the downloader to bookmark a work, the tag of the work is automatically added.',
    'ダウンローダーに追加されたボックマークボタン「☆」をクリックして、作品をブックマークに追加すると、自動的に作品のタグが追加されます。',
  ],
  _新增设置项: [
    '新增设置项',
    '新增設定項目',
    'Added setting items',
    '新たな機能を追加されました',
  ],
  _抓取: ['抓取', '擷取', 'Crawl', 'クロール'],
  _下载: ['下载', '下載', 'Download', 'ダウンロード'],
  _其他: ['其他', '其他', 'Other', 'その他'],
  _更多: ['更多', '更多', 'More', 'もっと'],
  _第一张图不带序号: [
    '第一张图不带<span class="key">序号</span>',
    '第一張圖片不包含<span class="key">序號</span>',
    'The first image without a <span class="key">serial number</span>',
    '最初のイメージの番号を削除',
  ],
  _第一张图不带序号说明: [
    '去掉每个作品第一张图的序号。例如 80036479_p0 变成 80036479',
    '去掉每個作品第一張圖的序號。例如：80036479_p0 變成 80036479。',
    'Remove the serial number of the first image of each work. For example 80036479_p0 becomes 80036479.',
    '作品ごとの最初のイメージの番号を削除します。例えば 80036479_p0 は 80036479 になります。',
  ],
  _最小值: ['最小值', '最小值', 'Minimum', '最小値'],
  _最大值: ['最大值', '最大值', 'Maximum', '最大値'],
  _单图作品: [
    '单图作品',
    '單圖作品',
    'Single image works',
    'シングルイメージ作品',
  ],
  _彩色图片: ['彩色图片', '彩色圖片', 'Color images', 'カラーイメージ'],
  _黑白图片: ['黑白图片', '黑白圖片', 'Black and white images', '白黒イメージ'],
  _不保存图片因为颜色: [
    '{} 没有被保存，因为它的颜色不符合设定。',
    '{} 並未儲存，因為它的色彩不符合設定。',
    '{} was not saved because its colors do not match the settings.',
    '{} は色が設定に合わないため、保存されていません。',
  ],
  _同时转换多少个动图: [
    '同时<span class="key">转换</span>多少个动图',
    '同時<span class="key">轉換</span>多少個動圖',
    'How many animations are <span class="key">converted</span> at the same time',
    '同時変換のうごイラの上限',
  ],
  _同时转换多少个动图警告: [
    '同时转换多个动图会增加资源占用。<br>转换动图时，请保持该标签页激活，否则浏览器会降低转换速度。',
    '同時轉換多個動圖會增加資源占用。<br>轉換動圖時，請保持這個分頁啟動，否則瀏覽器會降低轉換速度。',
    'Converting multiple animations at the same time will increase resource consumption. <br> Please keep the tab active when converting animation, otherwise the browser will reduce the conversion speed.',
    '複数の動画を同時に変換すると、リソースの占有が増加します。<br>うごイラを変換するときは、このタブを有効にしてください。そうしないと、ブラウザは変換速度を下げます。',
  ],
  _提示: ['提示', '提示', 'Tip', 'ヒント'],
  _提示2: ['提示', '提示', 'Tip', '？'],
  _fanboxDownloader: [
    'Fanbox 下载器',
    'Fanbox 下載器',
    'Fanbox Downloader',
    'Fanbox ダウンロード',
  ],
  _不保存图片因为体积: [
    '{} 没有被保存，因为它的体积不符合设定。',
    '{} 並未儲存，因為它的大小不符合設定。',
    '{} was not saved because its size do not match the settings.',
    '{} はファイルサイズが設定に合わないため、保存されていません。',
  ],
  _文件体积限制: [
    '文件<span class="key">体积</span>限制',
    '檔案<span class="key">體積</span>限制',
    'File <span class="key">size</span> limit',
    'ファイルサイズ制限',
  ],
  _不符合要求的文件不会被保存: [
    '不符合要求的文件不会被保存。',
    '不會儲存不符合要求的檔案。',
    'Files that do not meet the requirements will not be saved.',
    '設定 に合わないファイルは保存されません。',
  ],
  _小说: ['小说', '小說', 'Novel', '小説'],
  _抓取系列小说: [
    '抓取系列小说',
    '擷取系列小說',
    'Crawl series of novels',
    '小説のシリーズをクロールする',
  ],
  _合并系列小说: [
    '合并系列小说',
    '合併系列小說',
    'Merge series of novels',
    'シリーズ小説の統合',
  ],
  _小说保存格式: [
    '<span class="key">小说</span>保存格式',
    '<span class="key">小說</span>儲存格式',
    'Save the <span class="key">novel</span> as',
    '<span class="key">小説</span>の保存形式',
  ],
  _在小说里保存元数据: [
    '在小说里保存<span class="key">元数据</span>',
    '在小說裡儲存<span class="key">元資料</span>',
    'Save <span class="key">metadata</span> in the novel',
    '小説の中にメタデータを保存する',
  ],
  _在小说里保存元数据提示: [
    '把作者、网址等信息保存到小说里',
    '將作者、網址等資訊儲存到小說裡',
    'Save the author, URL and other information in the file',
    '作者やURLなどの情報をファイルの中に保存します。',
  ],
  _收藏本页面的所有作品: [
    '收藏本页面的所有作品',
    '收藏本頁面的所有作品',
    'Bookmark all works on this page',
    'この頁の全ての作品をブックマークに追加します',
  ],
  _输出内容太多已经为你保存到文件: [
    '因为输出内容太多，已经为您保存到文件。',
    '因為輸出內容太多，已經為你儲存到檔案。',
    'Because the output is too much, it has been saved to a file.',
    '出力内容が多いため、txt ファイルに保存しました。',
  ],
  _不下载重复文件: [
    '不下载<span class="key">重复</span>文件',
    '不下載<span class="key">重複</span>檔案',
    'Don`t download <span class="key">duplicate</span> files',
    '重複ファイルをダウンロードしない',
  ],
  _不下载重复文件的提示: [
    '下载器会保存自己的下载记录，以避免下载重复的文件。<br>当你清除 Cookie 和其他站点数据时，下载器的记录也会被清除。',
    '下載器會儲存自己的下載紀錄，以避免下載重複的檔案。<br>當你清除 Cookie 和其他站點資料時，下載器的紀錄也會被清除。',
    `The downloader will save its download record to avoid downloading duplicate files.<br>When you clear cookies and other site data, the downloader's records will also be cleared.`,
    'ダウンローダーは独自のダウンロード履歴を保存して、重複ファイルのダウンロードを回避する。<br>cookie と他のサイトデータを削除すると、ダウンローダーの記録も削除されます。',
  ],
  _策略: ['策略：', '策略：', 'Strategy:', 'フィルター：'],
  _严格: ['严格', '嚴格', 'Strict', '厳格'],
  _宽松: ['宽松', '寬鬆', 'Loose', '緩い'],
  _严格模式说明: [
    '判断条件：作品的 id、上传日期、文件名',
    '判斷條件：作品的 id、上傳日期、檔名',
    'Judgment conditions: id, upload date, file name of the work',
    '審査条件：作品のID、アップロード日、ファイル名',
  ],
  _宽松模式说明: [
    '判断条件：作品的 id、上传日期',
    '判斷條件：作品的 id、上傳日期',
    'Judgment conditions: id, upload date of the work',
    '審査条件：作品のID、アップロード日',
  ],
  _清除下载记录: [
    '清除下载记录',
    '清除下載紀錄',
    'Clear download record',
    '履歴をクリア',
  ],
  _下载记录已清除: [
    '下载记录已清除',
    '已清除下載紀錄',
    'Download record has been cleared',
    'ダウンロード履歴がクリアされました',
  ],
  _跳过下载因为重复文件: [
    '检测到文件 {} 已经下载过，跳过此次下载',
    '偵測到檔案 {} 已經下載過，跳過此次下載。',
    'Skip downloading duplicate files {}',
    '重複ファイル {} をスキップ',
  ],
  _保存用户头像为图标: [
    '保存用户头像为图标',
    '將使用者頭貼另存為圖示檔案',
    'Save user avatar as icon',
    'プロフィール画像をアイコンとして保存',
  ],
  _保存用户头像为图标说明: [
    '把用户头像保存为 ico 文件，可以手动设置成文件夹的图标。',
    '將使用者頭貼儲存為 ico 檔案，可以手動設定成資料夾圖示。',
    'Save user avatar as icon',
    'ユーザーのプロフィール画像を ico ファイルとして保存して、フォルダーアイコンとして設定できます。',
  ],
  _正在保存抓取结果: [
    '正在保存抓取结果',
    '正在儲存擷取結果',
    'Saving crawl results',
    'クロール結果を保存しています',
  ],
  _已保存抓取结果: [
    '已保存抓取结果',
    '已儲存擷取結果',
    'Crawl results saved',
    'クロール結果を保存しました',
  ],
  _正在恢复抓取结果: [
    '正在恢复抓取结果',
    '正在還原擷取結果',
    'Restoring crawl results',
    'クロール結果を再開しています',
  ],
  _已恢复抓取结果: [
    '已恢复抓取结果',
    '已還原擷取結果',
    'Crawl results resumed',
    'クロール結果を再開しました',
  ],
  _清空已保存的抓取结果: [
    '清空已保存的抓取结果',
    '清除已儲存的擷取結果',
    'Clear saved crawl results',
    'セーブしたクロール結果をクリアします',
  ],
  _数据清除完毕: [
    '数据清除完毕',
    '資料清除完畢',
    'Data cleared',
    'クリアされたデータ',
  ],
  _已跳过n个文件: [
    '已跳过 {} 个文件',
    '已跳過 {} 個檔案',
    '{} files skipped',
    '{} つのファイルをスキップしました',
  ],
  _不保存图片因为宽高: [
    '{} 没有被保存，因为它的宽高不符合设定。',
    '{} 並未儲存，因為它的寬高不符合設定。',
    '{} was not saved because its width and height do not match the settings.',
    '{} は幅と高さが設定に合わないため、保存されていません。',
  ],
  _显示下载面板: [
    '显示下载面板 (Alt + X)',
    '顯示下載面板 (Alt + X)',
    'Show download panel (Alt + X)',
    'ダウンロードパネルを表示 (Alt + X)',
  ],
  _保存: ['保存', '儲存', 'Save', '保存'],
  _加载: ['加载', '載入', 'Load', 'ロード'],
  _保存命名规则提示: [
    '保存命名规则，最多 20 个',
    '儲存命名規則，最多 20 個',
    'Save naming rule, up to 20',
    '命名規則を保存します。最大 20 個まで',
  ],
  _已保存命名规则: [
    '已保存命名规则',
    '已儲存命名規則',
    'Naming rule saved',
    '命名規則を保存しました',
  ],
  _命名: ['命名', '命名', 'Name', '命名'],
  _无损: ['无损', '無損', 'Lossless', 'ロスレス'],
  _文件名长度限制: [
    '文件名<span class="key">长度</span>限制',
    '檔案名稱<span class="key">長度</span>限制',
    'File name <span class="key">length</span> limit',
    'ファイル名の長さ制限',
  ],
  _导出csv: [
    '导出 CSV 文件',
    '匯出 CSV 檔',
    'Export CSV file',
    'CSV ファイルをエクスポート',
  ],
  _导出抓取结果: [
    '导出抓取结果',
    '匯出擷取結果',
    'Export results',
    'クロール結果をエクスポート',
  ],
  _导入抓取结果: [
    '导入抓取结果',
    '匯入擷取結果',
    'Import results',
    'クロール結果をインポート',
  ],
  _导入成功: ['导入成功', '匯入成功', 'Import successfully', 'インポート成功'],
  _导出成功: [
    '导出成功',
    '匯出成功',
    'Export successfully',
    'エクスポート成功',
  ],
  _图片尺寸: [
    '图片<span class="key">尺寸</span>',
    '圖片<span class="key">尺寸</span>',
    'Image <span class="key">size</span>',
    '画像<span class="key">サイズ</span>',
  ],
  _图片尺寸2: ['图片尺寸', '圖片尺寸', 'Image size', '画像サイズ'],
  _原图: ['原图', '原圖', 'Original', 'Original'],
  _普通: ['普通', '普通', 'Regular', 'Regular'],
  _小图: ['小图', '小圖', 'Small', 'Small'],
  _方形缩略图: [
    '方形缩略图',
    '方形縮圖',
    'Square thumbnail',
    'Square thumbnail',
  ],
  _导出: ['导出', '匯出', 'Export', 'エクスポート'],
  _导入: ['导入', '匯入', 'Import', 'インポート'],
  _清除: ['清除', '清除', 'Clear', 'クリア'],
  _导入下载记录: [
    '导入下载记录',
    '匯入下載紀錄',
    'Import download record',
    'ダウンロード記録をインポート',
  ],
  _完成: ['完成', '完成', 'Completed', '完了'],
  _日期格式: [
    '日期和时间<span class="key">格式</span>',
    '日期和時間<span class="key">格式</span>',
    'Date and time <span class="key">format</span>',
    '日付と時刻の書式',
  ],
  _日期格式提示: [
    '你可以使用以下标记来设置日期和时间格式。这会影响命名规则里的 {date} 和 {task_date}。<br>对于时间如 2021-04-30T06:40:08',
    '你可以使用以下標記來設定日期和時間格式。這會影響命名規則裡的 {date} 和 {task_date}。<br>對於資料如：2021-04-30T06:40:08。',
    'You can use the following notation to set the date and time format. This will affect {date} and {task_date} in the naming rules. <br>For time such as 2021-04-30T06:40:08',
    '以下のタグを使用して日時と時刻の書式を設定することができます。 これは命名規則の {date} と {task_date} に影響します。 <br> 例：2021-04-30T06:40:08',
  ],
  _命名标记taskDate: [
    '本次任务抓取完成时的时间。例如：2020-10-21',
    '本次工作擷取完成時的時間。例如：2020-10-21。',
    'The time when the task was crawl completed. For example: 2020-10-21',
    'この作業のクロールが完了した時刻です。 例：2020-10-21',
  ],
  _自动检测: ['自动检测', '自動偵測', 'Auto', '自動検出'],
  _变更语言后刷新页面的提示: [
    '更换语言后，请刷新页面。',
    '變更語言後，請重新整理頁面。',
    'Please refresh the page after changing the language.',
    '言語を変更した後は、ページを更新してください。',
  ],
  _公开: ['公开', '公開', 'Public', '公開'],
  _不公开: ['不公开', '非公開', 'Private', '非公開'],
  _已收藏: ['已收藏', '已收藏', 'Bookmarked', 'ブックマークした'],
  _已收藏带参数: [
    '已收藏 {}',
    '已收藏 {}',
    'Bookmarked {}',
    'ブックマークした {}',
  ],
  _未收藏: ['未收藏', '未收藏', 'Not bookmarked', 'ブックマークされていない'],
  _下载之后收藏作品: [
    '下载之后<span class="key">收藏</span>作品',
    '下載之後<span class="key">收藏</span>作品',
    '<span class="key">Bookmark</span> works after downloading',
    'ダウンロードした作品をブックマークする',
  ],
  _下载之后收藏作品的提示: [
    '下载文件之后，自动收藏这个作品。',
    '下載檔案之後，自動收藏這個作品。',
    'After you download a file, the downloader will automatically bookmark the work.',
    'ダウンロード後、作品は自動的にブックマークされます。',
  ],
  _收藏设置: [
    '下载器的<span class="key">收藏</span>按钮 (✩)',
    '下載器的<span class="key">收藏</span>按鈕 (✩)',
    `Downloader's <span class="key">bookmark</span> button (✩)`,
    'ダウンローダーの<span class="key">ブックマーク</span>ボタン (✩)',
  ],
  _添加tag: ['添加标签', '加入標籤', 'Add tag', 'タグを追加'],
  _不添加tag: ['不添加标签', '不加入標籤', "Don't add tag", 'タグなし'],
  _用户阻止名单: [
    '用户<span class="key">阻止</span>名单',
    '使用者<span class="key">阻止</span>名單',
    'User <span class="key">block</span> list',
    'ユーザーブロックリスト',
  ],
  _用户阻止名单的说明: [
    '不下载这些用户的作品。需要输入用户 id。如果有多个用户 id，使用英文逗号,分割。',
    '不下載這些使用者的作品。需要輸入使用者 id。若有多個使用者 id，使用半形逗號（,）分隔。',
    'The works of these users will not be downloaded. Need to type the user ID. If there are multiple user ID, use comma (,) separated.',
    'これらのユーザーの作品はダウンロードしません。ユーザー ID が必要です。複数のユーザ ID は "," で区切ってください。',
  ],
  _全部: ['全部', '全部', 'All', '全部'],
  _任一: ['任一', '任一', 'One', '何れか'],
  _颜色主题: [
    '颜色<span class="key">主题</span>',
    '色彩<span class="key">主題</span>',
    'Color <span class="key">theme</span>',
    'カラーテーマ',
  ],
  _管理设置: [
    '管理<span class="key">设置</span>',
    '管理<span class="key">設定</span>',
    'Manage <span class="key">settings</span>',
    '<span class="key">設定</span>の管理',
  ],
  _导出设置: ['导出设置', '匯出設定', 'Export settings', 'エクスポート設定'],
  _导入设置: ['导入设置', '匯入設定', 'Import settings', 'インポート設定'],
  _重置设置: ['重置设置', '重設設定', 'Reset settings', 'リセット設定'],
  _日均收藏数量: [
    '日均收藏数量',
    '日均收藏數量',
    'Average number of daily bookmarks',
    '1 日の平均ブックマーク数',
  ],
  _日均收藏数量的提示: [
    '你可以设置作品的平均每日收藏数量。满足条件的作品会被下载。',
    '您可以設定作品的平均每日收藏數量。滿足條件的作品會被下載。',
    'You can set the average daily bookmarks number of works. Works that meet the conditions will be downloaded.',
    '作品の 1 日の平均ブックマーク数を設定することができます。条件を満した作品はダウンロードされます。',
  ],
  _下载用户列表: [
    '下载用户列表',
    '下載使用者列表',
    'Download users list',
    'ユーザーリストのダウンロード',
  ],
  _手动选择作品: [
    '手动选择作品',
    '手動選擇作品',
    'Manually select',
    '手動で作品を選ぶ',
  ],
  _抓取选择的作品: [
    '抓取选择的作品',
    '擷取選擇的作品',
    'Crawl selected works',
    '選ばれた作品をクロール',
  ],
  _抓取选择的作品2: [
    '抓取选择的作品 {}',
    '擷取選擇的作品 {}',
    'Crawl selected works {}',
    '選ばれた作品をクロール {}',
  ],
  _清空选择的作品: [
    '清空选择的作品',
    '清空選擇的作品',
    'Clear selected works',
    '選んだ作品をクリアします',
  ],
  _暂停选择: ['暂停选择', '暫停選擇', 'Pause select', '選択を一時停止'],
  _继续选择: ['继续选择', '繼續選擇', 'Continue select', '選択を続ける'],
  _离开页面前提示选择的作品未抓取: [
    '选择的作品尚未抓取。现在离开此页面会导致你选择的作品被清空。',
    '選擇的作品尚未擷取。現在離開此頁面會導致您選擇的作品被清空。',
    'The selected work has not been crawled. Leaving this page now will cause your selected work to be cleared.',
    '選ばれた作品はまだクロールしていません。今このページを離れると、選ばれた作品がクリアされます。',
  ],
  _排除了所有作品类型: [
    '排除了所有作品类型',
    '排除了所有作品類型',
    'Excluded all work types',
    'すべての作品種類を除外しました',
  ],
  _为作品建立单独的文件夹: [
    '为<span class="key">每个</span>作品建立单独的文件夹',
    '為<span class="key">每個</span>作品建立單獨的資料夾',
    'Create a separate folder for <span class="key">each</span> work',
    '作品ごとに別フォルダを作成',
  ],
  _为作品建立单独的文件夹说明: [
    '这里应该使用 {id_num} 代替 {id}',
    '這裡應該使用 {id_num} 代替 {id}',
    'Here {id_num} should be used instead of {id}',
    'ここでは、{id} の代わりに {id_num} を使用する必要があります',
  ],
  _文件数量大于: [
    '文件数量 >',
    '檔案數量 >',
    'Number of files >',
    'ファイル数 >',
  ],
  _保存用户头像: [
    '保存用户头像',
    '儲存使用者頭貼',
    'Save user avatar',
    'ユーザーアイコンの保存',
  ],
  _保存用户封面: [
    '保存用户封面',
    '儲存使用者封面',
    'Save user cover',
    'ユーザーカバーの保存',
  ],
  _待处理: ['待处理', '待處理', 'Pending', '処理待ち'],
  _超出最大页码: [
    '超出最大页码：',
    '超出最大頁碼：',
    'Maximum page number exceeded:',
    '最大ページ数を超えました：',
  ],
  _针对特定用户屏蔽tag: [
    '针对特定用户屏蔽<span class="key">标签</span>',
    '針對特定使用者排除<span class="key">標籤</span>',
    'Block <span class="key">tags</span> for specific users',
    '特定のユーザーに対して<span class="key">タグ</span>をブロック',
  ],
  _展开收起: ['展开/收起', '展開/摺疊', 'Expand/Collapse', '展開/折りたたみ'],
  _展开: ['展开', '展開', 'Expand', '展開'],
  _收起: ['收起', '摺疊', 'Collapse', '折りたたみ'],
  _把r18作品存入指定的文件夹里: [
    '把 <span class="key">R-18(G)</span> 作品存入指定的文件夹里',
    '把 <span class="key">R-18(G)</span> 作品存入指定的資料夾裡',
    'Save the <span class="key">R-18(G)</span> works in the designated folder',
    '<span class="key">R-18(G)</span> の作品を指定のフォルダに入れる',
  ],
  _必填项不能为空: [
    '必填项不能为空',
    '必填項不能為空',
    'Required fields cannot be empty',
    '必須フィールドが入力されていません',
  ],
  _用户ID必须是数字: [
    '用户 ID 必须是数字',
    '使用者 ID 必須是數字',
    'User ID must be a number',
    'ユーザー ID は数字です',
  ],
  _必须是数字: [
    '必须是数字',
    '必須是數字',
    'Number',
    '数字でなければなりません',
  ],
  _tag用逗号分割: [
    '多个标签使用英文逗号,分割',
    '多個標籤使用半形逗號（,）分隔',
    'Multiple tags use comma (,) split',
    '複数のタグはカンマ「,」で区切ってください',
  ],
  _添加: ['添加', '新增', 'Add', '追加'],
  _取消: ['取消', '取消', 'Cancel', 'キャンセル'],
  _更新: ['更新', '更新', 'Update', '更新'],
  _删除: ['删除', '刪除', 'Delete', '削除'],
  _添加成功: ['添加成功', '新增成功', 'Added successfully', '追加されました'],
  _更新成功: ['更新成功', '更新成功', 'update completed', '更新成功'],
  _在作品缩略图上显示放大按钮: [
    '在作品缩略图上显示<span class="key">放大</span>按钮',
    '在作品縮圖上顯示<span class="key">放大</span>按鈕',
    'Show <span class="key">zoom</span> button on thumbnail',
    '作品のサムネイルに<span class="key">拡大</span>ボタンを表示',
  ],
  _在作品缩略图上显示下载按钮: [
    '在作品缩略图上显示<span class="key">下载</span>按钮',
    '在作品縮圖上顯示<span class="key">下載</span>按鈕',
    'Show <span class="key">download</span> button on thumbnail',
    '作品のサムネイルに<span class="key">ダウンロード</span>ボタンを表示',
  ],
  _已发送下载请求: [
    '已发送下载请求',
    '已傳送下載請求',
    'Download request sent',
    'ダウンロードリクエストを送信しました',
  ],
  _HowToUse: [
    '点击页面右侧的蓝色按钮可以打开下载器面板。',
    '點選頁面右側的藍色按鈕可以開啟下載器面板。',
    'Click the blue button on the right side of the page to open the downloader panel.',
    'ページ右側の青いボタンをクリックすると、ダウンローダーパネルが開きます。',
  ],
  _我知道了: ['我知道了', '我知道了', 'OK', '分かりました'],
  _背景图片: [
    '<span class="key">背景</span>图片',
    '<span class="key">背景</span>圖片',
    '<span class="key">Background</span> image',
    '<span class="key">背景</span>画像',
  ],
  _选择文件: ['选择文件', '選擇檔案', 'Select a file', 'ファイルを選択'],
  _不透明度: ['不透明度', '不透明度', 'Opacity', '不透明度'],
  _对齐方式: ['对齐方式', '對齊方式', 'Alignment', '揃え方式'],
  _顶部: ['顶部', '頂部', 'top', '上揃え'],
  _居中: ['居中', '居中', 'center', '中央揃え'],
  _根据作品类型自动建立文件夹: [
    '根据作品<span class="key">类型</span>自动建立文件夹',
    '根據作品<span class="key">類型</span>自動建立資料夾',
    'Create folders based on the <span class="key">type</span> of work',
    '作品種類に応じてフォルダを自動作成',
  ],
  _使用第一个匹配的tag建立文件夹: [
    '使用第一个匹配的<span class="key">标签</span>建立文件夹',
    '使用第一個符合的<span class="key">標籤</span>建立資料夾',
    'Create a folder with the first matched <span class="key">tag</span>',
    '最初の一致するタグにフォルダを作成',
  ],
  _使用匹配的tag建立文件夹的说明: [
    '如果作品的标签列表里含有用户设置的标签，就会使用这个标签建立文件夹（仅限第一个）',
    '如果作品的標籤列表裡含有使用者設定的標籤，就會使用這個標籤建立資料夾（僅限第一個）',
    'If the tag list of the work contains a tag set by the user, this tag will be used to create a folder (only the first one)',
    '作品のタグリストにユーザーが設定したタグが含まれている場合、そのタグを使用してフォルダが作成されます。(最初の1つだけ)',
  ],
  _全年龄: ['全年龄', '全年齡', 'All ages', '全年齢'],
  _没有符合条件的结果: [
    '没有符合条件的结果',
    '沒有符合條件的結果',
    'There are no eligible results',
    '対象となる結果はありません',
  ],
  _收藏: ['收藏', '收藏', 'Bookmark', 'ブックマーク'],
  _已加入收藏: ['已加入收藏', '已加入收藏', 'Bookmarked', 'ブックマークした'],
  _全屏查看: ['全屏', '全螢幕', 'Full screen view', '全画面表示'],
  _抓取id区间: [
    '抓取 id 区间',
    '擷取 id 區間',
    'Crawl id range',
    'id 範囲をクロール',
  ],
  _抓取id区间说明: [
    '你可以设置一个作品 id 范围，抓取此范围内的所有作品（包含开始和结束的 id）。\n注意：如果一次任务中产生的抓取结果数量太多，可能会导致页面崩溃。',
    '你可以設定一個作品 id 範圍，擷取此範圍內的所有作品（包含開始和結束的 id）。\n注意：如果一次任務中產生的擷取結果數量太多，可能會導致頁面崩潰。',
    'You can set a range of work id and grab all works in this range (including the begin and end id). \nNote: If the number of crawling results in a task is too much, it may cause the page to crash.',
    '作品 id の範囲を設定し、その範囲内のすべての作品をクロールすることができます。「開始 id と終了 id を含む」\n注意：1 つのタスクであまりにも多くのクロール結果を生成すると、ページがクラッシュする可能性があります。',
  ],
  _抓取id区间起点: [
    '请输入开始的 id',
    '請輸入開始的 id',
    'Please type in the beginning id',
    '開始 id を入力してください',
  ],
  _抓取id区间终点: [
    '请输入结束的 id',
    '請輸入結束的 id',
    'Please type  in the ending id',
    '終了 id を入力してください',
  ],
  _选项卡切换方式: [
    '<span class="key">选项卡</span>切换方式',
    '<span class="key">頁籤</span>切換方式',
    'How to switch <span class="key">tabs</span>',
    'タブ切り替え方式',
  ],
  _鼠标经过: ['鼠标经过', '滑鼠經過', 'Mouse over', 'マウスオーバー'],
  _鼠标点击: ['鼠标点击', '滑鼠點選', 'Mouse click', 'マウスクリック'],
  _在序号前面填充0: [
    '在序号前面<span class="key">填充 0</span>',
    '在序號前面<span class="key">填充 0</span>',
    '<span class="key">Add 0</span> in front of the serial number',
    'シリアル番号の前に 0 を記入',
  ],
  _序号总长度: [
    '序号总长度',
    '序號總長度',
    'Total length of serial number',
    'シリアル番号の全長',
  ],
  _完全一致: ['完全一致', '完全一致', 'Perfect match', '完全一致'],
  _部分一致: ['部分一致', '部分一致', 'Partial match', '部分一致'],
  _位置: ['位置', '位置', 'Position', '位置'],
  _左: ['左', '左', 'Left', '左'],
  _右: ['右', '右', 'Right', '右'],
  _多图作品只下载前几张图片: [
    '多图作品只下载<span class="key">前几张</span>图片',
    '多圖作品只下載<span class="key">前幾張</span>圖片',
    'Multi-image works only download the <span class="key">first few</span> images',
    'マルチ作品は最初の何枚の画像のみをダウンロードする',
  ],
  _多图作品的图片数量上限: [
    '多图作品的图片<span class="key">数量</span>上限',
    '多圖作品的圖片<span class="key">數量</span>上限',
    '<span class="key">Maximum number</span> of images for multi-image works',
    'マルチ作品の最大画像数',
  ],
  _超出此限制的多图作品不会被下载: [
    '超出此限制的多图作品不会被下载',
    '不會下載超出此限制的多圖作品',
    'Multi-image works exceeding this limit will not be downloaded',
    'この制限を超えたマルチ作品はダウンロードされません',
  ],
  _在搜索页面添加快捷搜索区域: [
    '在搜索页面添加快捷<span class="key">搜索</span>区域',
    '在搜尋頁面新增快速<span class="key">搜尋</span>區域',
    'Add a quick <span class="key">search</span> area on the search page',
    '検索ページにクイック検索領域を追加します',
  ],
  _保存作品的元数据: [
    '保存作品的<span class="key">元数据</span>',
    '儲存作品的<span class="key">元資料</span>',
    'Save the <span class="key">metadata</span> of the work',
    '作品のメタデータを保存する',
  ],
  _保存作品的元数据说明: [
    '为每个作品建立一个 txt 文件保存它的元数据',
    '為每個作品建立一個 txt 檔案儲存它的元資料',
    'Create a txt file for each work to save its metadata',
    '作品ごとに txt ファイルを作成して、メタデータを保存します',
  ],
  _在不同的页面类型中使用不同的命名规则: [
    '在不同的页面类型中使用<span class="key">不同</span>的命名规则',
    '在不同的頁面類型中使用<span class="key">不同</span>的命名規則',
    'Use <span class="key">different</span> naming rules in different page types',
    'ページの種類によって異なる命名規則を使用',
  ],
  _显示高级设置: [
    '显示<span class="key">高级</span>设置',
    '顯示<span class="key">進階</span>設定',
    'Show <span class="key">advanced</span> settings',
    '詳細設定を表示する',
  ],
  _显示高级设置说明: [
    '被隐藏的设置仍然会发挥作用',
    '被隱藏的設定仍然會發揮作用',
    'Hidden settings will still work',
    '隠していた設定がそのまま機能する',
  ],
  _状态码为0的错误提示: [
    '下载时发生错误，状态码为 0，请求未成功。可能的原因：<br><br>1. 系统磁盘的剩余空间可能不足（建议剩余空间大于 4GB）。请尝试清理系统磁盘空间，然后重新启动浏览器，继续未完成的下载。<br><br>2. 网络错误。可能是网络代理导致的问题。如果你使用 Nginx 或者 Apache 反代理访问 pixiv，请换成梯子。',
    '下載時發生錯誤，狀態碼為 0，請求未成功。可能的原因：<br><br>1. 系統磁碟的剩餘空間可能不足（建議剩餘空間大於 4GB）。請嘗試清理系統磁碟空間，然後重新啟動瀏覽器，繼續未完成的下載。<br><br>2. 網路錯誤。可能是網路代理導致的問題。',
    'An error occurred while downloading, the status code is 0, and the request was unsuccessful. Possible reasons: <br><br>1. The remaining space of the system disk may be insufficient (it is recommended that the remaining space be greater than 4GB). Please try to clear the system disk space, and then restart the browser to continue the unfinished download. <br><br>2. Network error. It may be a problem caused by a network proxy.',
    'ダウンロード中にエラーが発生し、ステータスコードは0で、リクエストは失敗しました。 考えられる理由：<br> <br> 1。 システムディスクの残りのスペースが不足している可能性があります（残りのスペースは4GBを超えることをお勧めします）。 システムのディスク領域をクリアしてから、ブラウザを再起動して、未完了のダウンロードを続行してください。 <br> <br> 2。 ネットワークエラー。 ネットワークプロキシが原因の問題である可能性があります。',
  ],
  _提示登录pixiv账号: [
    '请您登录 Pixiv 账号然后重试。',
    '請您登入 Pixiv 帳號後重試。',
    'Please log in to your Pixiv account and try again.',
    'Pixiv アカウントにログインして、もう一度お試しください。',
  ],
  _下载完成后显示通知: [
    '下载完成后显示<span class="key">通知</span>',
    '下載完成後顯示<span class="key">通知</span>',
    'Show <span class="key">notification</span> after download is complete',
    'ダウンロードが完了した後に通知を表示する',
  ],
  _高亮显示关键字: [
    '<span class="key">高亮</span>显示关键字',
    '<span class="key">標明</span>顯示關鍵字',
    '<span class="key">Highlight</span> keywords',
    'キーワードを強調表示',
  ],
  _抓取标签列表: [
    '抓取标签列表',
    '擷取標籤列表',
    'Crawl a list of tags',
    'タグのリストをクロール',
  ],
  _抓取标签列表的输入框提示: [
    '请输入你要抓取的标签列表。多个标签之间使用换行分割',
    '請輸入你要擷取的標籤列表。多個標籤之間使用換行分隔',
    'Please type the list of tags you want to crawl. Use line breaks between multiple tags',
    'クロールしたいタグのリストを入力してください。 複数のタグを改行で分割',
  ],
  _抓取标签列表的文件夹提示: [
    '在抓取标签列表时，你可以使用 {p_tag} 或者 {p_title} 标记获取当前抓取的标签，并用来建立文件夹。例如：{p_tag}/{id}',
    '在擷取標籤列表時，你可以使用 {p_tag} 或者 {p_title} 標記獲取目前擷取的標籤，並用來建立資料夾。例如：{p_tag}/{id}',
    'When crawling the tag list, you can use {p_tag} or {p_title} tags to get the tags currently crawled and use them to create folders. For example: {p_tag}/{id}',
    'タグリストをクロールする時に、 {p_tag} や {p_title}を使用すると、現在クロールされているタグを取得し、それらを使ってフォルダを作成することができます。例：{p_tag}/{id}',
  ],
  _停止抓取标签列表: [
    '停止抓取标签列表',
    '停止擷取標籤列表',
    'Stop crawling the list of tags',
    'タグリストのクロールを停止',
  ],
  _等待下载的标签: [
    '等待下载的标签',
    '等待下載的標籤',
    'Tags waiting to be downloaded',
    'ダウンロード待ちのタグ',
  ],
  _你确定要停止抓取吗: [
    '你确定要停止抓取吗？',
    '確定要停止擷取嗎？',
    'Are you sure you want to stop crawling?',
    '本当にクロールをやめたいのか',
  ],
  _只能在搜索页面使用: [
    '只能在搜索页面使用',
    '只能在搜尋頁面使用',
    'Can only be used on the search page',
    '検索ページでのみ使用できます',
  ],
  _自动导出抓取结果: [
    '自动<span class="key">导出</span>抓取结果',
    '自動<span class="key">匯出</span>擷取結果',
    'Automatically <span class="key">export</span> crawl results',
    'クロール結果の自動エクスポート',
  ],
  _抓取结果: ['抓取结果', '擷取結果', 'Crawl results', 'クロール結果'],
  _文件格式: ['文件格式', '檔案格式', 'File format', 'ファイル形式'],
  _格式: ['格式', '格式', 'Format', '形式'],
  _预览作品: [
    '<span class="key">预览</span>作品',
    '<span class="key">預覽</span>作品',
    '<span class="key">Preview</span> works',
    '作品のプレビュー',
  ],
  _点击鼠标左键可以关闭预览图: [
    '点击鼠标左键可以关闭预览图',
    '點選滑鼠左鍵可以關閉預覽圖',
    'Click the left mouse button to close the preview',
    'マウスの左クリックでプレビュー画像を閉じる',
  ],
  _尺寸: ['尺寸', '尺寸', 'Size', 'サイズ'],
  _允许鼠标停留在预览图上: [
    '允许鼠标停留在预览图上',
    '允許滑鼠停留在預覽圖上',
    'Allow the mouse to stay on the preview image',
    'プレビュー画像の上にマウスを置くことができます',
  ],
  _点击预览图时下载作品: [
    '点击预览图时下载作品',
    '點選預覽圖時下載作品',
    'Download the work when you click on the preview',
    'プレビュー画像をクリックするとその作品がダウンロードされます',
  ],
  _转换动图时页面被隐藏的提示: [
    '这个标签页正在转换动图。如果这个标签页被隐藏了，转换速度可能会变慢。',
    '這個標籤頁正在轉換動圖。如果這個標籤頁被隱藏了，轉換速度可能會變慢。',
    'This tab page is converting ugoira. If this tab page is hidden, the conversion speed may slow down.',
    'このタブページはうごイラを変換しています。 このタブを非表示にすると、変換速度が低下する場合があります。',
  ],
  _原始尺寸: ['原始尺寸', '原始尺寸', 'Original size', 'オリジナルサイズ'],
  _增强: ['增强', '增強', 'Enhance', '強化機能'],
  _长按右键显示大图: [
    '在缩略图上长按鼠标右键时显示<span class="key">大图</span>',
    '在縮圖上長按滑鼠右鍵時顯示<span class="key">大圖</span>',
    'Long press the right mouse button on the thumbnail to display the <span class="key">large image</span>',
    'サムネイルでマウスの右ボタンを長押しすると、大きな画像が表示されます。',
  ],
  _鼠标滚轮切换图片: [
    '预览多图作品时，可以使用鼠标滚轮切换图片。',
    '預覽多圖作品時，可以使用滑鼠滾輪切換圖片。',
    'When previewing multi-image works, you can use the mouse wheel to switch images.',
    '複数画像をプレビューする際に、マウスホイールを使って画像を切り替えることができます。',
  ],
  _whatisnew: [
    `提高对多图作品进行宽高检查时的准确性。<br>
    如果你设置了宽高条件，下载时可能会花费更多的时间用于进行宽高检查。`,
    `提高對多圖作品進行寬高檢查時的準確性。<br>
    如果你設定了寬高條件，下載時可能會花費更多的時間用於寬高檢查。`,
    `Improve the accuracy when checking the width and height of multi-image works. <br>
    If you set the width and height conditions, it may take more time to check the width and height when downloading.`,
    `マルチイメージ作品の幅と高さをチェックする際の精度を向上させます。 <br>
    幅と高さの条件を設定すると、ダウンロード時に幅と高さの確認に時間がかかる場合があります。`,
  ],
  _等待时间: ['等待时间', '等待時間', 'Waiting time', '待ち時間'],
  _格式错误: ['格式错误', '格式錯誤', 'Format error', 'フォーマットエラー'],
  _下载数量错误: [
    '下载的页数（作品）数量设置错误',
    '下載的頁數（作品）數量設定錯誤',
    'The number of downloaded pages (works) is set incorrectly',
    '下载页数（作品）设置不正确',
  ],
  _默认下载多页: [
    '开始抓取, 如有多页，默认会下载全部。',
    '開始擷取，如有多頁，預設會下載全部。',
    'Start crawl, if there are multiple pages, the default will be downloaded.',
    'クロールを開始する、複数のページがある場合、デフォルトですべてをダウンロードされます。',
  ],
  _在Patreon赞助我: [
    '在 Patreon 赞助我',
    '在 Patreon 贊助我',
    'Become a patron',
    'Become a patron',
  ],
  _赞助我: ['赞助我', '贊助我', 'Sponsor me', '支援する'],
  _赞助方式提示: [
    `非常感谢您的支持！<br>
    您可以在 Patreon 上赞助我：<br>
    <a href="https://www.patreon.com/xuejianxianzun" target="_blank">https://www.patreon.com/xuejianxianzun</a><br>
    中国大陆用户可以在“爱发电”上赞助我：<br>
    <a href="https://afdian.net/@xuejianxianzun" target="_blank">https://afdian.net/@xuejianxianzun</a><br>
    也可以扫描二维码：<br>
    <a href="https://github.com/xuejianxianzun/PixivBatchDownloader#%E6%94%AF%E6%8C%81%E5%92%8C%E6%8D%90%E5%8A%A9" target="_blank">在 Github 上查看二维码</a> 或者加入 QQ 群 675174717 查看二维码。
    `,
    `非常感謝您的支持！<br>
    您可以在 Patreon 上贊助我：<br>
    <a href="https://www.patreon.com/xuejianxianzun" target="_blank">https://www.patreon.com/xuejianxianzun</a><br>
    中國大陸使用者可以在“愛發電”上贊助我：<br>
    <a href="https://afdian.net/@xuejianxianzun" target="_blank">https://afdian.net/@xuejianxianzun</a><br>
    也可以掃描行動條碼（QR Code）：<br>
    <a href="https://github.com/xuejianxianzun/PixivBatchDownloader#%E6%94%AF%E6%8C%81%E5%92%8C%E6%8D%90%E5%8A%A9" target="_blank">在 Github 上檢視行動條碼</a> 或者加入 QQ 群 675174717 檢視行動條碼。
    `,
    `Thank you very much for your support!<br>
    You can sponsor me on Patreon: <br>
    <a href="https://www.patreon.com/xuejianxianzun" target="_blank">https://www.patreon.com/xuejianxianzun</a>
    `,
    `ご支援してくださった皆様、本当にありがとうございました。<br>
    ご支援してくださった方は、以下の Patreon で：<br>
    <a href="https://www.patreon.com/xuejianxianzun" target="_blank"> https://www.patreon.com/xuejianxianzun </a>
    `,
  ],
  _替换方形缩略图以显示图片比例: [
    '替换方形<span class="key">缩略图</span>以显示图片比例',
    '替換方形<span class="key">縮圖</span>以顯示圖片比例',
    'Replace square <span class="key">thumbnails</span> to show image ratio',
    '正方形のサムネイルを置き換えて、画像のスケールを表示。',
  ],
  _只有一个抓取结果时不建立文件夹: [
    '只有一个抓取结果时<span class="key">不建立</span>文件夹',
    '只有一個擷取結果時<span class="key">不建立</span>資料夾',
    '<span class="key">Do not create</span> a folder when there is only one crawl result',
    'クロール結果が１つのみの場合、フォルダを作成しない',
  ],
  _搜索页面页数限制: [
    '由于 pixiv 的限制，下载器最多只能抓取到第 {} 页。',
    '由於 pixiv 的限制，下載器最多只能擷取到第 {} 頁。',
    'Due to the limitation of pixiv, the downloader can only crawl up to the {}th page.',
    'pixiv の制限により、ダウンローダーは {} ページ目までしかクロールできません。',
  ],
  _获取图片的宽高时出现错误: [
    '获取图片的宽高时出现错误：',
    '獲取圖片的寬高時出現錯誤：',
    'An error occurred while getting the width and height of the image:',
    '画像の幅と高さの取得中にエラーが発生しました：',
  ],
  _上限: ['上限', '上限', 'Upper limit', '上限'],
  _预览搜索结果的数量达到上限的提示: [
    '预览搜索结果的数量已经达到上限，剩余的结果不会显示。',
    '預覽搜尋結果的數量已經達到上限，剩餘的結果不會顯示。',
    'The number of preview search results has reached the upper limit, and the remaining results will not be displayed.',
    'プレビュー検索結果の数が上限に達し、残りの結果は表示されません。',
  ],
  _新增命名标记: [
    '新增命名标记',
    '新增命名標記',
    'Add named tag',
    '名前付きタグを追加',
  ],
  _自定义用户名: [
    '自定义<span class="key">用户名</span>',
    '自訂<span class="key">使用者名稱</span>',
    'Customize <span class="key">username</span>',
    'カスタムユーザー名',
  ],
  _自定义用户名的说明: [
    `有些用户可能会改名，如果你想使用他原来的名字，你可以在这里手动设置他的名字。<br>
    你也可以为用户设置别名。<br>
    当你在命名规则中使用 {user} 标记时，下载器会优先使用你设置的名字。`,
    `有些使用者可能會改名，如果你想使用他原來的名字，你可以在這裡手動設定他的名字。<br>
    你也可以為使用者設定別名。<br>
    當你在命名規則中使用 {user} 標記時，下載器會優先使用你設定的名字。`,
    `Some users may change their name. If you want to use his original name, you can manually set his name here. <br>
    You can also set aliases for users. <br>
    When you use the {user} tag in the naming rule, the downloader will give priority to the name you set.`,
    `ユーザーによっては名前を変更する場合があります。元の名前を使いたい場合は、ここで名前を手動で設定することができます。<br>
    また、ユーザーの別名を設定することも可能です。<br>
    命名規則で {user} タグを使用すると、ダウンローダーは設定された名前を優先的に使用します。`,
  ],
  _移除用户名中的at和后续字符: [
    '移除用户名中的 <span class="key">@</span> 和后续字符',
    '移除使用者名稱中的 <span class="key">@</span> 和後續字元',
    'Remove <span class="key">@</span> and subsequent characters in username',
    'ユーザー名から <span class="key">@</span> 以降の文字を削除する',
  ],
  _移除用户名中的at和后续字符的说明: [
    '例如：Anmi@画集発売中 → Anmi',
    '例如：Anmi@画集発売中 → Anmi',
    'For example：Anmi@画集発売中 → Anmi',
    '例：Anmi@画集発売中 → Anmi',
  ],
  _列表页被限制时返回空结果的提示: [
    'Pixiv 返回了空数据。下载器已暂停抓取，并且会在等待几分钟后继续抓取。',
    'Pixiv 返回了空資料。下載器已暫停抓取，並且會在等待幾分鐘後繼續抓取。',
    'Pixiv returned empty data. The downloader has paused crawling and will resume crawling after a few minutes.',
    'Pixivが空のデータを返しました。 ダウンローダーはクロールを一時停止し、数分後にクロールを再開します。',
  ],
  _解决了抓取搜索页面时被限制的问题的说明: [
    '解决了抓取搜索页面时可能会被 Pixiv 限制的问题。',
    '解決了抓取搜尋頁面時可能會被 Pixiv 限制的問題。',
    'Fixed an issue where crawling search pages could be restricted by Pixiv.',
    'Pixivで検索ページのクロールが制限される問題を修正しました。',
  ],
  _搜索模式: ['搜索模式', '搜尋模式', 'Search mode', '検索モード'],
  _标签部分一致: [
    '标签（部分一致）',
    '標籤（部分一致）',
    'Tags (partial match)',
    'タグ（部分一致）',
  ],
  _标签完全一致: [
    '标签（完全一致）',
    '標籤（完全一致）',
    'Tags (perfect match)',
    'タグ（完全一致）',
  ],
  _标题说明文字: [
    '标题、说明文字',
    '標題、說明文字',
    'Title, Caption',
    'タイトル・キャプション',
  ],
  _正文: ['正文', '本文', 'Text', '本文'],
  _标签标题说明文字: [
    '标签、标题、说明文字',
    '標籤、標題、說明文字',
    'Tags, Titles, Captions',
    'タグ・タイトル・キャプション',
  ],
  _save_file_failed_tip: [
    `{} 保存失败，code：{}。下载器将会重试下载这个文件。`,
    `{} 儲存失敗，code：{}。下載器將會重試下載這個檔案。`,
    `{} save failed, code: {}. The downloader will retry to download the file.`,
    `{} 保存に失敗しました。code：{}。ダウンローダーはファイルのダウンロードを再試行します。`,
  ],
  _user_canceled_tip: [
    `{} 未保存，code：{}。`,
    `{} 未儲存，code：{}。`,
    `{} not saved, code: {}.`,
    `{} 保存されていません。code：{}。`,
  ],
  _FILE_FAILED_tip: [
    '可能是文件名太长，或是其他原因导致文件保存失败。你可以尝试启用高级设置里的“文件名长度限制”。',
    '可能是檔名太長，或是其他原因導致檔案儲存失敗。你可以嘗試啟用高階設定裡的“檔案名稱長度限制”。',
    'Maybe the file name is too long, or other reasons cause the file to fail to save. You can try enabling "File name length limit" in advanced settings.',
    'ファイル名が長すぎるか、他の理由でファイルの保存に失敗した可能性があります。 詳細設定で「ファイル名の長さ制限」を有効にしてみてください。',
  ],
  _显示摘要信息: [
    '显示摘要信息',
    '顯示摘要資訊',
    'Show summary',
    '要約情報を表示する',
  ],
  _显示更大的缩略图: [
    '显示<span class="key">更大</span>的缩略图',
    '顯示<span class="key">更大</span>的縮圖',
    'show <span class="key">larger</span> thumbnails',
    '大きなサムネイルを表示する',
  ],
  _横图占用二倍宽度: [
    '横图占用二倍宽度',
    '橫圖佔用二倍寬度',
    'Horizontal image takes up double the width',
    '水平方向の画像は幅の2倍を占めます',
  ],
  _该功能默认开启: [
    '这个功能默认启用。',
    '這個功能預設啟用。',
    'This feature is enabled by default.',
    'この機能はデフォルトで有効になっています。',
  ],
  _你可以在更多他选项卡的下载分类里找到它: [
    '你可以在“更多”选项卡 → “下载”分类里找到它。（需要先启用“显示高级设置”）',
    '你可以在“更多”選項卡 → “下載”分類裡找到它。（需要先啟用“顯示進階設定”）',
    'You can find it in the "More" tab → "Download" category. ("Show advanced settings" needs to be enabled first)',
    '[もっと]タブ→[ダウンロード]カテゴリにあります。 （最初に「詳細設定を表示」を有効にする必要があります）',
  ],
  _使用鼠标滚轮切换作品里的图片: [
    '使用鼠标滚轮切换多图作品里的图片',
    '使用滑鼠滾輪切換多圖作品裡的圖片',
    'Use the mouse wheel to switch images in multi-image works',
    'マウスホイールを使用して、マルチイメージ作品のイメージを切り替えます',
  ],
  _这可能会阻止页面滚动: [
    '这可能会阻止页面滚动',
    '這可能會阻止頁面滾動',
    '这可能会阻止页面滚动',
    'ページのスクロールを妨げる可能性があります',
  ],
  _动图转换失败的提示: [
    '动图转换失败，id：{}',
    '動圖轉換失敗，id：{}',
    'Ugoira(animation) conversion failed, id: {}',
    'うごイラの変換に失敗しました、id：{}',
  ],
  _作品id无法下载带状态码: [
    '{} 无法下载，状态码：{}',
    '{} 無法下載，狀態碼：{}',
    '{} failed to download, status code: {}',
    '{} ダウンロードに失敗しました、ステータスコード：{}',
  ],
  _作品总数为0: [
    '作品总数为 0，Pixiv 可能拒绝了此次抓取。请稍后重试。',
    '作品總數為 0，Pixiv 可能拒絕了此次抓取。請稍後重試。',
    'The total number of works is 0, Pixiv may have refused this crawl. Please try again later.',
    '作品の総数は 0 です。 Pixivがこのクロールを拒否した可能性があります。 後でもう一度やり直してください。',
  ],
  _快捷键AltP: [
    '快捷键 Alt + P',
    '快捷鍵 Alt + P',
    'Hot key: Alt + P',
    'ホットキー Alt + P',
  ],
  _优化预览作品功能: [
    '优化“预览作品”功能',
    '最佳化“預覽作品”功能',
    'Optimize the "Preview Works" function',
    '「作品のプレビュー」機能を最適化する',
  ],
  _1230更新说明: [
    `1. 在网页标题上显示剩余下载数量<br>
    下载时，网页标题上会显示还有多少个文件尚未下载。<br>
    这样，用户不需要打开下载面板就能够知道下载进度。<br><br>
    2. 用户可以在下载时添加一些新的下载任务。`,
    `1. 在網頁標題上顯示剩餘下載數量<br>
    下載時，網頁標題上會顯示還有多少個檔案尚未下載。<br>
    這樣，使用者不需要開啟下載面板就能夠知道下載進度。<br><br>
    2. 使用者可以在下載時新增一些新的下載任務。`,
    `1. Show remaining downloads on page title<br>
    While downloading, the page title will show how many files are not yet downloaded. <br>
    In this way, the user can know the download progress without opening the download panel.<br><br>
    2. Users can add some new download tasks while downloading.`,
    `1. ページタイトルに残りのダウンロードを表示する<br>
    ダウンロード中、ページタイトルにはまだダウンロードされていないファイルの数が表示されます。 <br>
    このようにして、ユーザーはダウンロードパネルを開かなくてもダウンロードの進行状況を知ることができます。<br><br>
    2. ユーザーは、ダウンロード中にいくつかの新しいダウンロードタスクを追加できます。`,
  ],
  _设定资料: ['设定资料', '設定資料', 'Reference materials', '設定資料'],
  _年龄限制: [
    '<span class="key">年龄</span>限制',
    '<span class="key">年齡</span>限制',
    '<span class="key">Age</span> limit',
    '<span class="key">年齢</span>制限',
  ],
  _收藏状态: [
    '<span class="key">收藏</span>状态',
    '<span class="key">收藏</span>狀態',
    '<span class="key">Bookmark</span> status',
    'ブックマークステータス',
  ],
  _图片色彩: [
    '图片<span class="key">色彩</span>',
    '圖片<span class="key">色彩</span>',
    'Image <span class="key">color</span>',
    '画像の<span class="key">色</span>',
  ],
  _图片数量: [
    '图片<span class="key">数量</span>',
    '圖片<span class="key">數量</span>',
    '<span class="key">Number</span> of images',
    '画像の<span class="key">数</span>',
  ],
  _不抓取多图作品的最后一张图片: [
    '不抓取多图作品的<span class="key">最后一张</span>图片',
    '不抓取多圖作品的<span class="key">最後一張</span>圖片',
    'Do not crawl the <span class="key">last image</span> of multi-image works',
    'マルチ画像作品の<span class="key">最後の画像</span>をつかまないでください',
  ],
  _下载小说的封面图片: [
    '下载小说的<span class="key">封面图片</span>',
    '下載小說的<span class="key">封面圖片</span>',
    '小説の<span class="key">表紙画像</span>をダウンロード',
    'Download the <span class="key">cover image</span> of the novel',
  ],
}

export { langText }
