export interface SettingsForm extends HTMLFormElement {
  setWantPage: HTMLInputElement
  firstFewImages: HTMLInputElement
  downType0: HTMLInputElement
  downType1: HTMLInputElement
  downType2: HTMLInputElement
  downType3: HTMLInputElement
  downSingleImg: HTMLInputElement
  downMultiImg: HTMLInputElement
  firstFewImagesSwitch: HTMLInputElement
  downColorImg: HTMLInputElement
  downBlackWhiteImg: HTMLInputElement
  ugoiraSaveAs: RadioNodeList
  BMKNumMin: HTMLInputElement
  BMKNumMax: HTMLInputElement
  BMKNumAverageSwitch: HTMLInputElement
  BMKNumAverage: HTMLInputElement
  downNotBookmarked: HTMLInputElement
  downBookmarked: HTMLInputElement
  setWHSwitch: HTMLInputElement
  setWidth: HTMLInputElement
  idRange: RadioNodeList
  idRangeInput: HTMLInputElement
  setWidthAndOr: RadioNodeList
  setHeight: HTMLInputElement
  ratio: RadioNodeList
  userRatio: HTMLInputElement
  postDate: HTMLInputElement
  postDateStart: HTMLInputElement
  postDateEnd: HTMLInputElement
  needTag: HTMLInputElement
  notNeedTag: HTMLInputElement
  quietDownload: HTMLInputElement
  downloadThread: HTMLInputElement
  userSetName: HTMLInputElement
  fileNameSelect: HTMLSelectElement
  tagNameToFileName: HTMLInputElement
  noSerialNo: HTMLInputElement
  alwaysFolder: HTMLInputElement
  multipleImageDir: HTMLInputElement
  multipleImageFolderNumber: HTMLInputElement
  multipleImageFolderName: RadioNodeList
  previewResult: HTMLInputElement
  BMKNumSwitch: HTMLInputElement
  ratioSwitch: HTMLInputElement
  idRangeSwitch: HTMLInputElement
  needTagSwitch: HTMLInputElement
  notNeedTagSwitch: HTMLInputElement
  convertUgoiraThread: HTMLInputElement
  sizeSwitch: HTMLInputElement
  sizeMin: HTMLInputElement
  sizeMax: HTMLInputElement
  novelSaveAs: RadioNodeList
  saveNovelMeta: HTMLInputElement
  deduplication: HTMLInputElement
  dupliStrategy: RadioNodeList
  fileNameLengthLimitSwitch: HTMLInputElement
  fileNameLengthLimit: HTMLInputElement
  imageSize: RadioNodeList
  dateFormat: HTMLInputElement
  userSetLang: RadioNodeList
  bmkAfterDL: HTMLInputElement
  widthTag: RadioNodeList
  restrict: RadioNodeList
  userBlockList: HTMLInputElement
  blockList: HTMLInputElement
  needTagMode: RadioNodeList
  theme: RadioNodeList
}
